import type { CurriculumTopic } from "@/lib/curriculum/topic-types";

export const enMappingsTopic: CurriculumTopic = {
  slug: "en-mappings",
  title: "English-to-Spanish Mappings",
  description:
    'English words whose Spanish translation depends entirely on the sentence around them — "mean" is "querer decir" when you\'re asking what someone meant, but "cruel" when describing a person, and a statistical "promedio" in "the mean time"; "him" is "lo," "le," or "con él" depending on his grammatical role in the sentence. These are the words where one memorized Spanish equivalent will mislead you. Click an English chip to see the full range of what it can become.',
  baseCollection: "topic:en-multi-sense",
  facetButtons: [
    { collection: "topic:enmap-to", label: "to", family: "P–T" },
    { collection: "topic:enmap-for", label: "for", family: "F–J" },
    { collection: "topic:enmap-with", label: "with", family: "U–Z" },
    { collection: "topic:enmap-of", label: "of", family: "K–O" },
    { collection: "topic:enmap-take", label: "take", family: "P–T" },
    { collection: "topic:enmap-put", label: "put", family: "P–T" },
    { collection: "topic:enmap-get", label: "get", family: "F–J" },
    { collection: "topic:enmap-go", label: "go", family: "F–J" },
    { collection: "topic:enmap-from", label: "from", family: "F–J" },
    { collection: "topic:enmap-you", label: "you", family: "U–Z" },
    { collection: "topic:enmap-make", label: "make", family: "K–O" },
    { collection: "topic:enmap-have", label: "have", family: "F–J" },
    { collection: "topic:enmap-set", label: "set", family: "P–T" },
    { collection: "topic:enmap-in", label: "in", family: "F–J" },
    { collection: "topic:enmap-give", label: "give", family: "F–J" },
    { collection: "topic:enmap-that", label: "that", family: "P–T" },
    { collection: "topic:enmap-keep", label: "keep", family: "K–O" },
    { collection: "topic:enmap-at", label: "at", family: "A–E" },
    { collection: "topic:enmap-how", label: "how", family: "F–J" },
    { collection: "topic:enmap-what", label: "what", family: "U–Z" },
    { collection: "en:feel", label: "feel", family: "F–J" },
    { collection: "en:tell", label: "tell", family: "P–T" },
    { collection: "topic:enmap-be", label: "be", family: "A–E" },
    { collection: "topic:enmap-come", label: "come", family: "A–E" },
    { collection: "en:ask", label: "ask", family: "A–E" },
    { collection: "en:there", label: "there", family: "P–T" },
    { collection: "en:leave", label: "leave", family: "K–O" },
    { collection: "en:it", label: "it", family: "F–J" },
    { collection: "en:could", label: "could", family: "A–E" },
    { collection: "en:look", label: "look", family: "K–O" },
    { collection: "en:fall", label: "fall", family: "F–J" },
    { collection: "en:turn", label: "turn", family: "P–T" },
    { collection: "en:work", label: "work", family: "U–Z" },
    { collection: "en:pay", label: "pay", family: "P–T" },
    { collection: "en:speak", label: "speak", family: "P–T" },
    { collection: "en:say", label: "say", family: "P–T" },
    { collection: "en:bring", label: "bring", family: "A–E" },
    { collection: "en:as", label: "as", family: "A–E" },
    { collection: "en:see", label: "see", family: "P–T" },
    { collection: "en:let", label: "let", family: "K–O" },
    { collection: "en:like", label: "like", family: "K–O" },
    { collection: "en:think", label: "think", family: "P–T" },
    { collection: "en:on", label: "on", family: "K–O" },
    { collection: "en:open", label: "open", family: "K–O" },
    { collection: "en:want", label: "want", family: "U–Z" },
    { collection: "en:is", label: "is", family: "F–J" },
    { collection: "en:talk", label: "talk", family: "P–T" },
    { collection: "en:them", label: "them", family: "P–T" },
    { collection: "en:catch", label: "catch", family: "A–E" },
    { collection: "en:stop", label: "stop", family: "P–T" },
    { collection: "en:know", label: "know", family: "K–O" },
    { collection: "en:agree", label: "agree", family: "A–E" },
    { collection: "en:if", label: "if", family: "F–J" },
    { collection: "en:start", label: "start", family: "P–T" },
    { collection: "en:use", label: "use", family: "U–Z" },
    { collection: "en:eat", label: "eat", family: "A–E" },
    { collection: "en:drink", label: "drink", family: "A–E" },
    { collection: "en:somebody", label: "somebody", family: "P–T" },
    { collection: "en:one", label: "one", family: "K–O" },
    { collection: "en:old", label: "old", family: "K–O" },
    { collection: "en:bad", label: "bad", family: "A–E" },
    { collection: "en:run", label: "run", family: "P–T" },
    { collection: "en:her", label: "her", family: "F–J" },
    { collection: "en:so", label: "so", family: "P–T" },
    { collection: "en:must", label: "must", family: "K–O" },
    { collection: "en:may", label: "may", family: "K–O" },
    { collection: "en:been", label: "been", family: "A–E" },
    { collection: "en:send", label: "send", family: "P–T" },
    { collection: "en:good", label: "good", family: "F–J" },
    { collection: "en:care", label: "care", family: "A–E" },
    { collection: "en:are", label: "are", family: "A–E" },
    { collection: "en:after", label: "after", family: "A–E" },
    { collection: "en:cost", label: "cost", family: "A–E" },
    { collection: "en:power", label: "power", family: "P–T" },
    { collection: "en:believe", label: "believe", family: "A–E" },
    { collection: "en:next", label: "next", family: "K–O" },
    { collection: "en:would", label: "would", family: "U–Z" },
    { collection: "en:count", label: "count", family: "A–E" },
    { collection: "en:stand", label: "stand", family: "P–T" },
    { collection: "en:even", label: "even", family: "A–E" },
    { collection: "en:this", label: "this", family: "P–T" },
    { collection: "en:white", label: "white", family: "U–Z" },
    { collection: "en:lose", label: "lose", family: "K–O" },
    { collection: "en:who", label: "who", family: "U–Z" },
    { collection: "en:then", label: "then", family: "P–T" },
    { collection: "en:lend", label: "lend", family: "K–O" },
    { collection: "en:finish", label: "finish", family: "F–J" },
    { collection: "en:him", label: "him", family: "F–J" },
    { collection: "en:request", label: "request", family: "P–T" },
    { collection: "en:hard", label: "hard", family: "F–J" },
    { collection: "en:free", label: "free", family: "F–J" },
    { collection: "en:show", label: "show", family: "P–T" },
    { collection: "en:hear", label: "hear", family: "F–J" },
    { collection: "en:own", label: "own", family: "K–O" },
    { collection: "en:break", label: "break", family: "A–E" },
    { collection: "en:able", label: "able", family: "A–E" },
    { collection: "en:slow", label: "slow", family: "P–T" },
    { collection: "en:become", label: "become", family: "A–E" },
    { collection: "en:wear", label: "wear", family: "U–Z" },
    { collection: "en:mean", label: "mean", family: "K–O" },
    { collection: "en:hold", label: "hold", family: "F–J" },
    { collection: "en:return", label: "return", family: "P–T" },
    { collection: "en:all", label: "all", family: "A–E" },
    { collection: "en:many", label: "many", family: "K–O" },
    { collection: "en:made", label: "made", family: "K–O" },
    { collection: "en:some", label: "some", family: "P–T" },
    { collection: "en:the", label: "the", family: "P–T" },
    // Common confusions — translation-choice groups that start from an English
    // word that fans out to several Spanish forms.
    {
      collection: "topic:confusable-pronoun",
      label: "you (tú/usted/ustedes/te), him (lo/le)",
      family: "Common confusions",
    },
    {
      collection: "topic:confusable-determiner",
      label: "un vs. uno, algún vs. alguno, el",
      family: "Common confusions",
    },
  ],
};
