import type { CurriculumTopic } from "@/lib/curriculum/topic-types";

export const mappingsTopic: CurriculumTopic = {
  slug: "mappings",
  title: "Spanish-to-English Mappings",
  description:
    'Spanish words whose English translation depends entirely on the sentence around them — hacer means "do," "make," "ago," or describes the weather; dar means "give," but also "turn on," "feel like," or "face a direction." These are the words where memorizing one English gloss will mislead you. Click a Spanish chip to see the full range of what one word can mean.',
  baseCollection: "topic:multi-sense",
  facetButtons: [
    { collection: "topic:map-ser", label: "ser", family: "P–T" },
    { collection: "topic:map-estar", label: "estar", family: "A–E" },
    { collection: "topic:map-poner", label: "poner", family: "P–T" },
    { collection: "topic:map-tener", label: "tener", family: "P–T" },
    { collection: "topic:map-poder", label: "poder", family: "P–T" },
    { collection: "topic:map-hacer", label: "hacer", family: "F–J" },
    { collection: "topic:map-dar", label: "dar", family: "A–E" },
    { collection: "topic:map-haber", label: "haber", family: "F–J" },
    { collection: "topic:map-ir", label: "ir", family: "F–J" },
    { collection: "topic:map-decir", label: "decir", family: "A–E" },
    { collection: "topic:map-de", label: "de", family: "A–E" },
    { collection: "topic:map-en", label: "en", family: "A–E" },
    { collection: "topic:map-pedir", label: "pedir", family: "P–T" },
    { collection: "topic:map-dejar", label: "dejar", family: "A–E" },
    { collection: "topic:map-hablar", label: "hablar", family: "F–J" },
    { collection: "topic:map-deber", label: "deber", family: "A–E" },
    { collection: "topic:map-querer", label: "querer", family: "P–T" },
    { collection: "topic:map-que", label: "que", family: "P–T" },
    { collection: "topic:map-echar", label: "echar", family: "A–E" },
    { collection: "topic:map-seguir", label: "seguir", family: "P–T" },
    { collection: "topic:map-sentir", label: "sentir", family: "P–T" },
    { collection: "es:quedar", label: "quedar", family: "P–T" },
    { collection: "topic:map-ver", label: "ver", family: "U–Z" },
    { collection: "topic:map-pasar", label: "pasar", family: "P–T" },
    { collection: "topic:map-contar", label: "contar", family: "A–E" },
    { collection: "topic:map-tomar", label: "tomar", family: "P–T" },
    { collection: "es:caer", label: "caer", family: "A–E" },
    { collection: "es:volver", label: "volver", family: "U–Z" },
    { collection: "es:trabajar", label: "trabajar", family: "P–T" },
    { collection: "es:por", label: "por", family: "P–T" },
    { collection: "es:salir", label: "salir", family: "P–T" },
    { collection: "es:esperar", label: "esperar", family: "A–E" },
    { collection: "es:saber", label: "saber", family: "P–T" },
    { collection: "es:con", label: "con", family: "A–E" },
    { collection: "es:a", label: "a", family: "A–E" },
    { collection: "es:conocer", label: "conocer", family: "A–E" },
    { collection: "es:creer", label: "creer", family: "A–E" },
    { collection: "es:valer", label: "valer", family: "U–Z" },
    { collection: "es:cargar", label: "cargar", family: "A–E" },
    { collection: "es:si", label: "si", family: "P–T" },
    { collection: "es:parecer", label: "parecer", family: "P–T" },
    { collection: "es:subir", label: "subir", family: "P–T" },
    { collection: "es:pensar", label: "pensar", family: "P–T" },
    { collection: "es:venir", label: "venir", family: "U–Z" },
    // Common confusions — translation-choice groups that start from a Spanish
    // form. Grouped into the "Common confusions" family by navigation.ts.
    {
      collection: "topic:confusable-possessive",
      label: "su / sus / mi / tu — whose is it?",
      family: "Common confusions",
    },
    {
      collection: "topic:confusable-verb",
      label: "ser vs. estar, voy a, vivir",
      family: "Common confusions",
    },
    {
      collection: "topic:confusable-false-friend",
      label: "False friends (realizar, éxito, largo…)",
      family: "Common confusions",
    },
    {
      collection: "topic:confusable-pronoun",
      label: "él / lo / le / se / tú",
      family: "Common confusions",
    },
    {
      collection: "topic:confusable-determiner",
      label: "un vs. uno, algún vs. alguno, el",
      family: "Common confusions",
    },
  ],
};
