import type { CurriculumTopic } from "@/lib/curriculum/topic-types";

export const phrasalVerbsByParticleTopic: CurriculumTopic = {
  slug: "phrasal-verbs-by-particle",
  title: "Phrasal Verbs by Particle",
  description:
    'One particle, many verbs — click "at" to see look at, yell at, aim at, laugh at, arrive at. The particle is the hard part to guess as a Spanish speaker, since Spanish doesn\'t build meaning this way; seeing it hold constant across unrelated verbs is what makes it stick.',
  baseCollection: "topic:phrasal-verb",
  facetButtons: [
    { collection: "topic:part-up", label: "up", family: "U–Z" },
    { collection: "topic:part-out", label: "out", family: "K–O" },
    { collection: "topic:part-to", label: "to", family: "P–T" },
    { collection: "topic:part-in", label: "in", family: "F–J" },
    { collection: "topic:part-on", label: "on", family: "K–O" },
    { collection: "topic:part-for", label: "for", family: "F–J" },
    { collection: "topic:part-off", label: "off", family: "K–O" },
    { collection: "topic:part-of", label: "of", family: "K–O" },
    { collection: "topic:part-with", label: "with", family: "U–Z" },
    { collection: "topic:part-from", label: "from", family: "F–J" },
    { collection: "particle:back", label: "back", family: "A–E" },
    { collection: "particle:into", label: "into", family: "F–J" },
    { collection: "particle:away", label: "away", family: "A–E" },
    { collection: "particle:about", label: "about", family: "A–E" },
    { collection: "particle:down", label: "down", family: "A–E" },
    { collection: "particle:at", label: "at", family: "A–E" },
    { collection: "particle:through", label: "through", family: "P–T" },
    { collection: "particle:over", label: "over", family: "K–O" },
    { collection: "particle:by", label: "by", family: "A–E" },
    { collection: "particle:like", label: "like", family: "K–O" },
    { collection: "particle:around", label: "around", family: "A–E" },
    { collection: "particle:along", label: "along", family: "A–E" },
    { collection: "particle:apart", label: "apart", family: "A–E" },
    { collection: "particle:after", label: "after", family: "A–E" },
    { collection: "particle:as", label: "as", family: "A–E" },
    { collection: "particle:forward", label: "forward", family: "F–J" },
    { collection: "particle:together", label: "together", family: "P–T" },
    { collection: "particle:onto", label: "onto", family: "K–O" },
    { collection: "particle:across", label: "across", family: "A–E" },
    { collection: "particle:aside", label: "aside", family: "A–E" },
    { collection: "particle:against", label: "against", family: "A–E" },
    { collection: "particle:behind", label: "behind", family: "A–E" },
    { collection: "particle:among", label: "among", family: "A–E" },
    { collection: "particle:under", label: "under", family: "U–Z" },
    { collection: "particle:past", label: "past", family: "P–T" },
    { collection: "particle:ahead", label: "ahead", family: "A–E" },
    { collection: "particle:below", label: "below", family: "A–E" },
    { collection: "particle:toward", label: "toward", family: "P–T" },
    { collection: "particle:before", label: "before", family: "A–E" },
  ],
};
