// Curriculum collection registry.
//
// Collections are namespaced `facet:value` tags. This file is the controlled
// vocabulary: the regression test rejects any database collection whose facet is
// not listed here, and rejects any bare (un-namespaced) collection that is not in
// LEGACY_COLLECTIONS. The legacy set is only allowed to shrink.

export type CollectionFacet =
  | "es"
  | "en"
  | "pos"
  | "grammar"
  | "construction"
  | "form"
  | "morphology"
  | "cognate"
  | "sound"
  | "rhyme"
  | "homophone"
  | "particle"
  | "topic"
  | "register"
  | "dialect"
  | "contrast"
  | "conjugation"
  | "sense"
  | "gender"
  | "degree";

export const COLLECTION_FACETS: Record<CollectionFacet, string> = {
  es: "Spanish headword — every sense and construction of one lemma",
  en: "English headword — every sense that maps to one word",
  pos: "part of speech",
  grammar: "grammatical subcategory (pronoun type, tense, mood, agreement)",
  construction: "sentence pattern or verb-complement shape",
  form: "verb form (past, past participle, gerund, third person) — English morphology drills, not Spanish conjugation",
  conjugation: "Spanish verb conjugation (person, tense, irregularity) for a specific suppletive/irregular verb's finite form — regular verbs stay infinitive-only and are not tagged here",
  sense: "one sense of one verb lemma — the join between a conjugated-form paradigm and the infinitive row whose meaning it realizes. Value shape <lemma>-<slug>, e.g. sense:ser-identidad. See docs/curation/verb-organization-plan-2026-09-05.md",
  morphology: "affix and derivation relationship",
  cognate: "two disjoint value classes: TYPE (0 or 1 per row — transparent / opaque-gloss / false-friend, is the English cognate the actual gloss or not) and PATTERN (0..n per row — a specific <es>-to-<en> spelling-suffix family, or a <esStem>-to-<enRoot> Latin-root family). See docs/curation/cognates-plan-2026-09-05.md",
  sound: "pronunciation family and named sound cluster",
  rhyme: "shared stressed rime, keyed by IPA",
  homophone: "exact same pronunciation, keyed by IPA",
  particle: "phrasal-verb particle",
  topic: "semantic domain",
  register: "formality / spoken vs written",
  dialect: "regional variety",
  contrast: "a confusable pair a Spanish speaker must actively distinguish",
  gender: "grammatical gender of a noun, keyed by the bracketed article: masculine (el), feminine (la), common (el/la), invariant (no gender-marked article)",
  degree: "comparative/superlative form of a gradable adjective",
};

export function collectionFacet(name: string): CollectionFacet | null {
  const facet = name.includes(":") ? name.slice(0, name.indexOf(":")) : null;
  return facet && facet in COLLECTION_FACETS ? (facet as CollectionFacet) : null;
}

// Un-namespaced collections still awaiting a facet. Do not add to this list.
export const LEGACY_COLLECTIONS: ReadonlySet<string> = new Set([
  "a few",
  "a great many",
  "a little",
  "a pesar de",
  "a pile of",
  "absence of obligation",
  "accent contrast",
  "across from",
  "actualidad",
  "adjective before noun",
  "afford",
  "aficionado",
  "after be",
  "agree on",
  "agree to",
  "ahead",
  "alike",
  "all day",
  "all the time",
  "all week",
  "allowed to",
  "almost always",
  "almost never",
  "alternative",
  "another way",
  "any",
  "appear before",
  "appear in",
  "as ... as",
  "as long as",
  "as many as",
  "as much as",
  "at + clock time",
  "attention",
  "auxiliary did",
  "auxiliary does",
  "back then",
  "be + -ing",
  "be + adjective",
  "be + past participle",
  "be over",
  "before i sound",
  "before main verb",
  "before o sound",
  "big deal",
  "birth",
  "building level",
  "but also",
  "cada vez más",
  "calculation",
  "can't remember",
  "can't seem to",
  "capacity",
  "cargo",
  "classification",
  "clothes",
  "collective noun",
  "come + bare infinitive",
  "come back",
  "come out",
  "conditional perfect",
  "conditional perfect progressive",
  "conditional progressive",
  "course",
  "cuando vs cuándo",
  "current affairs",
  "dating",
  "death",
  "debt",
  "defective verb",
  "delay",
  "depending on",
  "desired change",
  "difícil",
  "dining room",
  "disbelief",
  "discourse repair",
  "don't",
  "e",
  "el vs él",
  "embarrassed",
  "emission",
  "employment",
  "equipment",
  "esfuerzo",
  "even if",
  "event location",
  "every day",
  "every week",
  "expected to",
  "fallecer",
  "fan",
  "farewell",
  "feel + adjective",
  "find + object + adjective",
  "fixed connector",
  "for now",
  "forewarned is forearmed",
  "forgiveness",
  "free-choice construction",
  "frente a",
  "fuera",
  "future perfect",
  "future perfect progressive",
  "future progressive",
  "future time",
  "general condition",
  "general idea",
  "general plural",
  "get + past participle",
  "gift",
  "give back",
  "go + bare infinitive",
  "go back",
  "grammar term",
  "grande",
  "growth",
  "had + past participle",
  "had been + present participle",
  "hambre",
  "hand in",
  "hand over",
  "have + past participle",
  "have been + present participle",
  "have not",
  "height",
  "hold back",
  "if I were you",
  "if only",
  "if there is",
  "illness",
  "impersonal",
  "importante",
  "impossible past",
  "impression",
  "in any case",
  "in case",
  "independence",
  "ingredient",
  "instead of",
  "inversion",
  "invitation",
  "laugh",
  "leak",
  "legal",
  "let's",
  "letter writing",
  "limited choice",
  "linking verb",
  "literal pile",
  "literal word combination",
  "lleno",
  "long object after particle",
  "look at",
  "look for",
  "lots of",
  "loud",
  "manage to",
  "market",
  "meal expression",
  "measurement",
  "meeting",
  "mind",
  "more and more",
  "more than enough",
  "motion",
  "music",
  "must not",
  "need to",
  "news",
  "no",
  "no longer",
  "no past participle",
  "no preposition",
  "not anymore",
  "not only",
  "not prohibition",
  "not that",
  "not that many",
  "not that much",
  "noun expression",
  "now that",
  "object after preposition",
  "official seeking",
  "other words",
  "passive perception",
  "past ability",
  "past condition + present result",
  "past expectation",
  "past experience",
  "past form + would",
  "past obligation",
  "past perfect + would have",
  "past perfect progressive",
  "past regret",
  "past time",
  "payment",
  "perception",
  "perfect auxiliary",
  "permitted to",
  "physical effect",
  "physical property",
  "plenty of",
  "polite offer",
  "por poco",
  "prayer",
  "preferred direction expression",
  "prepositional verb",
  "present + present",
  "present + will",
  "present condition + past result",
  "present time",
  "pro-form",
  "protest",
  "proverb",
  "provided that",
  "publication",
  "que + subjunctive",
  "questioning",
  "reaction",
  "real future condition",
  "regional Spanish",
  "related shorter form",
  "religion",
  "remember doing",
  "replacement",
  "return a call",
  "risk",
  "rule",
  "seated",
  "second ambiguity",
  "service",
  "shall",
  "shopping",
  "show up",
  "si vs sí",
  "similarity",
  "sincerarse",
  "size",
  "so many",
  "so much",
  "somebody from doing something",
  "somebody how to do something",
  "something",
  "something is needed",
  "specific idea",
  "specific plural",
  "spite",
  "stop to",
  "subjunctive were",
  "subordinate clause",
  "substance",
  "success expression",
  "takeout",
  "team",
  "tener adjectives",
  "tense",
  "texture",
  "that is",
  "that said",
  "the time",
  "then again",
  "there are",
  "there is",
  "there was",
  "there were",
  "third conditional",
  "though",
  "too many",
  "too much",
  "tradition",
  "training",
  "transbordo",
  "trash",
  "truth",
  "turn oneself in",
  "ultimo",
  "urgency",
  "vehicle",
  "verb + -ing",
  "verb + bare infinitive",
  "water",
  "what time",
  "why clause",
  "will be + present participle",
  "will have + past participle",
  "will have been + present participle",
  "wish + would",
  "would be + present participle",
  "would have + past participle",
  "would have been + present participle",
]);

// Controlled vocabulary for the `grammar:` facet. Unlike the legacy set this may
// grow — but only deliberately: adding a value here is the reviewable step when
// a curation batch or a new topic introduces a grammatical subcategory. The
// regression test rejects any `grammar:<value>` in the database not listed here,
// which catches typos and one-off tags that should have been `topic:` or dropped.
export const KNOWN_GRAMMAR_VALUES: ReadonlySet<string> = new Set([
  "ability", "addition", "adjective-modifier", "adjective-position",
  "adjective-state", "adverb-formation", "advice", "age",
  "agreement", "article", "be", "be-allowed-to",
  "capitalization", "cardinal-number", "causative", "change-of-state",
  "clause", "collocation", "command", "comparative",
  "comparison", "comprehension", "concession", "conditional",
  "continuation", "contraction", "contrast", "correlative",
  "countable", "deduction", "definite-article", "degree",
  "demonstrative", "demonstrative-determiner", "demonstrative-pronoun", "depletion",
  "difficulty", "direct-object-pronoun", "discourse", "distal",
  "effort", "emphasis", "emphatic-affirmative", "emphatic-quantity",
  "estar-adjective", "exception", "excess", "exclamative",
  "existence", "feminine", "first-encounter", "first-person",
  "fixed-expression", "frequency-adverb", "gerund", "goal",
  "going-to", "handle-verb", "human-object", "hypothetical",
  "imperative", "impersonal", "impersonal-necessity", "inability",
  "indefinite-article", "indefinite-pronoun", "indirect-object-pronoun", "ing-noun",
  "intensifier", "interrogative-adverb", "interrogative-determiner", "interrogative-pronoun",
  "introduction",
  "irregular-plural", "linking-verb-adjective", "manner", "masculine",
  "meaning-changing-preterite", "mixed-group", "modal", "negative",
  "neuter", "neuter-article", "noun-phrase", "object-complement",
  "object-control", "object-pronoun", "opportunity", "ordinal-number",
  "origin", "particle", "passive", "past-form-for-distance",
  "past-plan", "perception-verb", "perfect", "permission",
  "person-noun", "personal-pronoun", "perspective-change", "phrasal-verb",
  "plural", "polite-request", "possessive-determiner", "possessive-pronoun",
  "precaution", "preposition-stranding", "prepositional-pronoun", "present-wish",
  "progressive", "prohibition", "pronominal", "pronominal-verb",
  "pronoun-between-verb-and-particle", "proximal", "purpose", "quantifier",
  "question", "reason", "reciprocal-pronoun", "referenced-quantity",
  "reflexive", "reflexive-pronoun", "relative-determiner", "relative-pronoun",
  "resulting-state", "role", "se", "sentence-structure",
  "sequence", "ser-adjective", "singular", "statement-order",
  "subject-pronoun", "subjunctive", "subordinate-subject-pronoun", "suggestion",
  "superlative", "supposed-to", "tener-adjective", "the-other", "three-jobs-of-have",
  "uncountable", "universal-quantifier", "uses-auxiliary-do-for-questions", "verb-direct-object",
  "verb-indirect-object", "warning", "wish", "would-like",
  "zero-article",
]);

// Controlled vocabulary for the `conjugation:` facet — small and deliberate,
// grows only when a new suppletive verb or tense is added to the catalog.
export const KNOWN_CONJUGATION_VALUES: ReadonlySet<string> = new Set([
  "present", "imperfect", "irregular",
  "1sg", "2sg", "3sg", "1pl", "3pl",
  // the anchor infinitive row of a sense's paradigm
  "infinitive",
  // this sense is in verb scope but deliberately has no built paradigm yet
  "deferred",
]);

// Controlled vocabulary for the `sense:` facet — one entry per infinitive
// sense that has been brought into the verb-conjugation system (see
// docs/curation/verb-organization-plan-2026-09-05.md §3, §5). Grows only when
// a verb's sense enumeration is done deliberately, not per new row.
export const KNOWN_SENSE_VALUES: ReadonlySet<string> = new Set([
  "ser-identidad", "ser-clasificacion", "ser-caracteristica", "ser-hora",
  "ser-origen", "ser-lugar-evento", "ser-material", "ser-posesion",
  "ser-impersonal", "ser-pasiva",
  "estar-estado", "estar-lugar", "estar-progresivo", "estar-acuerdo", "estar-punto",
  "ir-destino", "ir-futuro", "ir-transporte", "ir-actividad", "ir-imperativo",
  "irse-partir",
  "tener-posesion", "tener-edad", "tener-obligacion",
  "haber-perfecto", "haber-existencia", "haber-necesidad",
]);

// Controlled vocabulary for the `cognate:` facet (see docs/curation/
// cognates-plan-2026-09-05.md). Two disjoint value classes sharing one
// namespace — a row carries 0-1 TYPE value and 0-n PATTERN values.
export const KNOWN_COGNATE_VALUES: ReadonlySet<string> = new Set([
  // TYPE — mutually exclusive claims about one row's gloss.
  "transparent", "opaque-gloss", "false-friend",

  // PATTERN — spelling-suffix families (Spanish-side <-> English-side swap).
  "able-to-able", "acto-to-act", "al-to-al", "ando-to-ing", "ante-to-ant",
  "anza-to-ance", "ar-to-ar", "ario-to-ary", "arte-to-art", "cion-to-tion",
  "dad-to-ty", "dido-to-ded", "ecto-to-ect", "el-to-el", "ente-to-ent",
  "es-to-s", "ible-to-ible", "ico-to-ic", "icto-to-ict", "ido-to-id",
  "iendo-to-ing", "il-to-ile", "ivo-to-ive", "ma-to-m", "mente-to-ly",
  "orio-to-ory", "oso-to-ous", "sion-to-sion", "sis-to-sis", "tud-to-tude",
  "uro-ura-to-ure",

  // PATTERN — Latin-root families (Spanish stem <-> English root; the
  // spelling does not obviously match, unlike the suffix families above).
  "tener-to-tain", "poner-to-pose", "mitir-to-mit", "ferir-to-fer",
  "ducir-to-duce", "tribuir-to-tribute", "struir-to-struct", "traer-to-tract",
  "escribir-to-scribe", "cluir-to-clude", "decir-to-dict", "ceder-to-cede",
  "primir-to-press", "vertir-to-vert", "servar-to-serve", "solver-to-solve",
  "gerir-to-gest", "hibir-to-hibit", "cibir-to-ceive", "plicar-to-ply",
  "currir-to-cur", "hender-to-hend",

  // Umbrella marker: "this row belongs to some Latin-root family" — lets the
  // Cognates topic page have one "Latin roots" button without enumerating
  // all 22 root families in facetButtons.
  "latin-root",
]);

// Controlled vocabulary for the `gender:` facet — one entry per pos:noun row,
// keyed by the bracketed article: "el" -> masculine, "la" -> feminine,
// "el/la" -> common (same form serves either gender), no gender-marked
// article (los/las-only, or a noun with no singular article) -> invariant.
export const KNOWN_GENDER_VALUES: ReadonlySet<string> = new Set([
  "masculine", "feminine", "common", "neuter", "invariant",
]);

// Controlled vocabulary for the `degree:` facet — comparative/superlative
// forms of a gradable adjective. "positive" marks the base/uninflected form
// so a degree family can be queried as one group.
export const KNOWN_DEGREE_VALUES: ReadonlySet<string> = new Set([
  "positive",
  "comparative-er", "superlative-est",
  "comparative-ier", "superlative-iest",
  "comparative-more", "superlative-most",
  "irregular-comparative", "irregular-superlative",
]);
