// Curriculum collection registry.
//
// Collections are namespaced `facet:value` tags. This file is the controlled
// vocabulary: the regression test rejects any database collection whose facet is
// not listed here, and rejects any bare (un-namespaced) collection that is not in
// LEGACY_COLLECTIONS. The legacy set is only allowed to shrink.

export type CollectionFacet =
  | "es"
  | "en"
  | "pos"
  | "grammar"
  | "construction"
  | "form"
  | "morphology"
  | "cognate"
  | "sound"
  | "rhyme"
  | "homophone"
  | "particle"
  | "topic"
  | "register"
  | "dialect";

export const COLLECTION_FACETS: Record<CollectionFacet, string> = {
  es: "Spanish headword — every sense and construction of one lemma",
  en: "English headword — every sense that maps to one word",
  pos: "part of speech",
  grammar: "grammatical subcategory (pronoun type, tense, mood, agreement)",
  construction: "sentence pattern or verb-complement shape",
  form: "verb form (past, past participle, gerund, third person)",
  morphology: "affix and derivation relationship",
  cognate: "cognate type and spelling-pattern family",
  sound: "pronunciation family and named sound cluster",
  rhyme: "shared stressed rime, keyed by IPA",
  homophone: "exact same pronunciation, keyed by IPA",
  particle: "phrasal-verb particle",
  topic: "semantic domain",
  register: "formality / spoken vs written",
  dialect: "regional variety",
};

export function collectionFacet(name: string): CollectionFacet | null {
  const facet = name.includes(":") ? name.slice(0, name.indexOf(":")) : null;
  return facet && facet in COLLECTION_FACETS ? (facet as CollectionFacet) : null;
}

// Un-namespaced collections still awaiting a facet. Do not add to this list.
export const LEGACY_COLLECTIONS: ReadonlySet<string> = new Set([
  "a few",
  "a great many",
  "a little",
  "a pesar de",
  "a pile of",
  "absence of obligation",
  "accent contrast",
  "across from",
  "actualidad",
  "adjective before noun",
  "afford",
  "aficionado",
  "after be",
  "agree on",
  "agree to",
  "ahead",
  "alike",
  "all day",
  "all the time",
  "all week",
  "allowed to",
  "almost always",
  "almost never",
  "alternative",
  "another way",
  "any",
  "appear before",
  "appear in",
  "as ... as",
  "as long as",
  "as many as",
  "as much as",
  "at + clock time",
  "attention",
  "auxiliary did",
  "auxiliary does",
  "back then",
  "be + -ing",
  "be + adjective",
  "be + past participle",
  "be over",
  "before i sound",
  "before main verb",
  "before o sound",
  "big deal",
  "birth",
  "building level",
  "but also",
  "cada vez más",
  "calculation",
  "can't remember",
  "can't seem to",
  "capacity",
  "cargo",
  "classification",
  "clothes",
  "collective noun",
  "come + bare infinitive",
  "come back",
  "come out",
  "conditional perfect",
  "conditional perfect progressive",
  "conditional progressive",
  "course",
  "cuando vs cuándo",
  "current affairs",
  "dating",
  "death",
  "debt",
  "defective verb",
  "delay",
  "depending on",
  "desired change",
  "difícil",
  "dining room",
  "disbelief",
  "discourse repair",
  "don't",
  "e",
  "el vs él",
  "embarrassed",
  "emission",
  "employment",
  "equipment",
  "esfuerzo",
  "even if",
  "event location",
  "every day",
  "every week",
  "expected to",
  "fallecer",
  "false friend",
  "fan",
  "farewell",
  "feel + adjective",
  "find + object + adjective",
  "fixed connector",
  "for now",
  "forewarned is forearmed",
  "forgiveness",
  "free-choice construction",
  "frente a",
  "fuera",
  "future perfect",
  "future perfect progressive",
  "future progressive",
  "future time",
  "general condition",
  "general idea",
  "general plural",
  "get + past participle",
  "gift",
  "give back",
  "go + bare infinitive",
  "go back",
  "grammar term",
  "grande",
  "growth",
  "had + past participle",
  "had been + present participle",
  "hambre",
  "hand in",
  "hand over",
  "have + past participle",
  "have been + present participle",
  "have not",
  "height",
  "hold back",
  "how many",
  "if I were you",
  "if only",
  "if there is",
  "illness",
  "impersonal",
  "importante",
  "impossible past",
  "impression",
  "in any case",
  "in case",
  "independence",
  "ingredient",
  "instead of",
  "inversion",
  "invitation",
  "laugh",
  "leak",
  "legal",
  "let's",
  "letter writing",
  "limited choice",
  "linking verb",
  "literal pile",
  "literal word combination",
  "lleno",
  "long object after particle",
  "look at",
  "look for",
  "lots of",
  "loud",
  "manage to",
  "market",
  "meal expression",
  "measurement",
  "meeting",
  "mind",
  "more and more",
  "more than enough",
  "motion",
  "music",
  "must not",
  "need to",
  "news",
  "no",
  "no longer",
  "no past participle",
  "no preposition",
  "not anymore",
  "not only",
  "not prohibition",
  "not that",
  "not that many",
  "not that much",
  "noun expression",
  "now that",
  "object after preposition",
  "official seeking",
  "other words",
  "passive perception",
  "past ability",
  "past condition + present result",
  "past expectation",
  "past experience",
  "past form + would",
  "past obligation",
  "past perfect + would have",
  "past perfect progressive",
  "past regret",
  "past time",
  "payment",
  "perception",
  "perfect auxiliary",
  "permitted to",
  "physical effect",
  "physical property",
  "plenty of",
  "polite offer",
  "por poco",
  "prayer",
  "preferred direction expression",
  "prepositional verb",
  "present + present",
  "present + will",
  "present condition + past result",
  "present time",
  "pro-form",
  "protest",
  "proverb",
  "provided that",
  "publication",
  "que + subjunctive",
  "questioning",
  "reaction",
  "real future condition",
  "regional Spanish",
  "related shorter form",
  "religion",
  "remember doing",
  "replacement",
  "return a call",
  "risk",
  "rule",
  "seated",
  "second ambiguity",
  "service",
  "shall",
  "shopping",
  "show up",
  "si vs sí",
  "similarity",
  "sincerarse",
  "size",
  "so many",
  "so much",
  "somebody from doing something",
  "somebody how to do something",
  "something",
  "something is needed",
  "specific idea",
  "specific plural",
  "spite",
  "stop to",
  "subjunctive were",
  "subordinate clause",
  "substance",
  "success expression",
  "takeout",
  "team",
  "tener adjectives",
  "tense",
  "texture",
  "that is",
  "that said",
  "the time",
  "then again",
  "there are",
  "there is",
  "there was",
  "there were",
  "third conditional",
  "though",
  "too many",
  "too much",
  "tradition",
  "training",
  "transbordo",
  "trash",
  "truth",
  "turn oneself in",
  "ultimo",
  "urgency",
  "vehicle",
  "verb + -ing",
  "verb + bare infinitive",
  "water",
  "what time",
  "why clause",
  "will be + present participle",
  "will have + past participle",
  "will have been + present participle",
  "wish + would",
  "would be + present participle",
  "would have + past participle",
  "would have been + present participle",
]);
