// Curriculum macrotags. Each is a curated view of /admin/curriculum scoped to one
// base collection, with quick-filter buttons for its sub-facets, shown inline
// on the curriculum table.

export type CurriculumTopic = {
  slug: string;
  title: string;
  description: string;
  baseCollection: string;
  facetButtons: Array<{ collection: string; label: string }>;
};

export const CURRICULUM_TOPICS: CurriculumTopic[] = [
  {
    slug: "pronouns",
    title: "Pronouns",
    description:
      "Every pronoun, Spanish to English, with its grammatical role. Click a Spanish or English chip to trace one form across the whole system.",
    baseCollection: "topic:pronoun",
    facetButtons: [
      { collection: "grammar:subject-pronoun", label: "Subject" },
      { collection: "grammar:direct-object-pronoun", label: "Direct object" },
      { collection: "grammar:indirect-object-pronoun", label: "Indirect object" },
      { collection: "grammar:prepositional-pronoun", label: "Prepositional" },
      { collection: "grammar:possessive-determiner", label: "Possessive (det)" },
      { collection: "grammar:possessive-pronoun", label: "Possessive (pron)" },
      { collection: "grammar:reflexive-pronoun", label: "Reflexive" },
      { collection: "grammar:reciprocal-pronoun", label: "Reciprocal" },
      { collection: "grammar:demonstrative-determiner", label: "Demonstrative (det)" },
      { collection: "grammar:demonstrative-pronoun", label: "Demonstrative (pron)" },
      { collection: "grammar:indefinite-pronoun", label: "Indefinite" },
      { collection: "grammar:interrogative-pronoun", label: "Interrogative" },
      { collection: "grammar:relative-pronoun", label: "Relative" },
      { collection: "grammar:exclamative", label: "Exclamative" },
      { collection: "grammar:subordinate-subject-pronoun", label: "él → him" },
      { collection: "contrast:confusable", label: "Confusions" },
    ],
  },
  {
    slug: "determiners",
    title: "Determiners",
    description:
      "Everything that can stand where “the” does in front of a noun — articles, demonstratives, possessives, quantifiers, and numbers. Click a Spanish or English chip to trace one form.",
    baseCollection: "topic:determiner",
    facetButtons: [
      { collection: "grammar:definite-article", label: "Definite article" },
      { collection: "grammar:indefinite-article", label: "Indefinite article" },
      { collection: "grammar:demonstrative-determiner", label: "Demonstrative" },
      { collection: "grammar:possessive-determiner", label: "Possessive" },
      { collection: "grammar:quantifier", label: "Quantifier" },
      { collection: "grammar:cardinal-number", label: "Number" },
      { collection: "grammar:interrogative-determiner", label: "Interrogative" },
      { collection: "grammar:relative-determiner", label: "Relative (cuyo)" },
      { collection: "grammar:negative", label: "Negative (ningún)" },
      { collection: "contrast:confusable", label: "Confusions" },
    ],
  },
  {
    slug: "interrogatives",
    title: "Interrogatives",
    description:
      "The question words — qué, quién, cuál, cuándo, dónde, cómo, cuánto, por qué — as pronouns, determiners, and adverbs. Click a chip to trace one form.",
    baseCollection: "topic:interrogative",
    facetButtons: [
      { collection: "grammar:interrogative-pronoun", label: "Pronoun" },
      { collection: "grammar:interrogative-determiner", label: "Determiner" },
      { collection: "grammar:interrogative-adverb", label: "Adverb" },
      { collection: "contrast:confusable", label: "Confusions" },
    ],
  },
  {
    slug: "verbs",
    title: "Verbs",
    description:
      "Regular verbs stay infinitive-only — conjugation is a rule, not vocabulary. This is the short list of suppletive/irregular verbs whose conjugated forms don't resemble the infinitive: ser and estar (both “to be”), ir (“to go” / going-to), tener (“to have”), haber (“to have done”).",
    baseCollection: "pos:verb",
    facetButtons: [
      { collection: "es:ser", label: "ser (to be)" },
      { collection: "es:estar", label: "estar (to be)" },
      { collection: "es:ir", label: "ir (to go / going to)" },
      { collection: "es:tener", label: "tener (to have)" },
      { collection: "es:haber", label: "haber (have done)" },
      { collection: "conjugation:1sg", label: "I (yo)" },
      { collection: "conjugation:3sg", label: "he / she / it" },
      { collection: "contrast:confusable", label: "Confusions" },
    ],
  },
  {
    slug: "cognates",
    title: "Cognates",
    description:
      "Words that share a Spanish/English root, grouped by the transformation trick that gets you from one to the other — spelling suffixes (-ción → -tion), Latin roots that don't share a spelling (tener → contain), and false friends that look related but aren't.",
    baseCollection: "topic:cognate",
    facetButtons: [
      { collection: "cognate:transparent", label: "Identical / transparent" },
      { collection: "cognate:opaque-gloss", label: "Looks different" },
      { collection: "cognate:false-friend", label: "False friends" },
      // Spelling-suffix families.
      { collection: "cognate:able-to-able", label: "-able → -able" },
      { collection: "cognate:acto-to-act", label: "-acto → -act" },
      { collection: "cognate:al-to-al", label: "-al → -al" },
      { collection: "cognate:ando-to-ing", label: "-ando → -ing" },
      { collection: "cognate:ante-to-ant", label: "-ante → -ant" },
      { collection: "cognate:anza-to-ance", label: "-anza → -ance" },
      { collection: "cognate:ar-to-ar", label: "-ar → -ar" },
      { collection: "cognate:ario-to-ary", label: "-ario → -ary" },
      { collection: "cognate:arte-to-art", label: "-arte → -art" },
      { collection: "cognate:cion-to-tion", label: "-ción → -tion" },
      { collection: "cognate:dad-to-ty", label: "-dad → -ty" },
      { collection: "cognate:dido-to-ded", label: "-dido → -ded" },
      { collection: "cognate:ecto-to-ect", label: "-ecto → -ect" },
      { collection: "cognate:el-to-el", label: "-el → -el" },
      { collection: "cognate:ente-to-ent", label: "-ente → -ent" },
      { collection: "cognate:es-to-s", label: "-es → -s" },
      { collection: "cognate:ible-to-ible", label: "-ible → -ible" },
      { collection: "cognate:ico-to-ic", label: "-ico → -ic" },
      { collection: "cognate:icto-to-ict", label: "-icto → -ict" },
      { collection: "cognate:ido-to-id", label: "-ido → -id" },
      { collection: "cognate:iendo-to-ing", label: "-iendo → -ing" },
      { collection: "cognate:il-to-ile", label: "-il → -ile" },
      { collection: "cognate:ivo-to-ive", label: "-ivo → -ive" },
      { collection: "cognate:ma-to-m", label: "-ma → -m" },
      { collection: "cognate:mente-to-ly", label: "-mente → -ly" },
      { collection: "cognate:orio-to-ory", label: "-orio → -ory" },
      { collection: "cognate:oso-to-ous", label: "-oso → -ous" },
      { collection: "cognate:sion-to-sion", label: "-sión → -sion" },
      { collection: "cognate:sis-to-sis", label: "-sis → -sis" },
      { collection: "cognate:tud-to-tude", label: "-tud → -tude" },
      { collection: "cognate:uro-ura-to-ure", label: "-uro/-ura → -ure" },
      // Latin-root families (spelling doesn't match; grouped by verb stem).
      { collection: "cognate:latin-root", label: "Latin roots (any)" },
      { collection: "cognate:tener-to-tain", label: "tener → -tain" },
      { collection: "cognate:poner-to-pose", label: "poner → -pose" },
      { collection: "cognate:mitir-to-mit", label: "mitir/meter → -mit" },
      { collection: "cognate:ferir-to-fer", label: "ferir/frir → -fer" },
      { collection: "cognate:ducir-to-duce", label: "ducir → -duce" },
      { collection: "cognate:tribuir-to-tribute", label: "tribuir → -tribute" },
      { collection: "cognate:struir-to-struct", label: "struir → -struct" },
      { collection: "cognate:traer-to-tract", label: "traer → -tract" },
      { collection: "cognate:escribir-to-scribe", label: "escribir → -scribe" },
      { collection: "cognate:cluir-to-clude", label: "cluir → -clude" },
      { collection: "cognate:decir-to-dict", label: "decir → -dict" },
      { collection: "cognate:ceder-to-cede", label: "ceder → -cede" },
      { collection: "cognate:primir-to-press", label: "primir/presar → -press" },
      { collection: "cognate:vertir-to-vert", label: "vertir → -vert" },
      { collection: "cognate:servar-to-serve", label: "servar → -serve" },
      { collection: "cognate:solver-to-solve", label: "solver → -solve" },
      { collection: "cognate:gerir-to-gest", label: "gerir → -gest" },
      { collection: "cognate:hibir-to-hibit", label: "hibir → -hibit" },
      { collection: "cognate:cibir-to-ceive", label: "cibir → -ceive" },
      { collection: "cognate:plicar-to-ply", label: "plicar → -ply" },
      { collection: "cognate:currir-to-cur", label: "currir → -cur" },
      { collection: "cognate:hender-to-hend", label: "hender/prender → -hend" },
      { collection: "contrast:confusable", label: "Confusions" },
    ],
  },
  {
    slug: "nouns",
    title: "Nouns",
    description:
      "Every noun, with its article bracketed to show gender — [la] mesa, [el] hombre, [el/la] estudiante — plus a subject-matter theme so you can browse by topic instead of alphabetically.",
    baseCollection: "pos:noun",
    facetButtons: [
      { collection: "gender:masculine", label: "el (masculine)" },
      { collection: "gender:feminine", label: "la (feminine)" },
      { collection: "gender:common", label: "el/la (common)" },
      { collection: "gender:invariant", label: "No article" },
      { collection: "gender:neuter", label: "lo (neuter)" },
      { collection: "topic:abstract-quality", label: "Abstract" },
      { collection: "topic:people", label: "People" },
      { collection: "topic:everyday-objects", label: "Everyday objects" },
      { collection: "topic:time", label: "Time" },
      { collection: "topic:family", label: "Family" },
      { collection: "topic:places", label: "Places" },
      { collection: "topic:calendar", label: "Calendar" },
      { collection: "topic:education", label: "Education" },
      { collection: "topic:business-work", label: "Business & work" },
      { collection: "topic:money-business", label: "Money" },
      { collection: "topic:food", label: "Food" },
      { collection: "topic:technology", label: "Technology" },
      { collection: "topic:health", label: "Health" },
      { collection: "topic:government-politics", label: "Government & politics" },
      { collection: "topic:crime-law", label: "Crime & law" },
      { collection: "topic:art-culture", label: "Art & culture" },
      { collection: "topic:communication-request", label: "Communication & requests" },
      { collection: "topic:sports-recreation", label: "Sports & travel" },
      { collection: "topic:event", label: "Events" },
      { collection: "contrast:confusable", label: "Confusions" },
    ],
  },
  {
    slug: "adjectives",
    title: "Adjectives",
    description:
      "Every adjective, with its copula bracketed to show how it's actually used — [ser] importante, [estar] listo, [tener] hambre — plus comparative/superlative forms and a quality-based theme.",
    baseCollection: "pos:adjective",
    facetButtons: [
      { collection: "grammar:ser-adjective", label: "ser (permanent)" },
      { collection: "grammar:estar-adjective", label: "estar (state)" },
      { collection: "grammar:tener-adjective", label: "tener (idiom)" },
      { collection: "degree:comparative-er", label: "-er (harder)" },
      { collection: "degree:superlative-est", label: "-est (hardest)" },
      { collection: "degree:comparative-more", label: "more ___" },
      { collection: "degree:superlative-most", label: "most ___" },
      { collection: "degree:irregular-comparative", label: "irregular comparative" },
      { collection: "degree:irregular-superlative", label: "irregular superlative" },
      { collection: "topic:abstract-quality", label: "Abstract quality" },
      { collection: "topic:condition-state", label: "Condition / state" },
      { collection: "topic:emotion-state", label: "Emotion" },
      { collection: "topic:personality", label: "Personality" },
      { collection: "topic:age", label: "Age" },
      { collection: "topic:value-price", label: "Value / price" },
      { collection: "topic:size", label: "Size" },
      { collection: "topic:nationality", label: "Nationality" },
      { collection: "topic:difficulty", label: "Difficulty" },
      { collection: "topic:color", label: "Color" },
      { collection: "topic:weather", label: "Weather" },
      { collection: "topic:speed", label: "Speed" },
      { collection: "contrast:confusable", label: "Confusions" },
    ],
  },
  {
    slug: "mappings",
    title: "Spanish-to-English Mappings",
    description:
      "Spanish words whose English translation depends entirely on the sentence around them — hacer means \"do,\" \"make,\" \"ago,\" or describes the weather; dar means \"give,\" but also \"turn on,\" \"feel like,\" or \"face a direction.\" These are the words where memorizing one English gloss will mislead you. Click a Spanish chip to see the full range of what one word can mean.",
    baseCollection: "topic:multi-sense",
    facetButtons: [
      { collection: "es:ser", label: "ser" },
      { collection: "es:estar", label: "estar" },
      { collection: "es:poner", label: "poner" },
      { collection: "es:tener", label: "tener" },
      { collection: "es:poder", label: "poder" },
      { collection: "es:hacer", label: "hacer" },
      { collection: "es:dar", label: "dar" },
      { collection: "es:haber", label: "haber" },
      { collection: "es:ir", label: "ir" },
      { collection: "es:decir", label: "decir" },
      { collection: "es:de", label: "de" },
      { collection: "es:en", label: "en" },
      { collection: "es:pedir", label: "pedir" },
      { collection: "es:dejar", label: "dejar" },
      { collection: "es:hablar", label: "hablar" },
      { collection: "es:deber", label: "deber" },
      { collection: "es:querer", label: "querer" },
      { collection: "es:que", label: "que" },
      { collection: "es:echar", label: "echar" },
      { collection: "es:seguir", label: "seguir" },
      { collection: "es:sentir", label: "sentir" },
      { collection: "es:quedar", label: "quedar" },
      { collection: "es:ver", label: "ver" },
      { collection: "es:pasar", label: "pasar" },
      { collection: "es:contar", label: "contar" },
      { collection: "es:tomar", label: "tomar" },
      { collection: "es:caer", label: "caer" },
      { collection: "es:volver", label: "volver" },
      { collection: "es:trabajar", label: "trabajar" },
      { collection: "es:por", label: "por" },
      { collection: "es:salir", label: "salir" },
      { collection: "es:esperar", label: "esperar" },
      { collection: "es:saber", label: "saber" },
      { collection: "es:con", label: "con" },
      { collection: "es:a", label: "a" },
      { collection: "es:conocer", label: "conocer" },
      { collection: "es:creer", label: "creer" },
      { collection: "es:valer", label: "valer" },
      { collection: "es:cargar", label: "cargar" },
      { collection: "es:si", label: "si" },
      { collection: "es:parecer", label: "parecer" },
      { collection: "es:subir", label: "subir" },
      { collection: "es:pensar", label: "pensar" },
      { collection: "es:venir", label: "venir" },
    ],
  },
  {
    slug: "en-mappings",
    title: "English-to-Spanish Mappings",
    description:
      "English words whose Spanish translation depends entirely on the sentence around them — \"mean\" is \"querer decir\" when you're asking what someone meant, but \"cruel\" when describing a person, and a statistical \"promedio\" in \"the mean time\"; \"him\" is \"lo,\" \"le,\" or \"con él\" depending on his grammatical role in the sentence. These are the words where one memorized Spanish equivalent will mislead you. Click an English chip to see the full range of what it can become.",
    baseCollection: "topic:en-multi-sense",
    facetButtons: [
      { collection: "en:to", label: "to" },
      { collection: "en:for", label: "for" },
      { collection: "en:with", label: "with" },
      { collection: "en:of", label: "of" },
      { collection: "en:take", label: "take" },
      { collection: "en:put", label: "put" },
      { collection: "en:get", label: "get" },
      { collection: "en:go", label: "go" },
      { collection: "en:from", label: "from" },
      { collection: "en:you", label: "you" },
      { collection: "en:make", label: "make" },
      { collection: "en:have", label: "have" },
      { collection: "en:set", label: "set" },
      { collection: "en:in", label: "in" },
      { collection: "en:give", label: "give" },
      { collection: "en:that", label: "that" },
      { collection: "en:keep", label: "keep" },
      { collection: "en:at", label: "at" },
      { collection: "en:how", label: "how" },
      { collection: "en:what", label: "what" },
      { collection: "en:feel", label: "feel" },
      { collection: "en:tell", label: "tell" },
      { collection: "en:be", label: "be" },
      { collection: "en:come", label: "come" },
      { collection: "en:ask", label: "ask" },
      { collection: "en:there", label: "there" },
      { collection: "en:leave", label: "leave" },
      { collection: "en:it", label: "it" },
      { collection: "en:could", label: "could" },
      { collection: "en:look", label: "look" },
      { collection: "en:fall", label: "fall" },
      { collection: "en:turn", label: "turn" },
      { collection: "en:work", label: "work" },
      { collection: "en:pay", label: "pay" },
      { collection: "en:speak", label: "speak" },
      { collection: "en:say", label: "say" },
      { collection: "en:bring", label: "bring" },
      { collection: "en:as", label: "as" },
      { collection: "en:see", label: "see" },
      { collection: "en:let", label: "let" },
      { collection: "en:like", label: "like" },
      { collection: "en:think", label: "think" },
      { collection: "en:on", label: "on" },
      { collection: "en:open", label: "open" },
      { collection: "en:want", label: "want" },
      { collection: "en:is", label: "is" },
      { collection: "en:talk", label: "talk" },
      { collection: "en:them", label: "them" },
      { collection: "en:catch", label: "catch" },
      { collection: "en:stop", label: "stop" },
      { collection: "en:know", label: "know" },
      { collection: "en:agree", label: "agree" },
      { collection: "en:if", label: "if" },
      { collection: "en:start", label: "start" },
      { collection: "en:use", label: "use" },
      { collection: "en:eat", label: "eat" },
      { collection: "en:drink", label: "drink" },
      { collection: "en:somebody", label: "somebody" },
      { collection: "en:one", label: "one" },
      { collection: "en:old", label: "old" },
      { collection: "en:bad", label: "bad" },
      { collection: "en:run", label: "run" },
      { collection: "en:her", label: "her" },
      { collection: "en:so", label: "so" },
      { collection: "en:must", label: "must" },
      { collection: "en:may", label: "may" },
      { collection: "en:been", label: "been" },
      { collection: "en:send", label: "send" },
      { collection: "en:good", label: "good" },
      { collection: "en:care", label: "care" },
      { collection: "en:are", label: "are" },
      { collection: "en:after", label: "after" },
      { collection: "en:cost", label: "cost" },
      { collection: "en:power", label: "power" },
      { collection: "en:believe", label: "believe" },
      { collection: "en:next", label: "next" },
      { collection: "en:would", label: "would" },
      { collection: "en:count", label: "count" },
      { collection: "en:stand", label: "stand" },
      { collection: "en:even", label: "even" },
      { collection: "en:this", label: "this" },
      { collection: "en:white", label: "white" },
      { collection: "en:lose", label: "lose" },
      { collection: "en:who", label: "who" },
      { collection: "en:then", label: "then" },
      { collection: "en:lend", label: "lend" },
      { collection: "en:finish", label: "finish" },
      { collection: "en:him", label: "him" },
      { collection: "en:request", label: "request" },
      { collection: "en:hard", label: "hard" },
      { collection: "en:free", label: "free" },
      { collection: "en:show", label: "show" },
      { collection: "en:hear", label: "hear" },
      { collection: "en:own", label: "own" },
      { collection: "en:break", label: "break" },
      { collection: "en:able", label: "able" },
      { collection: "en:slow", label: "slow" },
      { collection: "en:become", label: "become" },
      { collection: "en:wear", label: "wear" },
      { collection: "en:mean", label: "mean" },
      { collection: "en:hold", label: "hold" },
      { collection: "en:return", label: "return" },
      { collection: "en:all", label: "all" },
      { collection: "en:many", label: "many" },
      { collection: "en:made", label: "made" },
      { collection: "en:some", label: "some" },
      { collection: "en:the", label: "the" },
    ],
  },
];

export function findCurriculumTopic(slug: string): CurriculumTopic | undefined {
  return CURRICULUM_TOPICS.find((topic) => topic.slug === slug);
}
