// Curriculum macrotags. Each is a curated view of /admin/curriculum scoped to one
// base collection, with quick-filter buttons for its sub-facets, shown inline
// on the curriculum table.

import type { TopicBaseExclusion } from "@/lib/curriculum/scope";

export type CurriculumTopic = {
  slug: string;
  title: string;
  description: string;
  baseCollection: string;
  // Material that carries `baseCollection` but does not belong in this page's
  // browser. See src/lib/curriculum/scope.ts for the rule and the rationale.
  baseExclusions?: readonly TopicBaseExclusion[];
  facetButtons: Array<{ collection: string; label: string; family: string }>;
};

export const CURRICULUM_TOPICS: CurriculumTopic[] = [
  {
    slug: "pronouns",
    title: "Pronouns",
    description:
      "Every pronoun, Spanish to English, with its grammatical role. Click a Spanish or English chip to trace one form across the whole system.",
    baseCollection: "topic:pronoun",
    facetButtons: [
      {
        collection: "grammar:subject-pronoun",
        label: "Subject",
        family: "Pronoun types",
      },
      {
        collection: "grammar:direct-object-pronoun",
        label: "Direct object",
        family: "Pronoun types",
      },
      {
        collection: "grammar:indirect-object-pronoun",
        label: "Indirect object",
        family: "Pronoun types",
      },
      {
        collection: "grammar:prep-pronoun-con",
        label: "Prepositional — con",
        family: "Pronoun types",
      },
      {
        collection: "grammar:prep-pronoun-para",
        label: "Prepositional — para",
        family: "Pronoun types",
      },
      {
        collection: "grammar:prep-pronoun-a",
        label: "Prepositional — a",
        family: "Pronoun types",
      },
      {
        collection: "grammar:possessive-determiner",
        label: "Possessive (det)",
        family: "Pronoun types",
      },
      {
        collection: "grammar:possessive-pronoun",
        label: "Possessive (pron)",
        family: "Pronoun types",
      },
      {
        collection: "grammar:reflexive-pronoun",
        label: "Reflexive",
        family: "Pronoun types",
      },
      {
        collection: "grammar:reciprocal-pronoun",
        label: "Reciprocal",
        family: "Pronoun types",
      },
      {
        collection: "grammar:demonstrative-determiner",
        label: "Demonstrative (det)",
        family: "Pronoun types",
      },
      {
        collection: "grammar:demonstrative-pronoun",
        label: "Demonstrative (pron)",
        family: "Pronoun types",
      },
      {
        collection: "grammar:indef-pronoun-person",
        label: "Indefinite — Person",
        family: "Pronoun types",
      },
      {
        collection: "grammar:indef-pronoun-thing",
        label: "Indefinite — Thing",
        family: "Pronoun types",
      },
      {
        collection: "grammar:indef-pronoun-place",
        label: "Indefinite — Place",
        family: "Pronoun types",
      },
      {
        collection: "grammar:indef-pronoun-quantity",
        label: "Indefinite — Quantity",
        family: "Pronoun types",
      },
      {
        collection: "grammar:interrogative-pronoun",
        label: "Interrogative",
        family: "Pronoun types",
      },
      {
        collection: "grammar:relative-pronoun",
        label: "Relative",
        family: "Pronoun types",
      },
      {
        collection: "grammar:exclamative",
        label: "Exclamative",
        family: "Pronoun types",
      },
      {
        collection: "grammar:subordinate-subject-pronoun",
        label: "él → him",
        family: "Pronoun types",
      },
    ],
  },
  {
    slug: "determiners",
    title: "Determiners",
    description:
      "Everything that can stand where “the” does in front of a noun — articles, demonstratives, possessives, quantifiers, and numbers. Click a Spanish or English chip to trace one form.",
    baseCollection: "topic:determiner",
    facetButtons: [
      {
        collection: "grammar:definite-article",
        label: "Definite article",
        family: "Determiner types",
      },
      {
        collection: "grammar:indefinite-article",
        label: "Indefinite article",
        family: "Determiner types",
      },
      {
        collection: "grammar:demonstrative-determiner",
        label: "Demonstrative",
        family: "Determiner types",
      },
      {
        collection: "grammar:possessive-determiner",
        label: "Possessive",
        family: "Determiner types",
      },
      {
        collection: "topic:quant-much-many",
        label: "Quantifier — Much & Many",
        family: "Determiner types",
      },
      {
        collection: "topic:quant-little-few",
        label: "Quantifier — Little & Few",
        family: "Determiner types",
      },
      {
        collection: "topic:quant-more-less",
        label: "Quantifier — More & Less",
        family: "Determiner types",
      },
      {
        collection: "topic:quant-both-all-whole",
        label: "Quantifier — Both, All & Whole",
        family: "Determiner types",
      },
      {
        collection: "topic:quant-some-any-no",
        label: "Quantifier — Some, Any & No",
        family: "Determiner types",
      },
      {
        collection: "topic:quant-other-certain-such",
        label: "Quantifier — Other, Certain & Such",
        family: "Determiner types",
      },
      {
        collection: "topic:cardinal-1-10",
        label: "Number — 1-10",
        family: "Determiner types",
      },
      {
        collection: "topic:cardinal-11-19",
        label: "Number — 11-19",
        family: "Determiner types",
      },
      {
        collection: "topic:cardinal-tens-and-up",
        label: "Number — Tens & Up",
        family: "Determiner types",
      },
      {
        collection: "grammar:interrogative-determiner",
        label: "Interrogative",
        family: "Determiner types",
      },
      {
        collection: "grammar:relative-determiner",
        label: "Relative (cuyo)",
        family: "Determiner types",
      },
      {
        collection: "grammar:negative",
        label: "Negative (ningún)",
        family: "Determiner types",
      },
    ],
  },
  {
    slug: "interrogatives",
    title: "Interrogatives",
    description:
      "The question words — qué, quién, cuál, cuándo, dónde, cómo, cuánto, por qué — as pronouns, determiners, and adverbs. Click a chip to trace one form.",
    baseCollection: "topic:interrogative",
    facetButtons: [
      {
        collection: "grammar:interrogative-pronoun",
        label: "Pronoun",
        family: "Question-word roles",
      },
      {
        collection: "grammar:interrogative-determiner",
        label: "Determiner",
        family: "Question-word roles",
      },
      {
        collection: "grammar:interrogative-adverb",
        label: "Adverb",
        family: "Question-word roles",
      },
    ],
  },
  {
    slug: "verbs",
    title: "Verbs",
    description:
      "Plain, everyday verbs grouped by theme instead of alphabetically — communication, thinking, movement, possession, money, and more — so you can browse them the way you'd actually reach for them in conversation. The copula/modal machinery (to be, to have, can, must) lives on the Special Verbs page; cognate verbs on Cognates; phrasal verbs on the two Phrasal Verbs pages.",
    baseCollection: "pos:verb",
    // The Verbs page is plain lexical verbs only. Three unconditional
    // exclusions send the rest to their own pages: `topic:verb-system` (ser /
    // estar / haber / hay / modals) -> Special Verbs; `topic:cognate` ->
    // Cognates (by spelling pattern); `topic:phrasal-verb` -> the two Phrasal
    // Verbs pages (by root, by particle).
    baseExclusions: [
      { collection: "topic:verb-system", unlessRole: [] },
      { collection: "topic:cognate", unlessRole: [] },
      { collection: "topic:phrasal-verb", unlessRole: [] },
    ],
    facetButtons: [
      // Communication
      { collection: "topic:verb-communication-talking", label: "Talking", family: "Communication" },
      { collection: "topic:verb-communication-saying", label: "Saying & Telling", family: "Communication" },
      { collection: "topic:verb-communication-other", label: "Informing & Reporting", family: "Communication" },
      { collection: "topic:verb-communication-naming", label: "Naming & Calling", family: "Communication" },
      { collection: "topic:verb-asking-requesting", label: "Asking & Requesting", family: "Communication" },
      // Thinking & knowing
      { collection: "topic:verb-thinking-opinions", label: "Thinking & Opinions", family: "Thinking & knowing" },
      { collection: "topic:verb-deciding-considering", label: "Deciding & Considering", family: "Thinking & knowing" },
      { collection: "topic:verb-knowing", label: "Knowing", family: "Thinking & knowing" },
      { collection: "topic:verb-learning-teaching", label: "Learning & Teaching", family: "Thinking & knowing" },
      { collection: "topic:verb-remembering-forgetting", label: "Remembering & Forgetting", family: "Thinking & knowing" },
      // Perception & feelings
      { collection: "topic:verb-seeing-ver", label: "Seeing", family: "Perception & feelings" },
      { collection: "topic:verb-watching-other", label: "Watching & Observing", family: "Perception & feelings" },
      { collection: "topic:verb-perception-hearing", label: "Hearing & Listening", family: "Perception & feelings" },
      { collection: "topic:verb-feelings-general", label: "Feelings & Sensations", family: "Perception & feelings" },
      { collection: "topic:verb-feelings-love-like", label: "Love & Liking", family: "Perception & feelings" },
      { collection: "topic:verb-feelings-dislike-worry", label: "Dislike, Worry & Missing", family: "Perception & feelings" },
      // Movement
      { collection: "topic:verb-movement-going", label: "Going & Coming", family: "Movement" },
      { collection: "topic:verb-movement-arriving-passing", label: "Arriving & Passing", family: "Movement" },
      { collection: "topic:verb-movement-leaving", label: "Leaving", family: "Movement" },
      { collection: "topic:verb-movement-directional", label: "Direction — Up, Down & Back", family: "Movement" },
      { collection: "topic:verb-locomotion-general", label: "Walking & Running", family: "Movement" },
      { collection: "topic:verb-following-continuing", label: "Following & Continuing", family: "Movement" },
      // Possession & transfer
      { collection: "topic:verb-possession-having", label: "Having (tener)", family: "Possession & transfer" },
      { collection: "topic:verb-possession-obtaining", label: "Getting & Obtaining", family: "Possession & transfer" },
      { collection: "topic:verb-tomar-general", label: "Taking (tomar)", family: "Possession & transfer" },
      { collection: "topic:verb-dar-giving", label: "Giving (dar)", family: "Possession & transfer" },
      { collection: "topic:verb-dar-idioms", label: "Giving (dar) — Idioms", family: "Possession & transfer" },
      { collection: "topic:verb-giving-lending-other", label: "Giving & Lending — Other Verbs", family: "Possession & transfer" },
      { collection: "topic:verb-offering", label: "Offering & Providing", family: "Possession & transfer" },
      { collection: "topic:verb-taking-removing", label: "Taking Away", family: "Possession & transfer" },
      { collection: "topic:verb-keeping-storing", label: "Keeping & Storing", family: "Possession & transfer" },
      { collection: "topic:verb-carrying", label: "Carrying", family: "Possession & transfer" },
      { collection: "topic:verb-bringing", label: "Bringing", family: "Possession & transfer" },
      // Daily life & money
      { collection: "topic:verb-eating-drinking", label: "Eating & Drinking", family: "Daily life & money" },
      { collection: "topic:verb-daily-routine", label: "Daily Routine & Self-care", family: "Daily life & money" },
      { collection: "topic:verb-work-employment", label: "Work & Employment", family: "Daily life & money" },
      { collection: "topic:verb-money-earning-spending", label: "Money — Earning & Spending", family: "Daily life & money" },
      { collection: "topic:verb-money-commerce", label: "Money — Buying & Selling", family: "Daily life & money" },
      // Making, changing & home
      { collection: "topic:verb-creation-hacer", label: "Making & Doing (hacer)", family: "Making, changing & home" },
      { collection: "topic:verb-creation-repair-other", label: "Creating, Fixing & Changing", family: "Making, changing & home" },
      { collection: "topic:verb-poner-idioms", label: "Placing & Setting (poner)", family: "Making, changing & home" },
      { collection: "topic:verb-household", label: "Household & Objects", family: "Making, changing & home" },
      { collection: "topic:verb-health-body", label: "Body & Health", family: "Making, changing & home" },
      // Social life
      { collection: "topic:verb-social-relationships", label: "Relationships", family: "Social life" },
      { collection: "topic:verb-conflict-crime", label: "Conflict & Crime", family: "Social life" },
      { collection: "topic:verb-loss-death", label: "Loss & Death", family: "Social life" },
      { collection: "topic:verb-admin-legal-formal", label: "Administrative, Legal & Formal", family: "Social life" },
      // Wanting, needing & hoping
      { collection: "topic:verb-wishes", label: "Wishes & Hypotheticals", family: "Wanting, needing & hoping" },
      { collection: "topic:verb-hoping-waiting", label: "Hoping & Waiting", family: "Wanting, needing & hoping" },
      { collection: "topic:verb-depending-fitting", label: "Needing, Depending & Fitting", family: "Wanting, needing & hoping" },
      { collection: "topic:verb-weather-time-duration", label: "Weather, Time & Duration", family: "Wanting, needing & hoping" },
    ],
  },
  {
    slug: "special-verbs",
    title: "Special Verbs",
    description:
      "The grammatical verb machinery, kept separate from the thematic Verbs page because its English translations swing wildly by context: the two verbs for “to be” (ser and estar), “there is / there are” (hay), “to have” as the perfect auxiliary, and the modals (can, could, may, must, should, have to).",
    baseCollection: "topic:verb-system",
    facetButtons: [
      { collection: "topic:verb-ser-idioms", label: "To Be (ser) — Idioms & Uses", family: "To be & there is" },
      { collection: "topic:verb-estar-idioms", label: "To Be (estar) — Idioms & Uses", family: "To be & there is" },
      { collection: "topic:verb-tobe-present", label: "To Be — Conjugated Forms (am/is/are, was/were)", family: "To be & there is" },
      { collection: "topic:verb-tobe-existence-hay", label: "There Is / Are (hay)", family: "To be & there is" },
      { collection: "topic:verb-perfect-auxiliary", label: "Have — Perfect Auxiliary (have/has/had done)", family: "Modals & auxiliaries" },
      { collection: "topic:verb-modal-ability", label: "Can & Could — Ability & Permission", family: "Modals & auxiliaries" },
      { collection: "topic:verb-modal-possibility", label: "May & Might — Possibility", family: "Modals & auxiliaries" },
      { collection: "topic:verb-modal-obligation", label: "Must, Should & Have To — Obligation", family: "Modals & auxiliaries" },
    ],
  },
  {
    slug: "cognates",
    title: "Cognates",
    description:
      "Words that share a Spanish/English root, grouped by the transformation trick that gets you from one to the other — spelling suffixes (-ción → -tion), Latin roots that don't share a spelling (tener → contain), and false friends that look related but aren't.",
    baseCollection: "topic:cognate",
    facetButtons: [
      {
        collection: "cognate:izar-to-ize",
        label: "-izar → -ize",
        family: "-ar verb cognates (preparAR → prepare)",
      },
      {
        collection: "cognate:ar-to-ate",
        label: "-ar → -ate",
        family: "-ar verb cognates (preparAR → prepare)",
      },
      {
        collection: "cognate:ificar-to-ify",
        label: "-ificar → -ify",
        family: "-ar verb cognates (preparAR → prepare)",
      },
      {
        collection: "cognate:inar-to-ine",
        label: "-inar → -ine",
        family: "-ar verb cognates (preparAR → prepare)",
      },
      {
        collection: "cognate:servar-to-serve",
        label: "servar → -serve",
        family: "-ar verb cognates (preparAR → prepare)",
      },
      {
        collection: "cognate:plicar-to-ply",
        label: "plicar → -ply",
        family: "-ar verb cognates (preparAR → prepare)",
      },
      {
        collection: "cognate:tener-to-tain",
        label: "tener → -tain",
        family: "-er verb cognates (defendER → defend)",
      },
      {
        collection: "cognate:poner-to-pose",
        label: "poner → -pose",
        family: "-er verb cognates (defendER → defend)",
      },
      {
        collection: "cognate:traer-to-tract",
        label: "traer → -tract",
        family: "-er verb cognates (defendER → defend)",
      },
      {
        collection: "cognate:ceder-to-cede",
        label: "ceder → -cede",
        family: "-er verb cognates (defendER → defend)",
      },
      {
        collection: "cognate:solver-to-solve",
        label: "solver → -solve",
        family: "-er verb cognates (defendER → defend)",
      },
      {
        collection: "cognate:hender-to-hend",
        label: "hender/prender → -hend",
        family: "-er verb cognates (defendER → defend)",
      },
      {
        collection: "cognate:ir-to-silent-e",
        label: "-ir → silent -e",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:mitir-to-mit",
        label: "mitir/meter → -mit",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:ferir-to-fer",
        label: "ferir/frir → -fer",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:ducir-to-duce",
        label: "ducir → -duce",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:tribuir-to-tribute",
        label: "tribuir → -tribute",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:struir-to-struct",
        label: "struir → -struct",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:escribir-to-scribe",
        label: "escribir → -scribe",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:cluir-to-clude",
        label: "cluir → -clude",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:decir-to-dict",
        label: "decir → -dict",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:primir-to-press",
        label: "primir/presar → -press",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:vertir-to-vert",
        label: "vertir → -vert",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:gerir-to-gest",
        label: "gerir → -gest",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:hibir-to-hibit",
        label: "hibir → -hibit",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:cibir-to-ceive",
        label: "cibir → -ceive",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:currir-to-cur",
        label: "currir → -cur",
        family: "-ir verb cognates (decidIR → decide)",
      },
      {
        collection: "cognate:anza-to-ance",
        label: "-anza → -ance",
        family: "Noun cognates",
      },
      {
        collection: "cognate:arte-to-art",
        label: "-arte → -art",
        family: "Noun cognates",
      },
      {
        collection: "cognate:cion-to-tion",
        label: "-ción → -tion",
        family: "Noun cognates",
      },
      {
        collection: "cognate:dad-to-ty",
        label: "-dad → -ty",
        family: "Noun cognates",
      },
      {
        collection: "cognate:ecto-to-ect",
        label: "-ecto → -ect",
        family: "Noun cognates",
      },
      {
        collection: "cognate:el-to-el",
        label: "-el → -el",
        family: "Noun cognates",
      },
      {
        collection: "cognate:es-to-s",
        label: "-es → -s",
        family: "Noun cognates",
      },
      {
        collection: "cognate:icto-to-ict",
        label: "-icto → -ict",
        family: "Noun cognates",
      },
      {
        collection: "cognate:ma-to-m",
        label: "-ma → -m",
        family: "Noun cognates",
      },
      {
        collection: "cognate:sion-to-sion",
        label: "-sión → -sion",
        family: "Noun cognates",
      },
      {
        collection: "cognate:sis-to-sis",
        label: "-sis → -sis",
        family: "Noun cognates",
      },
      {
        collection: "cognate:tud-to-tude",
        label: "-tud → -tude",
        family: "Noun cognates",
      },
      {
        collection: "cognate:uro-ura-to-ure",
        label: "-uro/-ura → -ure",
        family: "Noun cognates",
      },
      {
        collection: "topic:cognate-encia-ancia",
        label: "-encia/-ancia → -ence/-ance",
        family: "Noun cognates",
      },
      {
        collection: "cognate:ia-to-y",
        label: "-ia → -y",
        family: "Noun cognates",
      },
      {
        collection: "cognate:mento-miento-to-ment",
        label: "-mento/-miento → -ment",
        family: "Noun cognates",
      },
      {
        collection: "cognate:ista-to-ist",
        label: "-ista → -ist",
        family: "Noun cognates",
      },
      {
        collection: "cognate:ismo-to-ism",
        label: "-ismo → -ism",
        family: "Noun cognates",
      },
      {
        collection: "cognate:ema-to-em",
        label: "-ema → -em",
        family: "Noun cognates",
      },
      {
        collection: "cognate:able-to-able",
        label: "-able → -able",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:acto-to-act",
        label: "-acto → -act",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:al-to-al",
        label: "-al → -al",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:ante-to-ant",
        label: "-ante → -ant",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:ar-to-ar",
        label: "-ar → -ar",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:ario-to-ary",
        label: "-ario → -ary",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:ente-to-ent",
        label: "-ente → -ent",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:ible-to-ible",
        label: "-ible → -ible",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:ico-to-ic",
        label: "-ico → -ic",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:ido-to-id",
        label: "-ido → -id",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:il-to-ile",
        label: "-il → -ile",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:ivo-to-ive",
        label: "-ivo → -ive",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:orio-to-ory",
        label: "-orio → -ory",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:oso-to-ous",
        label: "-oso → -ous",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:ano-iano-to-an-ian",
        label: "-ano/-iano → -an/-ian",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:ico-to-ical",
        label: "-ico → -ical",
        family: "Adjective cognates",
      },
      {
        collection: "cognate:mente-to-ly",
        label: "-mente → -ly",
        family: "Adverb cognates",
      },
      {
        collection: "cognate:ando-to-ing",
        label: "-ando → -ing",
        family: "Verb form endings",
      },
      {
        collection: "cognate:dido-to-ded",
        label: "-dido → -ded",
        family: "Verb form endings",
      },
      {
        collection: "cognate:iendo-to-ing",
        label: "-iendo → -ing",
        family: "Verb form endings",
      },
      {
        collection: "cognate:ado-ido-to-ed",
        label: "-ado/-ido → -ed",
        family: "Verb form endings",
      },
      {
        collection: "topic:cognate-transparent",
        label: "Identical / transparent",
        family: "How close is it?",
      },
      {
        collection: "topic:cognate-opaque",
        label: "Looks different",
        family: "How close is it?",
      },
      {
        collection: "cognate:false-friend",
        label: "False friends",
        family: "How close is it?",
      },
      {
        collection: "topic:cognate-latin-root",
        label: "Latin roots (any)",
        family: "Latin roots — not yet sorted by stem",
      },
      // Spelling-suffix families.
      // Latin-root families (spelling doesn't match; grouped by verb stem).
    ],
  },
  {
    slug: "nouns",
    title: "Nouns",
    description:
      "Every noun, with its article bracketed to show gender — [la] mesa, [el] hombre, [el/la] estudiante — plus a subject-matter theme so you can browse by topic instead of alphabetically.",
    baseCollection: "pos:noun",
    facetButtons: [
      {
        collection: "topic:masc-o",
        label: "el, -o",
        family: "Articles & gender",
      },
      {
        collection: "topic:masc-consonant",
        label: "el, consonant",
        family: "Articles & gender",
      },
      {
        collection: "topic:masc-e",
        label: "el, -e",
        family: "Articles & gender",
      },
      {
        collection: "topic:masc-exceptions",
        label: "el, exceptions to -o",
        family: "Articles & gender",
      },
      {
        collection: "topic:fem-a",
        label: "la, -a",
        family: "Articles & gender",
      },
      {
        collection: "topic:fem-abstract-suffix",
        label: "la, -dad/-ción/-sión",
        family: "Articles & gender",
      },
      {
        collection: "topic:fem-consonant",
        label: "la, consonant",
        family: "Articles & gender",
      },
      {
        collection: "topic:fem-exceptions",
        label: "la, exceptions to -a",
        family: "Articles & gender",
      },
      {
        collection: "topic:common-gender-professions",
        label: "el/la, -ista professions",
        family: "Articles & gender",
      },
      {
        collection: "topic:common-gender-other-roles",
        label: "el/la, other roles",
        family: "Articles & gender",
      },
      {
        collection: "gender:invariant",
        label: "No article / neuter lo",
        family: "Articles & gender",
      },
      {
        collection: "topic:family-immediate",
        label: "Family — Immediate",
        family: "People & family",
      },
      {
        collection: "topic:family-extended",
        label: "Family — Extended",
        family: "People & family",
      },
      {
        collection: "topic:family-groups-terms",
        label: "Family — Groups & Terms",
        family: "People & family",
      },
      {
        collection: "topic:people-professions",
        label: "People — Professions & Roles",
        family: "People & family",
      },
      {
        collection: "topic:people-general",
        label: "People — General & Groups",
        family: "People & family",
      },
      {
        collection: "topic:places-home-buildings",
        label: "Home & Buildings",
        family: "Places",
      },
      {
        collection: "topic:places-public-city",
        label: "Public & City",
        family: "Places",
      },
      {
        collection: "topic:noun-time-months",
        label: "Months",
        family: "Time & calendar",
      },
      {
        collection: "topic:noun-time-days-periods",
        label: "Days & Periods",
        family: "Time & calendar",
      },
      {
        collection: "topic:calendar",
        label: "Calendar & Relative Time",
        family: "Time & calendar",
      },
      { collection: "topic:education", label: "Education", family: "Domains" },
      {
        collection: "topic:business-work",
        label: "Work & Employment",
        family: "Domains",
      },
      {
        collection: "topic:money-business",
        label: "Money & Finance",
        family: "Domains",
      },
      {
        collection: "topic:objects-money-business",
        label: "Business & Commerce",
        family: "Domains",
      },
      { collection: "topic:food", label: "Food", family: "Domains" },
      {
        collection: "topic:technology",
        label: "Technology",
        family: "Domains",
      },
      { collection: "topic:health", label: "Health", family: "Domains" },
      {
        collection: "topic:body-parts",
        label: "Body parts",
        family: "Domains",
      },
      { collection: "topic:clothing", label: "Clothing", family: "Domains" },
      {
        collection: "topic:government-politics",
        label: "Government & Politics",
        family: "Domains",
      },
      {
        collection: "topic:crime-law",
        label: "Crime & Law",
        family: "Domains",
      },
      {
        collection: "topic:art-culture",
        label: "Art & Culture",
        family: "Domains",
      },
      {
        collection: "topic:communication-request",
        label: "Communication & Requests",
        family: "Domains",
      },
      {
        collection: "topic:sports-recreation",
        label: "Sports & Travel",
        family: "Domains",
      },
      { collection: "topic:event", label: "Events", family: "Domains" },
      {
        collection: "topic:objects-physical",
        label: "Physical Items",
        family: "Objects & things",
      },
      {
        collection: "topic:objects-communication-media",
        label: "Communication & Media Objects",
        family: "Objects & things",
      },
      {
        collection: "topic:objects-misc-language",
        label: "Misc & Language",
        family: "Objects & things",
      },
      {
        collection: "topic:abstract-encia-ancia",
        label: "Abstract — -encia/-ancia",
        family: "Abstract nouns by suffix",
      },
      {
        collection: "topic:abstract-cion-sion",
        label: "Abstract — -ción/-sión",
        family: "Abstract nouns by suffix",
      },
      {
        collection: "topic:abstract-dad-tud",
        label: "Abstract — -dad/-tud",
        family: "Abstract nouns by suffix",
      },
      {
        collection: "topic:abstract-mento-miento",
        label: "Abstract — -mento/-miento",
        family: "Abstract nouns by suffix",
      },
      {
        collection: "topic:abstract-ismo-and-misc",
        label: "Abstract — -ismo & misc",
        family: "Abstract nouns by suffix",
      },
      {
        collection: "topic:abstract-general",
        label: "Other abstract nouns",
        family: "Other abstract nouns",
      },
    ],
  },
  {
    slug: "adjectives",
    title: "Adjectives",
    description:
      "Every adjective, with its copula bracketed to show how it's actually used — [ser] importante, [estar] listo, [tener] hambre — plus comparative/superlative forms and a quality-based theme.",
    baseCollection: "pos:adjective",
    facetButtons: [
      {
        collection: "topic:adj-oso-osa",
        label: "-oso/-osa (famoso, nervioso)",
        family: "Adjective endings",
      },
      {
        collection: "topic:adj-ico-ica",
        label: "-ico/-ica (práctico, típico)",
        family: "Adjective endings",
      },
      {
        collection: "topic:adj-ivo-iva",
        label: "-ivo/-iva (activo, creativo)",
        family: "Adjective endings",
      },
      {
        collection: "topic:adj-able",
        label: "-able (aceptable, notable)",
        family: "Adjective endings",
      },
      {
        collection: "topic:adj-ible",
        label: "-ible (posible, visible)",
        family: "Adjective endings",
      },
      {
        collection: "topic:adj-ente",
        label: "-ente (diferente, evidente)",
        family: "Adjective endings",
      },
      {
        collection: "topic:adj-al",
        label: "-al (natural, general)",
        family: "Adjective endings",
      },
      {
        collection: "topic:adj-ano-ana",
        label: "-ano/-ana (americano, cotidiano)",
        family: "Adjective endings",
      },
      { collection: "topic:color", label: "Color", family: "Semantic themes" },
      { collection: "topic:size", label: "Size", family: "Semantic themes" },
      { collection: "topic:age", label: "Age", family: "Semantic themes" },
      { collection: "topic:speed", label: "Speed", family: "Semantic themes" },
      {
        collection: "topic:weather",
        label: "Weather",
        family: "Semantic themes",
      },
      { collection: "topic:time", label: "Time", family: "Semantic themes" },
      {
        collection: "topic:value-price",
        label: "Value / price",
        family: "Semantic themes",
      },
      {
        collection: "topic:nationality",
        label: "Nationality",
        family: "Semantic themes",
      },
      {
        collection: "topic:difficulty",
        label: "Difficulty",
        family: "Semantic themes",
      },
      {
        collection: "topic:personality",
        label: "Personality",
        family: "Semantic themes",
      },
      {
        collection: "topic:emotion-physical-sensation",
        label: "Emotion — Physical Sensation",
        family: "Semantic themes",
      },
      {
        collection: "topic:emotion-feeling",
        label: "Emotion — Feeling",
        family: "Semantic themes",
      },
      {
        collection: "topic:condition-state",
        label: "Condition / state",
        family: "Semantic themes",
      },
      {
        collection: "topic:estar-adj",
        label: "estar (temporary state)",
        family: "How it's used",
      },
      {
        collection: "grammar:tener-adjective",
        label: "tener (idiom)",
        family: "How it's used",
      },
      {
        collection: "grammar:adjective-position",
        label: "Word order & sentence frame",
        family: "How it's used",
      },
      {
        collection: "degree:comparative-er",
        label: "-er (harder)",
        family: "Comparison",
      },
      {
        collection: "degree:superlative-est",
        label: "-est (hardest)",
        family: "Comparison",
      },
      {
        collection: "degree:comparative-more",
        label: "more ___",
        family: "Comparison",
      },
      {
        collection: "degree:superlative-most",
        label: "most ___",
        family: "Comparison",
      },
      {
        collection: "degree:irregular-comparative",
        label: "irregular comparative",
        family: "Comparison",
      },
      {
        collection: "degree:irregular-superlative",
        label: "irregular superlative",
        family: "Comparison",
      },
      {
        collection: "topic:adj-ser-general",
        label: "Other descriptive adjectives",
        family: "Other descriptive adjectives",
      },
    ],
  },
  {
    slug: "adverbs",
    title: "Adverbs",
    description:
      "Words that modify a verb, adjective, or whole sentence instead of naming a thing — frequency (siempre, nunca), manner (-mente words, like rápidamente), intensifiers (muy, tan), and the question-word adverbs already covered on the Interrogatives page.",
    baseCollection: "pos:adverb",
    facetButtons: [
      {
        collection: "grammar:frequency-adverb",
        label: "Frequency",
        family: "Word types",
      },
      {
        collection: "grammar:manner",
        label: "Manner (-mente)",
        family: "Word types",
      },
      {
        collection: "grammar:intensifier",
        label: "Intensifiers",
        family: "Word types",
      },
      {
        collection: "grammar:interrogative-adverb",
        label: "Interrogative",
        family: "Word types",
      },
      {
        collection: "topic:adv-time-relative-day",
        label: "Time — Relative Day",
        family: "Meaning & context",
      },
      {
        collection: "topic:adv-time-now-and-timing",
        label: "Time — Now & Timing",
        family: "Meaning & context",
      },
      {
        collection: "topic:location",
        label: "Place",
        family: "Meaning & context",
      },
      {
        collection: "topic:cognate",
        label: "Cognates",
        family: "Meaning & context",
      },
      {
        collection: "adv:possibility",
        label: "Possibility (maybe, apparently)",
        family: "Word types",
      },
      {
        collection: "adv:degree",
        label: "Degree / approximation (almost, barely, somewhat)",
        family: "Word types",
      },
      {
        collection: "adv:habitual",
        label: "Habitual (soler)",
        family: "Word types",
      },
      {
        collection: "grammar:addition",
        label: "Addition (also, either)",
        family: "Word types",
      },
    ],
  },
  {
    slug: "numbers",
    title: "Numbers",
    description:
      "Cardinals (uno, dos, tres), ordinals (primero, segundo, tercero), and the larger and more fractional numbers that come up once you're past counting on your fingers.",
    baseCollection: "pos:number",
    facetButtons: [
      {
        collection: "topic:cardinal-1-10",
        label: "Cardinal — 1-10",
        family: "Number groups",
      },
      {
        collection: "topic:cardinal-11-19",
        label: "Cardinal — 11-19",
        family: "Number groups",
      },
      {
        collection: "topic:cardinal-tens-and-up",
        label: "Cardinal — Tens & Up",
        family: "Number groups",
      },
      {
        collection: "topic:ordinal-1-10",
        label: "Ordinal — 1st-10th",
        family: "Number groups",
      },
      {
        collection: "topic:ordinal-11-19",
        label: "Ordinal — 11th-19th",
        family: "Number groups",
      },
      {
        collection: "topic:ordinal-20-and-up",
        label: "Ordinal — 20th & Up",
        family: "Number groups",
      },
      {
        collection: "topic:fractions-decimals-and-phone-numbers",
        label: "Fractions & decimals",
        family: "Number groups",
      },
      {
        collection: "topic:large-numbers",
        label: "Large numbers",
        family: "Number groups",
      },
    ],
  },
  {
    slug: "expressions",
    title: "Expressions",
    description:
      "Fixed social phrases that don't break down grammatically — please, thank you, excuse me, nice to meet you — learned whole rather than built word by word.",
    baseCollection: "topic:social-expression",
    facetButtons: [
      {
        collection: "expr:politeness",
        label: "Politeness",
        family: "Expression groups",
      },
      {
        collection: "expr:greeting",
        label: "Greetings",
        family: "Expression groups",
      },
      {
        collection: "expr:apology",
        label: "Apologies",
        family: "Expression groups",
      },
      {
        collection: "expr:response",
        label: "Response words",
        family: "Expression groups",
      },
      {
        collection: "expr:farewell",
        label: "Farewells",
        family: "Expression groups",
      },
      {
        collection: "expr:warning-command",
        label: "Warnings & commands",
        family: "Expression groups",
      },
      {
        collection: "expr:idiom",
        label: "Idioms & fixed phrases",
        family: "Expression groups",
      },
    ],
  },
  {
    slug: "connectors",
    title: "Connectors",
    description:
      "The words that join two clauses or ideas together — the everyday set (y, pero, o, porque, si) plus reason, concession, contrast, and addition connectors for building longer sentences.",
    baseCollection: "pos:connector",
    facetButtons: [
      {
        collection: "grammar:sentence-structure",
        label: "Everyday (and, but, or...)",
        family: "Everyday connectors",
      },
      {
        collection: "grammar:reason",
        label: "Reason",
        family: "Everyday connectors",
      },
      {
        collection: "grammar:concession",
        label: "Concession (although)",
        family: "Discourse & advanced",
      },
      {
        collection: "grammar:contrast",
        label: "Contrast",
        family: "Everyday connectors",
      },
      {
        collection: "grammar:addition",
        label: "Addition",
        family: "Everyday connectors",
      },
      {
        collection: "topic:time-connector",
        label: "Time",
        family: "Everyday connectors",
      },
      {
        collection: "grammar:discourse",
        label: "Discourse markers (that is, by the way)",
        family: "Discourse & advanced",
      },
      {
        collection: "grammar:sequence",
        label: "Sequence (then)",
        family: "Everyday connectors",
      },
      {
        collection: "grammar:conditional",
        label: "Conditional (as long as, unless)",
        family: "Discourse & advanced",
      },
      {
        collection: "grammar:correlative",
        label: "Correlative (either...or, neither...nor)",
        family: "Discourse & advanced",
      },
      {
        collection: "grammar:comparison",
        label: "Comparison (than)",
        family: "Discourse & advanced",
      },
    ],
  },
  {
    slug: "prepositions",
    title: "Prepositions",
    description:
      "The compound and multi-word prepositions beyond the basic set already covered on the Mappings pages (de, en, con, a, por) — mostly time and location relationships: antes de, detrás de, a lo largo de.",
    baseCollection: "pos:preposition",
    facetButtons: [
      { collection: "topic:time", label: "Time", family: "Preposition groups" },
      {
        collection: "topic:location-vertical-relative",
        label: "Location — Vertical & Relative",
        family: "Preposition groups",
      },
      {
        collection: "topic:location-path-between",
        label: "Location — Path & Between",
        family: "Preposition groups",
      },
      {
        collection: "construction:map-segun-according-to",
        label: "According to",
        family: "Preposition groups",
      },
      {
        collection: "grammar:purpose",
        label: "Purpose, without & except",
        family: "Preposition groups",
      },
    ],
  },
  {
    slug: "mappings",
    title: "Spanish-to-English Mappings",
    description:
      'Spanish words whose English translation depends entirely on the sentence around them — hacer means "do," "make," "ago," or describes the weather; dar means "give," but also "turn on," "feel like," or "face a direction." These are the words where memorizing one English gloss will mislead you. Click a Spanish chip to see the full range of what one word can mean.',
    baseCollection: "topic:multi-sense",
    facetButtons: [
      { collection: "topic:map-ser", label: "ser", family: "P–T" },
      { collection: "topic:map-estar", label: "estar", family: "A–E" },
      { collection: "topic:map-poner", label: "poner", family: "P–T" },
      { collection: "topic:map-tener", label: "tener", family: "P–T" },
      { collection: "topic:map-poder", label: "poder", family: "P–T" },
      { collection: "topic:map-hacer", label: "hacer", family: "F–J" },
      { collection: "topic:map-dar", label: "dar", family: "A–E" },
      { collection: "topic:map-haber", label: "haber", family: "F–J" },
      { collection: "topic:map-ir", label: "ir", family: "F–J" },
      { collection: "topic:map-decir", label: "decir", family: "A–E" },
      { collection: "topic:map-de", label: "de", family: "A–E" },
      { collection: "topic:map-en", label: "en", family: "A–E" },
      { collection: "topic:map-pedir", label: "pedir", family: "P–T" },
      { collection: "topic:map-dejar", label: "dejar", family: "A–E" },
      { collection: "topic:map-hablar", label: "hablar", family: "F–J" },
      { collection: "topic:map-deber", label: "deber", family: "A–E" },
      { collection: "topic:map-querer", label: "querer", family: "P–T" },
      { collection: "topic:map-que", label: "que", family: "P–T" },
      { collection: "topic:map-echar", label: "echar", family: "A–E" },
      { collection: "topic:map-seguir", label: "seguir", family: "P–T" },
      { collection: "topic:map-sentir", label: "sentir", family: "P–T" },
      { collection: "es:quedar", label: "quedar", family: "P–T" },
      { collection: "topic:map-ver", label: "ver", family: "U–Z" },
      { collection: "topic:map-pasar", label: "pasar", family: "P–T" },
      { collection: "topic:map-contar", label: "contar", family: "A–E" },
      { collection: "topic:map-tomar", label: "tomar", family: "P–T" },
      { collection: "es:caer", label: "caer", family: "A–E" },
      { collection: "es:volver", label: "volver", family: "U–Z" },
      { collection: "es:trabajar", label: "trabajar", family: "P–T" },
      { collection: "es:por", label: "por", family: "P–T" },
      { collection: "es:salir", label: "salir", family: "P–T" },
      { collection: "es:esperar", label: "esperar", family: "A–E" },
      { collection: "es:saber", label: "saber", family: "P–T" },
      { collection: "es:con", label: "con", family: "A–E" },
      { collection: "es:a", label: "a", family: "A–E" },
      { collection: "es:conocer", label: "conocer", family: "A–E" },
      { collection: "es:creer", label: "creer", family: "A–E" },
      { collection: "es:valer", label: "valer", family: "U–Z" },
      { collection: "es:cargar", label: "cargar", family: "A–E" },
      { collection: "es:si", label: "si", family: "P–T" },
      { collection: "es:parecer", label: "parecer", family: "P–T" },
      { collection: "es:subir", label: "subir", family: "P–T" },
      { collection: "es:pensar", label: "pensar", family: "P–T" },
      { collection: "es:venir", label: "venir", family: "U–Z" },
      // Common confusions — translation-choice groups that start from a Spanish
      // form. Grouped into the "Common confusions" family by navigation.ts.
      {
        collection: "topic:confusable-possessive",
        label: "su / sus / mi / tu — whose is it?",
        family: "Common confusions",
      },
      {
        collection: "topic:confusable-verb",
        label: "ser vs. estar, voy a, vivir",
        family: "Common confusions",
      },
      {
        collection: "topic:confusable-false-friend",
        label: "False friends (realizar, éxito, largo…)",
        family: "Common confusions",
      },
      {
        collection: "topic:confusable-pronoun",
        label: "él / lo / le / se / tú",
        family: "Common confusions",
      },
      {
        collection: "topic:confusable-determiner",
        label: "un vs. uno, algún vs. alguno, el",
        family: "Common confusions",
      },
    ],
  },
  {
    slug: "en-mappings",
    title: "English-to-Spanish Mappings",
    description:
      'English words whose Spanish translation depends entirely on the sentence around them — "mean" is "querer decir" when you\'re asking what someone meant, but "cruel" when describing a person, and a statistical "promedio" in "the mean time"; "him" is "lo," "le," or "con él" depending on his grammatical role in the sentence. These are the words where one memorized Spanish equivalent will mislead you. Click an English chip to see the full range of what it can become.',
    baseCollection: "topic:en-multi-sense",
    facetButtons: [
      { collection: "topic:enmap-to", label: "to", family: "P–T" },
      { collection: "topic:enmap-for", label: "for", family: "F–J" },
      { collection: "topic:enmap-with", label: "with", family: "U–Z" },
      { collection: "topic:enmap-of", label: "of", family: "K–O" },
      { collection: "topic:enmap-take", label: "take", family: "P–T" },
      { collection: "topic:enmap-put", label: "put", family: "P–T" },
      { collection: "topic:enmap-get", label: "get", family: "F–J" },
      { collection: "topic:enmap-go", label: "go", family: "F–J" },
      { collection: "topic:enmap-from", label: "from", family: "F–J" },
      { collection: "topic:enmap-you", label: "you", family: "U–Z" },
      { collection: "topic:enmap-make", label: "make", family: "K–O" },
      { collection: "topic:enmap-have", label: "have", family: "F–J" },
      { collection: "topic:enmap-set", label: "set", family: "P–T" },
      { collection: "topic:enmap-in", label: "in", family: "F–J" },
      { collection: "topic:enmap-give", label: "give", family: "F–J" },
      { collection: "topic:enmap-that", label: "that", family: "P–T" },
      { collection: "topic:enmap-keep", label: "keep", family: "K–O" },
      { collection: "topic:enmap-at", label: "at", family: "A–E" },
      { collection: "topic:enmap-how", label: "how", family: "F–J" },
      { collection: "topic:enmap-what", label: "what", family: "U–Z" },
      { collection: "en:feel", label: "feel", family: "F–J" },
      { collection: "en:tell", label: "tell", family: "P–T" },
      { collection: "topic:enmap-be", label: "be", family: "A–E" },
      { collection: "topic:enmap-come", label: "come", family: "A–E" },
      { collection: "en:ask", label: "ask", family: "A–E" },
      { collection: "en:there", label: "there", family: "P–T" },
      { collection: "en:leave", label: "leave", family: "K–O" },
      { collection: "en:it", label: "it", family: "F–J" },
      { collection: "en:could", label: "could", family: "A–E" },
      { collection: "en:look", label: "look", family: "K–O" },
      { collection: "en:fall", label: "fall", family: "F–J" },
      { collection: "en:turn", label: "turn", family: "P–T" },
      { collection: "en:work", label: "work", family: "U–Z" },
      { collection: "en:pay", label: "pay", family: "P–T" },
      { collection: "en:speak", label: "speak", family: "P–T" },
      { collection: "en:say", label: "say", family: "P–T" },
      { collection: "en:bring", label: "bring", family: "A–E" },
      { collection: "en:as", label: "as", family: "A–E" },
      { collection: "en:see", label: "see", family: "P–T" },
      { collection: "en:let", label: "let", family: "K–O" },
      { collection: "en:like", label: "like", family: "K–O" },
      { collection: "en:think", label: "think", family: "P–T" },
      { collection: "en:on", label: "on", family: "K–O" },
      { collection: "en:open", label: "open", family: "K–O" },
      { collection: "en:want", label: "want", family: "U–Z" },
      { collection: "en:is", label: "is", family: "F–J" },
      { collection: "en:talk", label: "talk", family: "P–T" },
      { collection: "en:them", label: "them", family: "P–T" },
      { collection: "en:catch", label: "catch", family: "A–E" },
      { collection: "en:stop", label: "stop", family: "P–T" },
      { collection: "en:know", label: "know", family: "K–O" },
      { collection: "en:agree", label: "agree", family: "A–E" },
      { collection: "en:if", label: "if", family: "F–J" },
      { collection: "en:start", label: "start", family: "P–T" },
      { collection: "en:use", label: "use", family: "U–Z" },
      { collection: "en:eat", label: "eat", family: "A–E" },
      { collection: "en:drink", label: "drink", family: "A–E" },
      { collection: "en:somebody", label: "somebody", family: "P–T" },
      { collection: "en:one", label: "one", family: "K–O" },
      { collection: "en:old", label: "old", family: "K–O" },
      { collection: "en:bad", label: "bad", family: "A–E" },
      { collection: "en:run", label: "run", family: "P–T" },
      { collection: "en:her", label: "her", family: "F–J" },
      { collection: "en:so", label: "so", family: "P–T" },
      { collection: "en:must", label: "must", family: "K–O" },
      { collection: "en:may", label: "may", family: "K–O" },
      { collection: "en:been", label: "been", family: "A–E" },
      { collection: "en:send", label: "send", family: "P–T" },
      { collection: "en:good", label: "good", family: "F–J" },
      { collection: "en:care", label: "care", family: "A–E" },
      { collection: "en:are", label: "are", family: "A–E" },
      { collection: "en:after", label: "after", family: "A–E" },
      { collection: "en:cost", label: "cost", family: "A–E" },
      { collection: "en:power", label: "power", family: "P–T" },
      { collection: "en:believe", label: "believe", family: "A–E" },
      { collection: "en:next", label: "next", family: "K–O" },
      { collection: "en:would", label: "would", family: "U–Z" },
      { collection: "en:count", label: "count", family: "A–E" },
      { collection: "en:stand", label: "stand", family: "P–T" },
      { collection: "en:even", label: "even", family: "A–E" },
      { collection: "en:this", label: "this", family: "P–T" },
      { collection: "en:white", label: "white", family: "U–Z" },
      { collection: "en:lose", label: "lose", family: "K–O" },
      { collection: "en:who", label: "who", family: "U–Z" },
      { collection: "en:then", label: "then", family: "P–T" },
      { collection: "en:lend", label: "lend", family: "K–O" },
      { collection: "en:finish", label: "finish", family: "F–J" },
      { collection: "en:him", label: "him", family: "F–J" },
      { collection: "en:request", label: "request", family: "P–T" },
      { collection: "en:hard", label: "hard", family: "F–J" },
      { collection: "en:free", label: "free", family: "F–J" },
      { collection: "en:show", label: "show", family: "P–T" },
      { collection: "en:hear", label: "hear", family: "F–J" },
      { collection: "en:own", label: "own", family: "K–O" },
      { collection: "en:break", label: "break", family: "A–E" },
      { collection: "en:able", label: "able", family: "A–E" },
      { collection: "en:slow", label: "slow", family: "P–T" },
      { collection: "en:become", label: "become", family: "A–E" },
      { collection: "en:wear", label: "wear", family: "U–Z" },
      { collection: "en:mean", label: "mean", family: "K–O" },
      { collection: "en:hold", label: "hold", family: "F–J" },
      { collection: "en:return", label: "return", family: "P–T" },
      { collection: "en:all", label: "all", family: "A–E" },
      { collection: "en:many", label: "many", family: "K–O" },
      { collection: "en:made", label: "made", family: "K–O" },
      { collection: "en:some", label: "some", family: "P–T" },
      { collection: "en:the", label: "the", family: "P–T" },
      // Common confusions — translation-choice groups that start from an English
      // word that fans out to several Spanish forms.
      {
        collection: "topic:confusable-pronoun",
        label: "you (tú/usted/ustedes/te), him (lo/le)",
        family: "Common confusions",
      },
      {
        collection: "topic:confusable-determiner",
        label: "un vs. uno, algún vs. alguno, el",
        family: "Common confusions",
      },
    ],
  },
  {
    slug: "phrasal-verbs-by-root",
    title: "Phrasal Verbs by Root",
    description:
      'One English verb, many particles — click "look" to see look at, look for, look into, look up, look after, look forward to, all in one place. Covers both true phrasal verbs (the particle shifts the meaning: give up) and prepositional verbs (a fixed preposition connects to the object: wait for).',
    baseCollection: "topic:phrasal-verb",
    facetButtons: [
      { collection: "topic:phr-be", label: "be", family: "A–E" },
      { collection: "topic:phr-put", label: "put", family: "P–T" },
      { collection: "topic:phr-take", label: "take", family: "P–T" },
      { collection: "topic:phr-get", label: "get", family: "F–J" },
      { collection: "en:set", label: "set", family: "P–T" },
      { collection: "en:go", label: "go", family: "F–J" },
      { collection: "en:give", label: "give", family: "F–J" },
      { collection: "en:come", label: "come", family: "A–E" },
      { collection: "en:turn", label: "turn", family: "P–T" },
      { collection: "en:keep", label: "keep", family: "K–O" },
      { collection: "en:work", label: "work", family: "U–Z" },
      { collection: "en:talk", label: "talk", family: "P–T" },
      { collection: "en:look", label: "look", family: "K–O" },
      { collection: "en:ask", label: "ask", family: "A–E" },
      { collection: "en:pay", label: "pay", family: "P–T" },
      { collection: "en:speak", label: "speak", family: "P–T" },
      { collection: "en:fall", label: "fall", family: "F–J" },
      { collection: "en:bring", label: "bring", family: "A–E" },
      { collection: "en:leave", label: "leave", family: "K–O" },
      { collection: "en:think", label: "think", family: "P–T" },
      { collection: "en:tell", label: "tell", family: "P–T" },
      { collection: "en:agree", label: "agree", family: "A–E" },
      { collection: "en:eat", label: "eat", family: "A–E" },
      { collection: "en:order", label: "order", family: "K–O" },
      { collection: "en:drink", label: "drink", family: "A–E" },
      { collection: "en:open", label: "open", family: "K–O" },
      { collection: "en:have", label: "have", family: "F–J" },
      { collection: "en:count", label: "count", family: "A–E" },
      { collection: "en:pick", label: "pick", family: "P–T" },
      { collection: "en:send", label: "send", family: "P–T" },
      { collection: "en:feel", label: "feel", family: "F–J" },
      { collection: "en:run", label: "run", family: "P–T" },
      { collection: "en:say", label: "say", family: "P–T" },
      { collection: "en:stand", label: "stand", family: "P–T" },
      { collection: "en:care", label: "care", family: "A–E" },
      { collection: "en:arrive", label: "arrive", family: "A–E" },
      { collection: "en:lose", label: "lose", family: "K–O" },
      { collection: "en:hear", label: "hear", family: "F–J" },
      { collection: "en:throw", label: "throw", family: "P–T" },
      { collection: "en:follow", label: "follow", family: "F–J" },
      { collection: "en:make", label: "make", family: "K–O" },
      { collection: "en:made", label: "made", family: "K–O" },
      { collection: "en:apply", label: "apply", family: "A–E" },
      { collection: "en:end", label: "end", family: "A–E" },
      { collection: "en:listen", label: "listen", family: "K–O" },
      { collection: "en:stay", label: "stay", family: "P–T" },
      { collection: "en:hand", label: "hand", family: "F–J" },
      { collection: "en:lend", label: "lend", family: "K–O" },
      { collection: "en:hold", label: "hold", family: "F–J" },
      { collection: "en:know", label: "know", family: "K–O" },
      { collection: "en:return", label: "return", family: "P–T" },
      { collection: "en:see", label: "see", family: "P–T" },
      { collection: "en:help", label: "help", family: "F–J" },
      { collection: "en:remove", label: "remove", family: "P–T" },
      { collection: "en:believe", label: "believe", family: "A–E" },
      { collection: "en:let", label: "let", family: "K–O" },
      { collection: "en:pour", label: "pour", family: "P–T" },
      { collection: "en:remind", label: "remind", family: "P–T" },
      { collection: "en:taste", label: "taste", family: "P–T" },
      { collection: "en:carry", label: "carry", family: "A–E" },
      { collection: "en:mean", label: "mean", family: "K–O" },
      { collection: "en:live", label: "live", family: "K–O" },
      { collection: "en:sit", label: "sit", family: "P–T" },
      { collection: "en:wake", label: "wake", family: "U–Z" },
      { collection: "en:lead", label: "lead", family: "K–O" },
      { collection: "en:request", label: "request", family: "P–T" },
      { collection: "en:book", label: "book", family: "A–E" },
      { collection: "en:apologize", label: "apologize", family: "A–E" },
      { collection: "en:borrow", label: "borrow", family: "A–E" },
      { collection: "en:demand", label: "demand", family: "A–E" },
      { collection: "en:catch", label: "catch", family: "A–E" },
      { collection: "en:wait", label: "wait", family: "U–Z" },
      { collection: "en:hope", label: "hope", family: "F–J" },
      { collection: "en:draw", label: "draw", family: "A–E" },
      { collection: "en:call", label: "call", family: "A–E" },
      { collection: "en:stop", label: "stop", family: "P–T" },
      { collection: "en:pull", label: "pull", family: "P–T" },
      { collection: "en:spend", label: "spend", family: "P–T" },
      { collection: "en:seem", label: "seem", family: "P–T" },
      { collection: "en:pass", label: "pass", family: "P–T" },
      { collection: "en:weigh", label: "weigh", family: "U–Z" },
      { collection: "en:move", label: "move", family: "K–O" },
      { collection: "en:volunteer", label: "volunteer", family: "U–Z" },
      { collection: "en:use", label: "use", family: "U–Z" },
      { collection: "en:do", label: "do", family: "A–E" },
      { collection: "en:include", label: "include", family: "F–J" },
      { collection: "en:owe", label: "owe", family: "K–O" },
      { collection: "en:rely", label: "rely", family: "P–T" },
      { collection: "en:burst", label: "burst", family: "A–E" },
      { collection: "en:back", label: "back", family: "A–E" },
      { collection: "en:add", label: "add", family: "A–E" },
      { collection: "en:kick", label: "kick", family: "K–O" },
      { collection: "en:figure", label: "figure", family: "F–J" },
      { collection: "en:steal", label: "steal", family: "P–T" },
      { collection: "en:blame", label: "blame", family: "A–E" },
      { collection: "en:knock", label: "knock", family: "K–O" },
      { collection: "en:belong", label: "belong", family: "A–E" },
      { collection: "en:touch", label: "touch", family: "P–T" },
      { collection: "en:show", label: "show", family: "P–T" },
      { collection: "en:depend", label: "depend", family: "A–E" },
      { collection: "en:appear", label: "appear", family: "A–E" },
      { collection: "en:buy", label: "buy", family: "A–E" },
      { collection: "en:own", label: "own", family: "K–O" },
      { collection: "en:provide", label: "provide", family: "P–T" },
      { collection: "en:reach", label: "reach", family: "P–T" },
      { collection: "en:benefit", label: "benefit", family: "A–E" },
      { collection: "en:shut", label: "shut", family: "P–T" },
      { collection: "en:fade", label: "fade", family: "F–J" },
      { collection: "en:find", label: "find", family: "F–J" },
      { collection: "en:found", label: "found", family: "F–J" },
      { collection: "en:warn", label: "warn", family: "U–Z" },
      { collection: "en:fit", label: "fit", family: "F–J" },
      { collection: "en:exchange", label: "exchange", family: "A–E" },
      { collection: "en:block", label: "block", family: "A–E" },
      { collection: "en:log", label: "log", family: "K–O" },
      { collection: "en:sort", label: "sort", family: "P–T" },
      { collection: "en:tidy", label: "tidy", family: "P–T" },
      { collection: "en:wear", label: "wear", family: "U–Z" },
      { collection: "en:start", label: "start", family: "P–T" },
      { collection: "en:insert", label: "insert", family: "F–J" },
      { collection: "en:involve", label: "involve", family: "F–J" },
      { collection: "en:interfere", label: "interfere", family: "F–J" },
      { collection: "en:forget", label: "forget", family: "F–J" },
      { collection: "en:play", label: "play", family: "P–T" },
      { collection: "en:tear", label: "tear", family: "P–T" },
      { collection: "en:break", label: "break", family: "A–E" },
      { collection: "en:stick", label: "stick", family: "P–T" },
      { collection: "en:sell", label: "sell", family: "P–T" },
      { collection: "en:reconcile", label: "reconcile", family: "P–T" },
      { collection: "en:write", label: "write", family: "U–Z" },
      { collection: "en:sign", label: "sign", family: "P–T" },
      { collection: "en:join", label: "join", family: "F–J" },
      { collection: "en:address", label: "address", family: "A–E" },
      { collection: "en:aim", label: "aim", family: "A–E" },
      { collection: "en:head", label: "head", family: "F–J" },
      { collection: "en:lay", label: "lay", family: "K–O" },
      { collection: "en:refer", label: "refer", family: "P–T" },
      { collection: "en:consist", label: "consist", family: "A–E" },
      { collection: "en:desist", label: "desist", family: "A–E" },
      { collection: "en:allude", label: "allude", family: "A–E" },
      { collection: "en:deprive", label: "deprive", family: "A–E" },
      { collection: "en:aspire", label: "aspire", family: "A–E" },
      { collection: "en:search", label: "search", family: "P–T" },
      { collection: "en:point", label: "point", family: "P–T" },
      { collection: "en:allow", label: "allow", family: "A–E" },
      { collection: "en:build", label: "build", family: "A–E" },
    ],
  },
  {
    slug: "phrasal-verbs-by-particle",
    title: "Phrasal Verbs by Particle",
    description:
      'One particle, many verbs — click "at" to see look at, yell at, aim at, laugh at, arrive at. The particle is the hard part to guess as a Spanish speaker, since Spanish doesn\'t build meaning this way; seeing it hold constant across unrelated verbs is what makes it stick.',
    baseCollection: "topic:phrasal-verb",
    facetButtons: [
      { collection: "topic:part-up", label: "up", family: "U–Z" },
      { collection: "topic:part-out", label: "out", family: "K–O" },
      { collection: "topic:part-to", label: "to", family: "P–T" },
      { collection: "topic:part-in", label: "in", family: "F–J" },
      { collection: "topic:part-on", label: "on", family: "K–O" },
      { collection: "topic:part-for", label: "for", family: "F–J" },
      { collection: "topic:part-off", label: "off", family: "K–O" },
      { collection: "topic:part-of", label: "of", family: "K–O" },
      { collection: "topic:part-with", label: "with", family: "U–Z" },
      { collection: "topic:part-from", label: "from", family: "F–J" },
      { collection: "particle:back", label: "back", family: "A–E" },
      { collection: "particle:into", label: "into", family: "F–J" },
      { collection: "particle:away", label: "away", family: "A–E" },
      { collection: "particle:about", label: "about", family: "A–E" },
      { collection: "particle:down", label: "down", family: "A–E" },
      { collection: "particle:at", label: "at", family: "A–E" },
      { collection: "particle:through", label: "through", family: "P–T" },
      { collection: "particle:over", label: "over", family: "K–O" },
      { collection: "particle:by", label: "by", family: "A–E" },
      { collection: "particle:like", label: "like", family: "K–O" },
      { collection: "particle:around", label: "around", family: "A–E" },
      { collection: "particle:along", label: "along", family: "A–E" },
      { collection: "particle:apart", label: "apart", family: "A–E" },
      { collection: "particle:after", label: "after", family: "A–E" },
      { collection: "particle:as", label: "as", family: "A–E" },
      { collection: "particle:forward", label: "forward", family: "F–J" },
      { collection: "particle:together", label: "together", family: "P–T" },
      { collection: "particle:onto", label: "onto", family: "K–O" },
      { collection: "particle:across", label: "across", family: "A–E" },
      { collection: "particle:aside", label: "aside", family: "A–E" },
      { collection: "particle:against", label: "against", family: "A–E" },
      { collection: "particle:behind", label: "behind", family: "A–E" },
      { collection: "particle:among", label: "among", family: "A–E" },
      { collection: "particle:under", label: "under", family: "U–Z" },
      { collection: "particle:past", label: "past", family: "P–T" },
      { collection: "particle:ahead", label: "ahead", family: "A–E" },
      { collection: "particle:below", label: "below", family: "A–E" },
      { collection: "particle:toward", label: "toward", family: "P–T" },
      { collection: "particle:before", label: "before", family: "A–E" },
    ],
  },
  {
    slug: "transformations",
    title: "Transformations",
    description:
      "One word, rebuilt into another part of speech by a suffix or prefix — power → powerful, power → powerless → powerlessness. Each pill is one transformation pattern; click it to see every word pair the catalog has for that pattern. Spanish/English cognate spelling patterns (-ción → -tion and the like) live on the Cognates page instead — this page is about English word-building alone.",
    baseCollection: "topic:transformation",
    facetButtons: [
      {
        collection: "morphology:suffix-ful",
        label: "-ful (power → powerful)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-less",
        label: "-less (thought → thoughtless)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-ness",
        label: "-ness (aware → awareness)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-hood",
        label: "-hood (neighbor → neighborhood)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-ship",
        label: "-ship (partner → partnership)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-dom",
        label: "-dom (bored → boredom)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-th",
        label: "-th (long → length)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-ment",
        label: "-ment (agree → agreement)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-al",
        label: "-al (arrive → arrival)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-tion",
        label: "-tion (educate → education)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-sion",
        label: "-sion (decide → decision)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-ity",
        label: "-ity (possible → possibility)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-ing",
        label: "-ing (weaken → the weakening)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-er",
        label: "-er (whiten → the whitener)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-er-or",
        label: "-er/-or (survive → the survivor)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-able",
        label: "-able (accept → acceptable)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-ible",
        label: "-ible (convert → convertible)",
        family: "Endings",
      },
      {
        collection: "topic:morph-ish",
        label: "-ish (tall → tallish)",
        family: "Word types",
      },
      {
        collection: "morphology:suffix-y",
        label: "-y (cloud → cloudy)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-en",
        label: "-en (weak → to weaken)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-ern",
        label: "-ern (north → northern)",
        family: "Endings",
      },
      {
        collection: "topic:morph-ward",
        label: "-ward (in → inward)",
        family: "Word types",
      },
      {
        collection: "morphology:suffix-ly",
        label: "-ly (careful → carefully)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-ed",
        label: "-ed (weaken → weakened)",
        family: "Endings",
      },
      {
        collection: "morphology:suffix-most",
        label: "-most (lower → lowermost)",
        family: "Endings",
      },
      {
        collection: "morphology:prefix-common",
        label: "Common prefixes (un-, dis-, mis-, re-, over-, under-, fore-)",
        family: "Word types",
      },
      {
        collection: "topic:morph-noun-to-adj",
        label: "noun → adjective",
        family: "Word types",
      },
      {
        collection: "topic:morph-adj-to-noun",
        label: "adjective → noun",
        family: "Word types",
      },
      {
        collection: "topic:morph-verb-to-noun",
        label: "verb → noun",
        family: "Word types",
      },
      {
        collection: "morphology:noun-to-verb",
        label: "noun → verb",
        family: "Word types",
      },
      {
        collection: "morphology:verb-to-adjective",
        label: "verb → adjective",
        family: "Word types",
      },
      {
        collection: "morphology:adjective-to-verb",
        label: "adjective → verb",
        family: "Word types",
      },
      {
        collection: "morphology:adjective-to-adjective",
        label: "adjective → adjective",
        family: "Word types",
      },
      {
        collection: "morphology:verb-to-verb",
        label: "verb → verb (prefixed)",
        family: "Word types",
      },
      {
        collection: "topic:morph-noun-to-noun",
        label: "noun → noun",
        family: "Word types",
      },
      {
        collection: "morphology:expression-to-adjective",
        label: "expression → adjective",
        family: "Word types",
      },
      {
        collection: "morphology:number-to-expression",
        label: "number → expression",
        family: "Word types",
      },
    ],
  },
  {
    slug: "verb-forms",
    title: "Past-Tense & Past-Participle Formation",
    description:
      "How English builds its past forms, grouped by sound — regular verbs split by their -ed pronunciation (played /d/, watched /t/, wanted /ɪd/), irregular verbs grouped by rhyming pattern (tell → told, sell → sold; sing → sang → sung; drink → drank → drunk). Click a pill to drill one pattern instead of memorizing verbs one at a time.",
    baseCollection: "topic:verb-form",
    facetButtons: [
      {
        collection: "topic:vf-past-d",
        label: "regular /d/ (played)",
        family: "Regular endings",
      },
      {
        collection: "sound:regular-past-pronounced-t",
        label: "regular /t/ (watched)",
        family: "Regular endings",
      },
      {
        collection: "sound:regular-past-pronounced-id",
        label: "regular /ɪd/ (wanted)",
        family: "Regular endings",
      },
      {
        collection: "topic:vf-cut-hit-hurt",
        label: "unchanged (cut)",
        family: "Irregular patterns",
      },
      {
        collection: "sound:sent-bent-lent-spent",
        label: "send → sent",
        family: "Irregular patterns",
      },
      {
        collection: "sound:kept-slept-swept",
        label: "keep → kept",
        family: "Irregular patterns",
      },
      {
        collection: "sound:felt-dealt-knelt",
        label: "feel → felt",
        family: "Irregular patterns",
      },
      {
        collection: "sound:fed-bled-led",
        label: "feed → fed",
        family: "Irregular patterns",
      },
      {
        collection: "sound:found-bound-ground-wound",
        label: "find → found",
        family: "Irregular patterns",
      },
      {
        collection: "sound:bought-thought-taught",
        label: "buy → bought",
        family: "Irregular patterns",
      },
      {
        collection: "sound:sold-told",
        label: "sell → sold",
        family: "Irregular patterns",
      },
      {
        collection: "sound:built-gilt-spilt",
        label: "build → built",
        family: "Irregular patterns",
      },
      {
        collection: "sound:made-paid-laid",
        label: "make → made",
        family: "Irregular patterns",
      },
      {
        collection: "sound:held-beheld",
        label: "hold → held",
        family: "Irregular patterns",
      },
      {
        collection: "sound:stood-understood",
        label: "stand → stood",
        family: "Irregular patterns",
      },
      {
        collection: "sound:struck-stuck-snuck",
        label: "strike → struck",
        family: "Irregular patterns",
      },
      {
        collection: "sound:clung-flung-strung-stung-swung",
        label: "cling → clung",
        family: "Irregular patterns",
      },
      {
        collection: "sound:spun-won",
        label: "spin → spun",
        family: "Irregular patterns",
      },
      {
        collection: "sound:lit-bit",
        label: "light → lit",
        family: "Irregular patterns",
      },
      {
        collection: "sound:sat-spat",
        label: "sit → sat",
        family: "Irregular patterns",
      },
      {
        collection: "sound:got-forgot-shot",
        label: "get → got",
        family: "Irregular patterns",
      },
      {
        collection: "sound:began-rang-sang",
        label: "begin → began",
        family: "Irregular patterns",
      },
      {
        collection: "sound:begun-rung-sung",
        label: "begin → begun",
        family: "Irregular patterns",
      },
      {
        collection: "sound:drank-sank-shrank",
        label: "drink → drank",
        family: "Irregular patterns",
      },
      {
        collection: "sound:drunk-sunk-shrunk",
        label: "drink → drunk",
        family: "Irregular patterns",
      },
      {
        collection: "sound:did-hid-slid",
        label: "do → did",
        family: "Irregular patterns",
      },
      {
        collection: "sound:blew-grew-knew-threw-drew-flew",
        label: "blow → blew",
        family: "Irregular patterns",
      },
      {
        collection: "sound:known-grown-thrown",
        label: "know → known",
        family: "Irregular patterns",
      },
      {
        collection: "sound:drove-rode-strode-wove-throve",
        label: "drive → drove",
        family: "Irregular patterns",
      },
      {
        collection: "sound:driven-ridden-stridden",
        label: "drive → driven",
        family: "Irregular patterns",
      },
      {
        collection: "sound:spoke-broke-woke-awoke",
        label: "speak → spoke",
        family: "Irregular patterns",
      },
      {
        collection: "sound:spoken-broken-woken",
        label: "speak → spoken",
        family: "Irregular patterns",
      },
      {
        collection: "sound:took-shook",
        label: "take → took",
        family: "Irregular patterns",
      },
      {
        collection: "sound:taken-shaken-forsaken",
        label: "take → taken",
        family: "Irregular patterns",
      },
      {
        collection: "sound:chose-froze",
        label: "choose → chose",
        family: "Irregular patterns",
      },
      {
        collection: "sound:chosen-frozen",
        label: "choose → chosen",
        family: "Irregular patterns",
      },
      {
        collection: "sound:gave-forgave",
        label: "give → gave",
        family: "Irregular patterns",
      },
      {
        collection: "sound:given-forgiven",
        label: "give → given",
        family: "Irregular patterns",
      },
      {
        collection: "sound:gotten-forgotten",
        label: "get → gotten",
        family: "Irregular patterns",
      },
      {
        collection: "sound:hidden-written",
        label: "hide → hidden",
        family: "Irregular patterns",
      },
      {
        collection: "sound:rose-arose",
        label: "rise → rose",
        family: "Irregular patterns",
      },
      {
        collection: "sound:risen-arisen",
        label: "rise → risen",
        family: "Irregular patterns",
      },
      {
        collection: "sound:came-became",
        label: "come → came",
        family: "Irregular patterns",
      },
      {
        collection: "sound:run-come-become",
        label: "come (pp = base form)",
        family: "Irregular patterns",
      },
      {
        collection: "sound:done-gone",
        label: "do → done",
        family: "Irregular patterns",
      },
      {
        collection: "sound:tore-wore-swore",
        label: "tear → tore",
        family: "Irregular patterns",
      },
      {
        collection: "sound:sworn-torn-worn-drawn-born",
        label: "swear → sworn",
        family: "Irregular patterns",
      },
      {
        collection: "sound:eaten-beaten",
        label: "eat → eaten",
        family: "Irregular patterns",
      },
      {
        collection: "sound:stolen-swollen",
        label: "steal → stolen",
        family: "Irregular patterns",
      },
      {
        collection: "sound:proven-sewn-shaven",
        label: "prove → proven",
        family: "Irregular patterns",
      },
      {
        collection: "sound:forbidden-bidden-trodden",
        label: "forbid → forbidden",
        family: "Irregular patterns",
      },
      {
        collection: "sound:striven-thriven",
        label: "strive → striven",
        family: "Irregular patterns",
      },
      {
        collection: "topic:vf-oneoff",
        label: "one-off (no rhyme partner)",
        family: "Irregular patterns",
      },
    ],
  },
  {
    slug: "verb-patterns",
    title: "Verb Patterns",
    description:
      "What comes after a verb: a bare infinitive (let him go), a full infinitive (want to go), a gerund (enjoy going), or either. English doesn't pick one by rule — each verb just takes what it takes, so this is memorized per verb, not derived from meaning.",
    baseCollection: "topic:verb-pattern",
    facetButtons: [
      {
        collection: "topic:vp-full-inf",
        label: "verb + to + infinitive (want to go)",
        family: "Sentence patterns",
      },
      {
        collection: "topic:vp-bare-inf",
        label: "verb + bare infinitive (let him go)",
        family: "Sentence patterns",
      },
      {
        collection: "topic:vp-gerund",
        label: "verb + gerund (enjoy going)",
        family: "Sentence patterns",
      },
      {
        collection: "construction:allows-full-infinitive-or-gerund",
        label: "either, same meaning (start to go / start going)",
        family: "Verb complements",
      },
      {
        collection: "construction:allows-bare-infinitive-or-present-participle",
        label: "perception verbs (saw him go / saw him going)",
        family: "Verb complements",
      },
      {
        collection: "construction:allows-full-infinitive-or-bare-infinitive",
        label: "help + either (help him go / help him to go)",
        family: "Verb complements",
      },
      {
        collection: "construction:somebody-bare-infinitive",
        label: "verb + somebody + bare infinitive (make her go)",
        family: "Verb complements",
      },
      {
        collection: "construction:somebody-doing-something",
        label: "verb + somebody + gerund (caught him going)",
        family: "Verb complements",
      },
      {
        collection: "construction:have-something-done",
        label: "have something done (causative)",
        family: "Verb complements",
      },
      {
        collection: "construction:get-something-done",
        label: "get something done (causative)",
        family: "Verb complements",
      },
      {
        collection: "construction:preposition-plus-gerund",
        label: "preposition + gerund (before going)",
        family: "Sentence patterns",
      },
      {
        collection: "construction:go-ing",
        label: "go + gerund (go shopping)",
        family: "Sentence patterns",
      },
      {
        collection: "construction:be-present-participle",
        label: "progressive (to be going)",
        family: "Tense & auxiliary patterns",
      },
      {
        collection: "construction:auxiliary-do",
        label: "auxiliary do (did they go?)",
        family: "Tense & auxiliary patterns",
      },
      {
        collection: "construction:double-object",
        label: "double object (give somebody something)",
        family: "Verb complements",
      },
      {
        collection: "topic:vp-obj-complement",
        label: "object + complement (make/expect somebody to go)",
        family: "Sentence patterns",
      },
      {
        collection: "grammar:passive",
        label: "passive (something is needed)",
        family: "Sentence patterns",
      },
      {
        collection: "grammar:going-to",
        label: "going to (future)",
        family: "Tense & auxiliary patterns",
      },
    ],
  },
  {
    slug: "questions-negation",
    title: "Questions & Negation",
    description:
      "English splits into two systems depending on the verb. Regular verbs borrow \"do\" (don't, doesn't, didn't) for both negation and questions. Modals and be/have negate and question by direct contraction or inversion instead — can't, isn't, haven't; Can you...?, Are you...?, Have you...? Negative questions and the emphatic \"I DO like it\" both ride on the same do-support system.",
    baseCollection: "topic:question-negation",
    facetButtons: [
      {
        collection: "qn:do-support-negation",
        label: "Negation — regular verbs (don't, doesn't, didn't)",
        family: "Question & negative patterns",
      },
      {
        collection: "qn:modal-be-have-negation",
        label: "Negation — modal/be/have (can't, isn't, haven't)",
        family: "Question & negative patterns",
      },
      {
        collection: "qn:do-support-question",
        label: "Questions — regular verbs (do, does, did)",
        family: "Question & negative patterns",
      },
      {
        collection: "qn:inversion-question",
        label: "Questions — modal/be/have (Can you...? Are you...?)",
        family: "Question & negative patterns",
      },
      {
        collection: "qn:negative-question",
        label: "Negative questions (Don't you...? Isn't it...?)",
        family: "Question & negative patterns",
      },
      {
        collection: "qn:emphatic",
        label: "Emphatic (I DO like it)",
        family: "Question & negative patterns",
      },
    ],
  },
  {
    slug: "imperatives",
    title: "Imperatives & Commands",
    description:
      'Spanish commands change form for formality and number (tú vs. usted vs. ustedes) and even switch conjugation entirely between affirmative and negative — English collapses all of that into one invariant "Close the door" / "Don\'t close the door." Watch the Spanish side change while the English stays put.',
    baseCollection: "topic:imperative",
    facetButtons: [
      {
        collection: "imp:affirmative-informal",
        label: "Affirmative — tú (informal)",
        family: "Command types",
      },
      {
        collection: "imp:affirmative-formal",
        label: "Affirmative — usted/ustedes (formal)",
        family: "Command types",
      },
      {
        collection: "imp:negative",
        label: "Negative (don't...)",
        family: "Command types",
      },
      {
        collection: "imp:lets",
        label: "Let's — nosotros",
        family: "Command types",
      },
    ],
  },
  {
    slug: "collocations",
    title: "Collocations",
    description:
      'Which "light" verb goes with which noun is arbitrary in English — you make a decision but take a risk, have a good time but set a goal — and Spanish carves it up completely differently (hacer, tomar, tener, poner all overlap in ways that don\'t map word-for-word). These have to be memorized as pairs, not built from the parts.',
    baseCollection: "topic:collocation",
    facetButtons: [
      {
        collection: "coll:make",
        label: "make (a decision, an effort, a call)",
        family: "Verb groups",
      },
      {
        collection: "coll:take",
        label: "take (a photo, a risk, a look)",
        family: "Verb groups",
      },
      {
        collection: "coll:have",
        label: "have (a good time, a hard time)",
        family: "Verb groups",
      },
      {
        collection: "coll:set",
        label: "set (an alarm, a goal, the table)",
        family: "Verb groups",
      },
      {
        collection: "coll:other",
        label: "give, tell, pay, hold, break, keep, catch...",
        family: "Verb groups",
      },
    ],
  },
];

export function findCurriculumTopic(slug: string): CurriculumTopic | undefined {
  return CURRICULUM_TOPICS.find((topic) => topic.slug === slug);
}
