// Curriculum macrotags. Each is a curated view of /admin/curriculum scoped to one
// base collection, with quick-filter buttons for its sub-facets, shown inline
// on the curriculum table.

export type CurriculumTopic = {
  slug: string;
  title: string;
  description: string;
  baseCollection: string;
  facetButtons: Array<{ collection: string; label: string }>;
};

export const CURRICULUM_TOPICS: CurriculumTopic[] = [
  {
    slug: "pronouns",
    title: "Pronouns",
    description:
      "Every pronoun, Spanish to English, with its grammatical role. Click a Spanish or English chip to trace one form across the whole system.",
    baseCollection: "topic:pronoun",
    facetButtons: [
      { collection: "grammar:subject-pronoun", label: "Subject" },
      { collection: "grammar:direct-object-pronoun", label: "Direct object" },
      { collection: "grammar:indirect-object-pronoun", label: "Indirect object" },
      { collection: "grammar:prep-pronoun-con", label: "Prepositional — con" },
      { collection: "grammar:prep-pronoun-para", label: "Prepositional — para" },
      { collection: "grammar:prep-pronoun-a", label: "Prepositional — a" },
      { collection: "grammar:possessive-determiner", label: "Possessive (det)" },
      { collection: "grammar:possessive-pronoun", label: "Possessive (pron)" },
      { collection: "grammar:reflexive-pronoun", label: "Reflexive" },
      { collection: "grammar:reciprocal-pronoun", label: "Reciprocal" },
      { collection: "grammar:demonstrative-determiner", label: "Demonstrative (det)" },
      { collection: "grammar:demonstrative-pronoun", label: "Demonstrative (pron)" },
      { collection: "grammar:indef-pronoun-person", label: "Indefinite — Person" },
      { collection: "grammar:indef-pronoun-thing", label: "Indefinite — Thing" },
      { collection: "grammar:indef-pronoun-place", label: "Indefinite — Place" },
      { collection: "grammar:indef-pronoun-quantity", label: "Indefinite — Quantity" },
      { collection: "grammar:interrogative-pronoun", label: "Interrogative" },
      { collection: "grammar:relative-pronoun", label: "Relative" },
      { collection: "grammar:exclamative", label: "Exclamative" },
      { collection: "grammar:subordinate-subject-pronoun", label: "él → him" },
    ],
  },
  {
    slug: "determiners",
    title: "Determiners",
    description:
      "Everything that can stand where “the” does in front of a noun — articles, demonstratives, possessives, quantifiers, and numbers. Click a Spanish or English chip to trace one form.",
    baseCollection: "topic:determiner",
    facetButtons: [
      { collection: "grammar:definite-article", label: "Definite article" },
      { collection: "grammar:indefinite-article", label: "Indefinite article" },
      { collection: "grammar:demonstrative-determiner", label: "Demonstrative" },
      { collection: "grammar:possessive-determiner", label: "Possessive" },
      { collection: "topic:quant-much-many", label: "Quantifier — Much & Many" },
      { collection: "topic:quant-little-few", label: "Quantifier — Little & Few" },
      { collection: "topic:quant-more-less", label: "Quantifier — More & Less" },
      { collection: "topic:quant-both-all-whole", label: "Quantifier — Both, All & Whole" },
      { collection: "topic:quant-some-any-no", label: "Quantifier — Some, Any & No" },
      { collection: "topic:quant-other-certain-such", label: "Quantifier — Other, Certain & Such" },
      { collection: "topic:cardinal-1-10", label: "Number — 1-10" },
      { collection: "topic:cardinal-11-19", label: "Number — 11-19" },
      { collection: "topic:cardinal-tens-and-up", label: "Number — Tens & Up" },
      { collection: "grammar:interrogative-determiner", label: "Interrogative" },
      { collection: "grammar:relative-determiner", label: "Relative (cuyo)" },
      { collection: "grammar:negative", label: "Negative (ningún)" },
    ],
  },
  {
    slug: "interrogatives",
    title: "Interrogatives",
    description:
      "The question words — qué, quién, cuál, cuándo, dónde, cómo, cuánto, por qué — as pronouns, determiners, and adverbs. Click a chip to trace one form.",
    baseCollection: "topic:interrogative",
    facetButtons: [
      { collection: "grammar:interrogative-pronoun", label: "Pronoun" },
      { collection: "grammar:interrogative-determiner", label: "Determiner" },
      { collection: "grammar:interrogative-adverb", label: "Adverb" },
    ],
  },
  {
    slug: "verbs",
    title: "Verbs",
    description:
      "Every verb, grouped by theme instead of alphabetically — communication, thinking, movement, possession, money, and more — so you can browse verbs the way you'd actually reach for them in conversation. \u201cTo be,\u201d \u201chave,\u201d and the modal verbs (poder, deber) get their own dedicated groups since their English translations swing wildly by context.",
    baseCollection: "pos:verb",
    facetButtons: [
      { collection: "topic:verb-tobe-present-1", label: "To Be — Present (am/is/are) (1)" },
      { collection: "topic:verb-tobe-present-2", label: "To Be — Present (am/is/are) (2)" },
      { collection: "topic:verb-tobe-past-future", label: "To Be — Past & Future (was/were/will be)" },
      { collection: "topic:verb-ser-idioms-1", label: "To Be (ser) — Idioms & Uses (1)" },
      { collection: "topic:verb-ser-idioms-2", label: "To Be (ser) — Idioms & Uses (2)" },
      { collection: "topic:verb-estar-idioms-1-1", label: "To Be (estar) — Idioms & Uses (1) (1)" },
      { collection: "topic:verb-estar-idioms-1-2", label: "To Be (estar) — Idioms & Uses (1) (2)" },
      { collection: "topic:verb-estar-idioms-2-1", label: "To Be (estar) — Idioms & Uses (2) (1)" },
      { collection: "topic:verb-estar-idioms-2-2", label: "To Be (estar) — Idioms & Uses (2) (2)" },
      { collection: "topic:verb-tobe-existence-hay", label: "There Is/Are (hay)" },
      { collection: "topic:verb-perfect-auxiliary-1", label: "Have — Perfect Auxiliary (have/has/had done) (1)" },
      { collection: "topic:verb-perfect-auxiliary-2", label: "Have — Perfect Auxiliary (have/has/had done) (2)" },
      { collection: "topic:verb-modal-ability-1", label: "Modals — Ability & Permission (1)" },
      { collection: "topic:verb-modal-ability-2", label: "Modals — Ability & Permission (2)" },
      { collection: "topic:verb-modal-possibility", label: "Modals — Possibility (may/might/could)" },
      { collection: "topic:verb-modal-obligation-1", label: "Modals — Obligation & Probability (must/should/have to) (1)" },
      { collection: "topic:verb-modal-obligation-2", label: "Modals — Obligation & Probability (must/should/have to) (2)" },
      { collection: "topic:verb-wishes-1", label: "Wishes & Hypotheticals (1)" },
      { collection: "topic:verb-wishes-2", label: "Wishes & Hypotheticals (2)" },
      { collection: "topic:verb-hoping-waiting", label: "Hoping & Waiting" },
      { collection: "topic:verb-communication-talking-1", label: "Communication — Talking (1)" },
      { collection: "topic:verb-communication-talking-2", label: "Communication — Talking (2)" },
      { collection: "topic:verb-communication-saying-1", label: "Communication — Saying & Telling (1)" },
      { collection: "topic:verb-communication-saying-2", label: "Communication — Saying & Telling (2)" },
      { collection: "topic:verb-communication-other-1", label: "Communication — Other (1)" },
      { collection: "topic:verb-communication-other-2", label: "Communication — Other (2)" },
      { collection: "topic:verb-communication-formal-1", label: "Communication — Formal & Reporting (1)" },
      { collection: "topic:verb-communication-formal-2", label: "Communication — Formal & Reporting (2)" },
      { collection: "topic:verb-communication-naming-1", label: "Communication — Naming, Calling & Marking (1)" },
      { collection: "topic:verb-communication-naming-2", label: "Communication — Naming, Calling & Marking (2)" },
      { collection: "topic:verb-asking-requesting-1", label: "Asking & Requesting (1)" },
      { collection: "topic:verb-asking-requesting-2", label: "Asking & Requesting (2)" },
      { collection: "topic:verb-offering", label: "Offering & Providing" },
      { collection: "topic:verb-thinking-opinions", label: "Thinking & Opinions" },
      { collection: "topic:verb-deciding-considering-1", label: "Deciding & Considering (1)" },
      { collection: "topic:verb-deciding-considering-2", label: "Deciding & Considering (2)" },
      { collection: "topic:verb-knowing-1", label: "Knowing (1)" },
      { collection: "topic:verb-knowing-2", label: "Knowing (2)" },
      { collection: "topic:verb-learning-teaching", label: "Learning & Teaching" },
      { collection: "topic:verb-remembering-forgetting", label: "Remembering & Forgetting" },
      { collection: "topic:verb-seeing-ver", label: "Seeing" },
      { collection: "topic:verb-watching-other-1", label: "Watching & Observing (1)" },
      { collection: "topic:verb-watching-other-2", label: "Watching & Observing (2)" },
      { collection: "topic:verb-perception-hearing", label: "Hearing & Listening" },
      { collection: "topic:verb-feelings-general", label: "Feelings & Sensations" },
      { collection: "topic:verb-feelings-love-like", label: "Feelings — Love & Liking" },
      { collection: "topic:verb-feelings-dislike-worry", label: "Feelings — Dislike, Worry & Missing" },
      { collection: "topic:verb-movement-going-1", label: "Movement — Going (1)" },
      { collection: "topic:verb-movement-going-2", label: "Movement — Going (2)" },
      { collection: "topic:verb-movement-coming", label: "Movement — Coming" },
      { collection: "topic:verb-movement-arriving-passing-1", label: "Movement — Arriving & Passing (1)" },
      { collection: "topic:verb-movement-arriving-passing-2", label: "Movement — Arriving & Passing (2)" },
      { collection: "topic:verb-movement-leaving-1", label: "Movement — Leaving (1)" },
      { collection: "topic:verb-movement-leaving-2", label: "Movement — Leaving (2)" },
      { collection: "topic:verb-movement-directional-verbs-1", label: "Movement — Return & Direction (1)" },
      { collection: "topic:verb-movement-directional-verbs-2", label: "Movement — Return & Direction (2)" },
      { collection: "topic:verb-movement-directional-1", label: "Movement — Up, Down & Falling (1)" },
      { collection: "topic:verb-movement-directional-2", label: "Movement — Up, Down & Falling (2)" },
      { collection: "topic:verb-locomotion-general", label: "Movement — Walking & Running" },
      { collection: "topic:verb-following-continuing-1", label: "Following & Continuing (1)" },
      { collection: "topic:verb-following-continuing-2", label: "Following & Continuing (2)" },
      { collection: "topic:verb-possession-having-1", label: "Having (tener) (1)" },
      { collection: "topic:verb-possession-having-2", label: "Having (tener) (2)" },
      { collection: "topic:verb-possession-obtaining-1", label: "Getting & Obtaining (1)" },
      { collection: "topic:verb-possession-obtaining-2", label: "Getting & Obtaining (2)" },
      { collection: "topic:verb-tomar-general-1", label: "Taking (tomar/coger) (1)" },
      { collection: "topic:verb-tomar-general-2", label: "Taking (tomar/coger) (2)" },
      { collection: "topic:verb-dar-giving", label: "Giving (dar)" },
      { collection: "topic:verb-dar-idioms", label: "Giving (dar) — Idioms" },
      { collection: "topic:verb-giving-lending-other", label: "Giving & Lending — Other Verbs" },
      { collection: "topic:verb-removing-stealing", label: "Removing & Stealing" },
      { collection: "topic:verb-taking-removing-1-1", label: "Taking Away (1) (1)" },
      { collection: "topic:verb-taking-removing-1-2", label: "Taking Away (1) (2)" },
      { collection: "topic:verb-taking-removing-2-1", label: "Taking Away (2) (1)" },
      { collection: "topic:verb-taking-removing-2-2", label: "Taking Away (2) (2)" },
      { collection: "topic:verb-keeping-storing-1", label: "Keeping & Storing (1)" },
      { collection: "topic:verb-keeping-storing-2", label: "Keeping & Storing (2)" },
      { collection: "topic:verb-quedar-remaining", label: "Remaining & Staying (quedar)" },
      { collection: "topic:verb-carrying", label: "Carrying" },
      { collection: "topic:verb-bringing", label: "Bringing" },
      { collection: "topic:verb-eating-drinking-1", label: "Eating & Drinking (1)" },
      { collection: "topic:verb-eating-drinking-2", label: "Eating & Drinking (2)" },
      { collection: "topic:verb-daily-routine", label: "Daily Routine & Self-care" },
      { collection: "topic:verb-work-employment-1", label: "Work & Employment (1)" },
      { collection: "topic:verb-work-employment-2", label: "Work & Employment (2)" },
      { collection: "topic:verb-money-earning-spending-1", label: "Money — Earning & Spending (1)" },
      { collection: "topic:verb-money-earning-spending-2", label: "Money — Earning & Spending (2)" },
      { collection: "topic:verb-money-commerce-1", label: "Money — Buying & Selling (1)" },
      { collection: "topic:verb-money-commerce-2", label: "Money — Buying & Selling (2)" },
      { collection: "topic:verb-creation-hacer-1", label: "Making & Doing (hacer) (1)" },
      { collection: "topic:verb-creation-hacer-2", label: "Making & Doing (hacer) (2)" },
      { collection: "topic:verb-creation-repair-other-1", label: "Creating, Fixing & Changing (1)" },
      { collection: "topic:verb-creation-repair-other-2", label: "Creating, Fixing & Changing (2)" },
      { collection: "topic:verb-poner-placement", label: "Placing (poner)" },
      { collection: "topic:verb-poner-turning-on", label: "Turning On/Off (poner)" },
      { collection: "topic:verb-poner-idioms-1-1", label: "Placing & Setting — Idioms (1) (1)" },
      { collection: "topic:verb-poner-idioms-1-2", label: "Placing & Setting — Idioms (1) (2)" },
      { collection: "topic:verb-poner-idioms-2-1", label: "Placing & Setting — Idioms (2) (1)" },
      { collection: "topic:verb-poner-idioms-2-2", label: "Placing & Setting — Idioms (2) (2)" },
      { collection: "topic:verb-household-1-1", label: "Household & Objects (1) (1)" },
      { collection: "topic:verb-household-1-2", label: "Household & Objects (1) (2)" },
      { collection: "topic:verb-household-2-1", label: "Household & Objects (2) (1)" },
      { collection: "topic:verb-household-2-2", label: "Household & Objects (2) (2)" },
      { collection: "topic:verb-social-relationships-1", label: "Social Interaction & Relationships (1)" },
      { collection: "topic:verb-social-relationships-2", label: "Social Interaction & Relationships (2)" },
      { collection: "topic:verb-conflict-crime-1", label: "Conflict & Crime (1)" },
      { collection: "topic:verb-conflict-crime-2", label: "Conflict & Crime (2)" },
      { collection: "topic:verb-loss-death", label: "Loss & Death" },
      { collection: "topic:verb-admin-legal-formal-1", label: "Administrative, Legal & Formal Actions (1)" },
      { collection: "topic:verb-admin-legal-formal-2", label: "Administrative, Legal & Formal Actions (2)" },
      { collection: "topic:verb-analysis-investigation", label: "Analysis & Investigation" },
      { collection: "topic:verb-technology-digital", label: "Technology & Digital Actions" },
      { collection: "topic:verb-weather-time-duration", label: "Weather, Time & Duration" },
      { collection: "topic:verb-health-body", label: "Body & Health" },
      { collection: "topic:verb-formal-abstract-1-1", label: "Formal Actions — Abstract (1) (1)" },
      { collection: "topic:verb-formal-abstract-1-2", label: "Formal Actions — Abstract (1) (2)" },
      { collection: "topic:verb-formal-abstract-2", label: "Formal Actions — Abstract (2)" },
      { collection: "topic:verb-formal-business", label: "Formal Actions — Business & Process" },
      { collection: "topic:verb-formal-remainder-0", label: "Formal & Rare Verbs (1)" },
      { collection: "topic:verb-formal-remainder-1", label: "Formal & Rare Verbs (2)" },
      { collection: "topic:verb-formal-remainder-2", label: "Formal & Rare Verbs (3)" },
      { collection: "topic:verb-formal-remainder-3", label: "Formal & Rare Verbs (4)" },
      { collection: "topic:verb-formal-remainder-4", label: "Formal & Rare Verbs (5)" },
      { collection: "topic:verb-formal-remainder-5", label: "Formal & Rare Verbs (6)" },
      { collection: "topic:verb-formal-remainder-6", label: "Formal & Rare Verbs (7)" },
      { collection: "topic:verb-formal-remainder-7", label: "Formal & Rare Verbs (8)" },
      { collection: "topic:verb-formal-remainder-8", label: "Formal & Rare Verbs (9)" },
      { collection: "topic:verb-formal-remainder-9", label: "Formal & Rare Verbs (10)" },
      { collection: "topic:verb-formal-remainder-10", label: "Formal & Rare Verbs (11)" },
      { collection: "topic:verb-formal-remainder-11", label: "Formal & Rare Verbs (12)" },
      { collection: "topic:verb-formal-remainder-12", label: "Formal & Rare Verbs (13)" },
      { collection: "topic:verb-formal-remainder-13", label: "Formal & Rare Verbs (14)" },
      { collection: "topic:verb-formal-remainder-14", label: "Formal & Rare Verbs (15)" },
    ],
  },
  {
    slug: "cognates",
    title: "Cognates",
    description:
      "Words that share a Spanish/English root, grouped by the transformation trick that gets you from one to the other — spelling suffixes (-ción → -tion), Latin roots that don't share a spelling (tener → contain), and false friends that look related but aren't.",
    baseCollection: "topic:cognate",
    facetButtons: [
      { collection: "topic:cognate-transparent-1", label: "Identical / transparent (1)" },
      { collection: "topic:cognate-transparent-2", label: "Identical / transparent (2)" },
      { collection: "topic:cognate-transparent-3", label: "Identical / transparent (3)" },
      { collection: "topic:cognate-transparent-4", label: "Identical / transparent (4)" },
      { collection: "topic:cognate-transparent-5", label: "Identical / transparent (5)" },
      { collection: "topic:cognate-transparent-6", label: "Identical / transparent (6)" },
      { collection: "topic:cognate-transparent-7", label: "Identical / transparent (7)" },
      { collection: "topic:cognate-transparent-8", label: "Identical / transparent (8)" },
      { collection: "topic:cognate-transparent-9", label: "Identical / transparent (9)" },
      { collection: "topic:cognate-transparent-10", label: "Identical / transparent (10)" },
      { collection: "topic:cognate-transparent-11", label: "Identical / transparent (11)" },
      { collection: "topic:cognate-transparent-12", label: "Identical / transparent (12)" },
      { collection: "topic:cognate-transparent-13", label: "Identical / transparent (13)" },
      { collection: "topic:cognate-transparent-14", label: "Identical / transparent (14)" },
      { collection: "topic:cognate-transparent-15", label: "Identical / transparent (15)" },
      { collection: "topic:cognate-transparent-16", label: "Identical / transparent (16)" },
      { collection: "topic:cognate-transparent-17", label: "Identical / transparent (17)" },
      { collection: "topic:cognate-transparent-18", label: "Identical / transparent (18)" },
      { collection: "topic:cognate-transparent-19", label: "Identical / transparent (19)" },
      { collection: "topic:cognate-opaque-1", label: "Looks different (1)" },
      { collection: "topic:cognate-opaque-2", label: "Looks different (2)" },
      { collection: "topic:cognate-opaque-3", label: "Looks different (3)" },
      { collection: "topic:cognate-opaque-4", label: "Looks different (4)" },
      { collection: "cognate:false-friend", label: "False friends" },
      // Spelling-suffix families.
      { collection: "cognate:able-to-able", label: "-able → -able" },
      { collection: "cognate:acto-to-act", label: "-acto → -act" },
      { collection: "cognate:al-to-al", label: "-al → -al" },
      { collection: "cognate:ando-to-ing", label: "-ando → -ing" },
      { collection: "cognate:ante-to-ant", label: "-ante → -ant" },
      { collection: "cognate:anza-to-ance", label: "-anza → -ance" },
      { collection: "cognate:ar-to-ar", label: "-ar → -ar" },
      { collection: "cognate:ario-to-ary", label: "-ario → -ary" },
      { collection: "cognate:arte-to-art", label: "-arte → -art" },
      { collection: "cognate:cion-to-tion", label: "-ción → -tion" },
      { collection: "cognate:dad-to-ty", label: "-dad → -ty" },
      { collection: "cognate:dido-to-ded", label: "-dido → -ded" },
      { collection: "cognate:ecto-to-ect", label: "-ecto → -ect" },
      { collection: "cognate:el-to-el", label: "-el → -el" },
      { collection: "cognate:ente-to-ent", label: "-ente → -ent" },
      { collection: "cognate:es-to-s", label: "-es → -s" },
      { collection: "cognate:ible-to-ible", label: "-ible → -ible" },
      { collection: "cognate:ico-to-ic", label: "-ico → -ic" },
      { collection: "cognate:icto-to-ict", label: "-icto → -ict" },
      { collection: "cognate:ido-to-id", label: "-ido → -id" },
      { collection: "cognate:iendo-to-ing", label: "-iendo → -ing" },
      { collection: "cognate:il-to-ile", label: "-il → -ile" },
      { collection: "cognate:ivo-to-ive", label: "-ivo → -ive" },
      { collection: "cognate:ma-to-m", label: "-ma → -m" },
      { collection: "cognate:mente-to-ly", label: "-mente → -ly" },
      { collection: "cognate:orio-to-ory", label: "-orio → -ory" },
      { collection: "cognate:oso-to-ous", label: "-oso → -ous" },
      { collection: "cognate:sion-to-sion", label: "-sión → -sion" },
      { collection: "cognate:sis-to-sis", label: "-sis → -sis" },
      { collection: "cognate:tud-to-tude", label: "-tud → -tude" },
      { collection: "cognate:uro-ura-to-ure", label: "-uro/-ura → -ure" },
      { collection: "cognate:izar-to-ize", label: "-izar → -ize" },
      { collection: "cognate:ar-to-ate", label: "-ar → -ate" },
      { collection: "cognate:ificar-to-ify", label: "-ificar → -ify" },
      { collection: "cognate:inar-to-ine", label: "-inar → -ine" },
      { collection: "topic:cognate-encia-ancia-1", label: "-encia/-ancia → -ence/-ance (1)" },
      { collection: "topic:cognate-encia-ancia-2", label: "-encia/-ancia → -ence/-ance (2)" },
      { collection: "cognate:ia-to-y", label: "-ia → -y" },
      { collection: "cognate:mento-miento-to-ment", label: "-mento/-miento → -ment" },
      { collection: "cognate:ista-to-ist", label: "-ista → -ist" },
      { collection: "cognate:ismo-to-ism", label: "-ismo → -ism" },
      { collection: "cognate:ano-iano-to-an-ian", label: "-ano/-iano → -an/-ian" },
      { collection: "cognate:ico-to-ical", label: "-ico → -ical" },
      { collection: "cognate:ado-ido-to-ed", label: "-ado/-ido → -ed" },
      { collection: "cognate:ema-to-em", label: "-ema → -em" },
      { collection: "cognate:ir-to-silent-e", label: "-ir → silent -e" },
      // Latin-root families (spelling doesn't match; grouped by verb stem).
      { collection: "topic:cognate-latin-root-1", label: "Latin roots (any) (1)" },
      { collection: "topic:cognate-latin-root-2", label: "Latin roots (any) (2)" },
      { collection: "topic:cognate-latin-root-3", label: "Latin roots (any) (3)" },
      { collection: "topic:cognate-latin-root-4", label: "Latin roots (any) (4)" },
      { collection: "topic:cognate-latin-root-5", label: "Latin roots (any) (5)" },
      { collection: "topic:cognate-latin-root-6", label: "Latin roots (any) (6)" },
      { collection: "topic:cognate-latin-root-7", label: "Latin roots (any) (7)" },
      { collection: "topic:cognate-latin-root-8", label: "Latin roots (any) (8)" },
      { collection: "topic:cognate-latin-root-9", label: "Latin roots (any) (9)" },
      { collection: "topic:cognate-latin-root-10", label: "Latin roots (any) (10)" },
      { collection: "topic:cognate-latin-root-11", label: "Latin roots (any) (11)" },
      { collection: "cognate:tener-to-tain", label: "tener → -tain" },
      { collection: "cognate:poner-to-pose", label: "poner → -pose" },
      { collection: "cognate:mitir-to-mit", label: "mitir/meter → -mit" },
      { collection: "cognate:ferir-to-fer", label: "ferir/frir → -fer" },
      { collection: "cognate:ducir-to-duce", label: "ducir → -duce" },
      { collection: "cognate:tribuir-to-tribute", label: "tribuir → -tribute" },
      { collection: "cognate:struir-to-struct", label: "struir → -struct" },
      { collection: "cognate:traer-to-tract", label: "traer → -tract" },
      { collection: "cognate:escribir-to-scribe", label: "escribir → -scribe" },
      { collection: "cognate:cluir-to-clude", label: "cluir → -clude" },
      { collection: "cognate:decir-to-dict", label: "decir → -dict" },
      { collection: "cognate:ceder-to-cede", label: "ceder → -cede" },
      { collection: "cognate:primir-to-press", label: "primir/presar → -press" },
      { collection: "cognate:vertir-to-vert", label: "vertir → -vert" },
      { collection: "cognate:servar-to-serve", label: "servar → -serve" },
      { collection: "cognate:solver-to-solve", label: "solver → -solve" },
      { collection: "cognate:gerir-to-gest", label: "gerir → -gest" },
      { collection: "cognate:hibir-to-hibit", label: "hibir → -hibit" },
      { collection: "cognate:cibir-to-ceive", label: "cibir → -ceive" },
      { collection: "cognate:plicar-to-ply", label: "plicar → -ply" },
      { collection: "cognate:currir-to-cur", label: "currir → -cur" },
      { collection: "cognate:hender-to-hend", label: "hender/prender → -hend" },
    ],
  },
  {
    slug: "nouns",
    title: "Nouns",
    description:
      "Every noun, with its article bracketed to show gender — [la] mesa, [el] hombre, [el/la] estudiante — plus a subject-matter theme so you can browse by topic instead of alphabetically.",
    baseCollection: "pos:noun",
    facetButtons: [
      { collection: "topic:masc-o-1", label: "el, -o (1)" },
      { collection: "topic:masc-o-2", label: "el, -o (2)" },
      { collection: "topic:masc-o-3", label: "el, -o (3)" },
      { collection: "topic:masc-o-4", label: "el, -o (4)" },
      { collection: "topic:masc-o-5", label: "el, -o (5)" },
      { collection: "topic:masc-o-6", label: "el, -o (6)" },
      { collection: "topic:masc-o-7", label: "el, -o (7)" },
      { collection: "topic:masc-o-8", label: "el, -o (8)" },
      { collection: "topic:masc-consonant-1", label: "el, consonant (1)" },
      { collection: "topic:masc-consonant-2", label: "el, consonant (2)" },
      { collection: "topic:masc-consonant-3", label: "el, consonant (3)" },
      { collection: "topic:masc-e", label: "el, -e" },
      { collection: "topic:masc-exceptions", label: "el, exceptions to -o" },
      { collection: "topic:fem-a-1", label: "la, -a (1)" },
      { collection: "topic:fem-a-2", label: "la, -a (2)" },
      { collection: "topic:fem-a-3", label: "la, -a (3)" },
      { collection: "topic:fem-a-4", label: "la, -a (4)" },
      { collection: "topic:fem-a-5", label: "la, -a (5)" },
      { collection: "topic:fem-a-6", label: "la, -a (6)" },
      { collection: "topic:fem-a-7", label: "la, -a (7)" },
      { collection: "topic:fem-a-8", label: "la, -a (8)" },
      { collection: "topic:fem-abstract-suffix-1", label: "la, -dad/-ción/-sión (1)" },
      { collection: "topic:fem-abstract-suffix-2", label: "la, -dad/-ción/-sión (2)" },
      { collection: "topic:fem-abstract-suffix-3", label: "la, -dad/-ción/-sión (3)" },
      { collection: "topic:fem-consonant-1", label: "la, consonant (1)" },
      { collection: "topic:fem-consonant-2", label: "la, consonant (2)" },
      { collection: "topic:fem-exceptions", label: "la, exceptions to -a" },
      { collection: "topic:common-gender-professions", label: "el/la, -ista professions" },
      { collection: "topic:common-gender-other-roles", label: "el/la, other roles" },
      { collection: "gender:invariant", label: "No article" },
      { collection: "gender:neuter", label: "lo (neuter)" },
      { collection: "topic:abstract-encia-ancia-1", label: "Abstract — -encia/-ancia (1)" },
      { collection: "topic:abstract-encia-ancia-2", label: "Abstract — -encia/-ancia (2)" },
      { collection: "topic:abstract-cion-sion", label: "Abstract — -ción/-sión" },
      { collection: "topic:abstract-dad-tud-1", label: "Abstract — -dad/-tud (1)" },
      { collection: "topic:abstract-dad-tud-2", label: "Abstract — -dad/-tud (2)" },
      { collection: "topic:abstract-mento-miento", label: "Abstract — -mento/-miento" },
      { collection: "topic:abstract-ismo-and-misc", label: "Abstract — -ismo & misc" },
      { collection: "topic:abstract-general-1", label: "Abstract — General (1)" },
      { collection: "topic:abstract-general-2", label: "Abstract — General (2)" },
      { collection: "topic:abstract-general-3", label: "Abstract — General (3)" },
      { collection: "topic:abstract-general-4", label: "Abstract — General (4)" },
      { collection: "topic:abstract-general-5", label: "Abstract — General (5)" },
      { collection: "topic:abstract-general-6", label: "Abstract — General (6)" },
      { collection: "topic:abstract-general-7", label: "Abstract — General (7)" },
      { collection: "topic:abstract-general-8", label: "Abstract — General (8)" },
      { collection: "topic:people-family-rel-1", label: "People — Family & Relationships (1)" },
      { collection: "topic:people-family-rel-2", label: "People — Family & Relationships (2)" },
      { collection: "topic:people-professions", label: "People — Professions & Roles" },
      { collection: "topic:people-general", label: "People — General & Groups" },
      { collection: "topic:objects-money-business", label: "Objects — Money & Business" },
      { collection: "topic:objects-communication-media", label: "Objects — Communication & Media" },
      { collection: "topic:objects-physical", label: "Objects — Physical Items" },
      { collection: "topic:objects-misc-language", label: "Objects — Misc & Language" },
      { collection: "topic:noun-time-months", label: "Time — Months" },
      { collection: "topic:noun-time-days-periods", label: "Time — Days & Periods" },
      { collection: "topic:family-immediate", label: "Family — Immediate" },
      { collection: "topic:family-extended", label: "Family — Extended" },
      { collection: "topic:family-groups-terms", label: "Family — Groups & Terms" },
      { collection: "topic:places-home-buildings", label: "Places — Home & Buildings" },
      { collection: "topic:places-public-city", label: "Places — Public & City" },
      { collection: "topic:calendar", label: "Calendar" },
      { collection: "topic:education", label: "Education" },
      { collection: "topic:business-work", label: "Business & work" },
      { collection: "topic:money-business", label: "Money" },
      { collection: "topic:food", label: "Food" },
      { collection: "topic:technology", label: "Technology" },
      { collection: "topic:health", label: "Health" },
      { collection: "topic:government-politics", label: "Government & politics" },
      { collection: "topic:crime-law", label: "Crime & law" },
      { collection: "topic:art-culture", label: "Art & culture" },
      { collection: "topic:communication-request", label: "Communication & requests" },
      { collection: "topic:sports-recreation", label: "Sports & travel" },
      { collection: "topic:event", label: "Events" },
    ],
  },
  {
    slug: "adjectives",
    title: "Adjectives",
    description:
      "Every adjective, with its copula bracketed to show how it's actually used — [ser] importante, [estar] listo, [tener] hambre — plus comparative/superlative forms and a quality-based theme.",
    baseCollection: "pos:adjective",
    facetButtons: [
      { collection: "topic:adj-oso-osa", label: "ser, -oso/-osa" },
      { collection: "topic:adj-ico-ica", label: "ser, -ico/-ica" },
      { collection: "topic:adj-ivo-iva", label: "ser, -ivo/-iva" },
      { collection: "topic:adj-able", label: "ser, -able" },
      { collection: "topic:adj-ible", label: "ser, -ible" },
      { collection: "topic:adj-ente", label: "ser, -ente" },
      { collection: "topic:adj-al", label: "ser, -al" },
      { collection: "topic:adj-ano-ana", label: "ser, -ano/-ana" },
      { collection: "topic:adj-ser-general-1", label: "ser, general (1)" },
      { collection: "topic:adj-ser-general-2", label: "ser, general (2)" },
      { collection: "topic:adj-ser-general-3", label: "ser, general (3)" },
      { collection: "topic:adj-ser-general-4", label: "ser, general (4)" },
      { collection: "topic:adj-ser-general-5", label: "ser, general (5)" },
      { collection: "topic:adj-ser-general-6", label: "ser, general (6)" },
      { collection: "topic:adj-ser-general-7", label: "ser, general (7)" },
      { collection: "topic:adj-ser-general-8", label: "ser, general (8)" },
      { collection: "topic:estar-adj-1", label: "estar (state), (1)" },
      { collection: "topic:estar-adj-2", label: "estar (state), (2)" },
      { collection: "grammar:tener-adjective", label: "tener (idiom)" },
      { collection: "degree:comparative-er", label: "-er (harder)" },
      { collection: "degree:superlative-est", label: "-est (hardest)" },
      { collection: "degree:comparative-more", label: "more ___" },
      { collection: "degree:superlative-most", label: "most ___" },
      { collection: "degree:irregular-comparative", label: "irregular comparative" },
      { collection: "degree:irregular-superlative", label: "irregular superlative" },
      { collection: "topic:adj-abs-oso-osa", label: "Abstract quality — -oso/-osa" },
      { collection: "topic:adj-abs-ico-ica", label: "Abstract quality — -ico/-ica" },
      { collection: "topic:adj-abs-ivo-iva", label: "Abstract quality — -ivo/-iva" },
      { collection: "topic:adj-abs-able", label: "Abstract quality — -able" },
      { collection: "topic:adj-abs-ible", label: "Abstract quality — -ible" },
      { collection: "topic:adj-abs-ente", label: "Abstract quality — -ente" },
      { collection: "topic:adj-abs-al", label: "Abstract quality — -al" },
      { collection: "topic:adj-abs-general-1", label: "Abstract quality — General (1)" },
      { collection: "topic:adj-abs-general-2", label: "Abstract quality — General (2)" },
      { collection: "topic:adj-abs-general-3", label: "Abstract quality — General (3)" },
      { collection: "topic:adj-abs-general-4", label: "Abstract quality — General (4)" },
      { collection: "topic:adj-abs-general-5", label: "Abstract quality — General (5)" },
      { collection: "topic:adj-abs-general-6", label: "Abstract quality — General (6)" },
      { collection: "topic:adj-abs-general-7", label: "Abstract quality — General (7)" },
      { collection: "topic:adj-abs-general-8", label: "Abstract quality — General (8)" },
      { collection: "topic:adj-abs-general-9", label: "Abstract quality — General (9)" },
      { collection: "topic:condition-state-1", label: "Condition / state (1)" },
      { collection: "topic:condition-state-2", label: "Condition / state (2)" },
      { collection: "topic:emotion-physical-sensation", label: "Emotion — Physical Sensation" },
      { collection: "topic:emotion-feeling", label: "Emotion — Feeling" },
      { collection: "topic:personality", label: "Personality" },
      { collection: "topic:age", label: "Age" },
      { collection: "topic:value-price", label: "Value / price" },
      { collection: "topic:size", label: "Size" },
      { collection: "topic:nationality", label: "Nationality" },
      { collection: "topic:difficulty", label: "Difficulty" },
      { collection: "topic:color", label: "Color" },
      { collection: "topic:weather", label: "Weather" },
      { collection: "topic:speed", label: "Speed" },
      { collection: "topic:time", label: "Time" },
    ],
  },
  {
    slug: "adverbs",
    title: "Adverbs",
    description:
      "Words that modify a verb, adjective, or whole sentence instead of naming a thing — frequency (siempre, nunca), manner (-mente words, like rápidamente), intensifiers (muy, tan), and the question-word adverbs already covered on the Interrogatives page.",
    baseCollection: "pos:adverb",
    facetButtons: [
      { collection: "grammar:frequency-adverb", label: "Frequency" },
      { collection: "grammar:manner", label: "Manner (-mente)" },
      { collection: "grammar:intensifier", label: "Intensifiers" },
      { collection: "grammar:interrogative-adverb", label: "Interrogative" },
      { collection: "topic:adv-time-frequency", label: "Time — Frequency" },
      { collection: "topic:adv-time-relative-day", label: "Time — Relative Day" },
      { collection: "topic:adv-time-now-and-timing", label: "Time — Now & Timing" },
      { collection: "topic:location", label: "Place" },
      { collection: "topic:cognate", label: "Cognates" },
      { collection: "adv:possibility", label: "Possibility (maybe, apparently)" },
      { collection: "adv:degree", label: "Degree / approximation (almost, barely, somewhat)" },
      { collection: "adv:habitual", label: "Habitual (soler)" },
      { collection: "grammar:addition", label: "Addition (also, either)" },
    ],
  },
  {
    slug: "numbers",
    title: "Numbers",
    description:
      "Cardinals (uno, dos, tres), ordinals (primero, segundo, tercero), and the larger and more fractional numbers that come up once you're past counting on your fingers.",
    baseCollection: "pos:number",
    facetButtons: [
      { collection: "topic:cardinal-1-10", label: "Cardinal — 1-10" },
      { collection: "topic:cardinal-11-19", label: "Cardinal — 11-19" },
      { collection: "topic:cardinal-tens-and-up", label: "Cardinal — Tens & Up" },
      { collection: "topic:ordinal-1-10", label: "Ordinal — 1st-10th" },
      { collection: "topic:ordinal-11-19", label: "Ordinal — 11th-19th" },
      { collection: "topic:ordinal-20-and-up", label: "Ordinal — 20th & Up" },
      { collection: "topic:fractions-decimals-and-phone-numbers", label: "Fractions & decimals" },
      { collection: "topic:large-numbers", label: "Large numbers" },
    ],
  },
  {
    slug: "expressions",
    title: "Expressions",
    description:
      "Fixed social phrases that don't break down grammatically — please, thank you, excuse me, nice to meet you — learned whole rather than built word by word.",
    baseCollection: "topic:social-expression",
    facetButtons: [
      { collection: "expr:politeness", label: "Politeness" },
      { collection: "expr:greeting", label: "Greetings" },
      { collection: "expr:apology", label: "Apologies" },
      { collection: "expr:response", label: "Response words" },
      { collection: "expr:farewell", label: "Farewells" },
      { collection: "expr:warning-command", label: "Warnings & commands" },
      { collection: "expr:idiom", label: "Idioms & fixed phrases" },
    ],
  },
  {
    slug: "connectors",
    title: "Connectors",
    description:
      "The words that join two clauses or ideas together — the everyday set (y, pero, o, porque, si) plus reason, concession, contrast, and addition connectors for building longer sentences.",
    baseCollection: "pos:connector",
    facetButtons: [
      { collection: "grammar:sentence-structure", label: "Everyday (and, but, or...)" },
      { collection: "grammar:reason", label: "Reason" },
      { collection: "grammar:concession", label: "Concession (although)" },
      { collection: "grammar:contrast", label: "Contrast" },
      { collection: "grammar:addition", label: "Addition" },
      { collection: "topic:time-connector", label: "Time" },
      { collection: "grammar:discourse", label: "Discourse markers (that is, by the way)" },
      { collection: "grammar:sequence", label: "Sequence (then)" },
      { collection: "grammar:conditional", label: "Conditional (as long as, unless)" },
      { collection: "grammar:correlative", label: "Correlative (either...or, neither...nor)" },
      { collection: "grammar:comparison", label: "Comparison (than)" },
    ],
  },
  {
    slug: "prepositions",
    title: "Prepositions",
    description:
      "The compound and multi-word prepositions beyond the basic set already covered on the Mappings pages (de, en, con, a, por) — mostly time and location relationships: antes de, detrás de, a lo largo de.",
    baseCollection: "pos:preposition",
    facetButtons: [
      { collection: "topic:time", label: "Time" },
      { collection: "topic:location-vertical-relative", label: "Location — Vertical & Relative" },
      { collection: "topic:location-path-between", label: "Location — Path & Between" },
      { collection: "construction:map-segun-according-to", label: "According to" },
      { collection: "grammar:purpose", label: "Purpose" },
      { collection: "grammar:negative", label: "Without" },
      { collection: "grammar:exception", label: "Except" },
    ],
  },
  {
    slug: "mappings",
    title: "Spanish-to-English Mappings",
    description:
      "Spanish words whose English translation depends entirely on the sentence around them — hacer means \"do,\" \"make,\" \"ago,\" or describes the weather; dar means \"give,\" but also \"turn on,\" \"feel like,\" or \"face a direction.\" These are the words where memorizing one English gloss will mislead you. Click a Spanish chip to see the full range of what one word can mean.",
    baseCollection: "topic:multi-sense",
    facetButtons: [
      { collection: "topic:map-ser-1", label: "ser (1)" },
      { collection: "topic:map-ser-2", label: "ser (2)" },
      { collection: "topic:map-ser-3", label: "ser (3)" },
      { collection: "topic:map-ser-4", label: "ser (4)" },
      { collection: "topic:map-ser-5", label: "ser (5)" },
      { collection: "topic:map-ser-6", label: "ser (6)" },
      { collection: "topic:map-ser-7", label: "ser (7)" },
      { collection: "topic:map-ser-8", label: "ser (8)" },
      { collection: "topic:map-ser-9", label: "ser (9)" },
      { collection: "topic:map-ser-10", label: "ser (10)" },
      { collection: "topic:map-ser-11", label: "ser (11)" },
      { collection: "topic:map-ser-12", label: "ser (12)" },
      { collection: "topic:map-ser-13", label: "ser (13)" },
      { collection: "topic:map-ser-14", label: "ser (14)" },
      { collection: "topic:map-ser-15", label: "ser (15)" },
      { collection: "topic:map-ser-16", label: "ser (16)" },
      { collection: "topic:map-ser-17", label: "ser (17)" },
      { collection: "topic:map-ser-18", label: "ser (18)" },
      { collection: "topic:map-ser-19", label: "ser (19)" },
      { collection: "topic:map-ser-20", label: "ser (20)" },
      { collection: "topic:map-ser-21", label: "ser (21)" },
      { collection: "topic:map-ser-22", label: "ser (22)" },
      { collection: "topic:map-ser-23", label: "ser (23)" },
      { collection: "topic:map-estar-1", label: "estar (1)" },
      { collection: "topic:map-estar-2", label: "estar (2)" },
      { collection: "topic:map-estar-3", label: "estar (3)" },
      { collection: "topic:map-estar-4", label: "estar (4)" },
      { collection: "topic:map-estar-5", label: "estar (5)" },
      { collection: "topic:map-estar-6", label: "estar (6)" },
      { collection: "topic:map-estar-7", label: "estar (7)" },
      { collection: "topic:map-poner-1", label: "poner (1)" },
      { collection: "topic:map-poner-2", label: "poner (2)" },
      { collection: "topic:map-poner-3", label: "poner (3)" },
      { collection: "topic:map-poner-4", label: "poner (4)" },
      { collection: "topic:map-poner-5", label: "poner (5)" },
      { collection: "topic:map-tener-1", label: "tener (1)" },
      { collection: "topic:map-tener-2", label: "tener (2)" },
      { collection: "topic:map-tener-3", label: "tener (3)" },
      { collection: "topic:map-tener-4", label: "tener (4)" },
      { collection: "topic:map-poder-1", label: "poder (1)" },
      { collection: "topic:map-poder-2", label: "poder (2)" },
      { collection: "topic:map-poder-3", label: "poder (3)" },
      { collection: "topic:map-poder-4", label: "poder (4)" },
      { collection: "topic:map-hacer-1", label: "hacer (1)" },
      { collection: "topic:map-hacer-2", label: "hacer (2)" },
      { collection: "topic:map-hacer-3", label: "hacer (3)" },
      { collection: "topic:map-hacer-4", label: "hacer (4)" },
      { collection: "topic:map-dar-1", label: "dar (1)" },
      { collection: "topic:map-dar-2", label: "dar (2)" },
      { collection: "topic:map-dar-3", label: "dar (3)" },
      { collection: "topic:map-haber-1", label: "haber (1)" },
      { collection: "topic:map-haber-2", label: "haber (2)" },
      { collection: "topic:map-haber-3", label: "haber (3)" },
      { collection: "topic:map-ir-1", label: "ir (1)" },
      { collection: "topic:map-ir-2", label: "ir (2)" },
      { collection: "topic:map-ir-3", label: "ir (3)" },
      { collection: "topic:map-decir-1", label: "decir (1)" },
      { collection: "topic:map-decir-2", label: "decir (2)" },
      { collection: "topic:map-de-1", label: "de (1)" },
      { collection: "topic:map-de-2", label: "de (2)" },
      { collection: "topic:map-en-1", label: "en (1)" },
      { collection: "topic:map-en-2", label: "en (2)" },
      { collection: "topic:map-pedir-1", label: "pedir (1)" },
      { collection: "topic:map-pedir-2", label: "pedir (2)" },
      { collection: "topic:map-dejar-1", label: "dejar (1)" },
      { collection: "topic:map-dejar-2", label: "dejar (2)" },
      { collection: "topic:map-hablar-1", label: "hablar (1)" },
      { collection: "topic:map-hablar-2", label: "hablar (2)" },
      { collection: "topic:map-deber-1", label: "deber (1)" },
      { collection: "topic:map-deber-2", label: "deber (2)" },
      { collection: "topic:map-querer-1", label: "querer (1)" },
      { collection: "topic:map-querer-2", label: "querer (2)" },
      { collection: "topic:map-que-1", label: "que (1)" },
      { collection: "topic:map-que-2", label: "que (2)" },
      { collection: "topic:map-echar-1", label: "echar (1)" },
      { collection: "topic:map-echar-2", label: "echar (2)" },
      { collection: "topic:map-seguir-1", label: "seguir (1)" },
      { collection: "topic:map-seguir-2", label: "seguir (2)" },
      { collection: "topic:map-sentir-1", label: "sentir (1)" },
      { collection: "topic:map-sentir-2", label: "sentir (2)" },
      { collection: "es:quedar", label: "quedar" },
      { collection: "topic:map-ver-1", label: "ver (1)" },
      { collection: "topic:map-ver-2", label: "ver (2)" },
      { collection: "topic:map-pasar-1", label: "pasar (1)" },
      { collection: "topic:map-pasar-2", label: "pasar (2)" },
      { collection: "topic:map-contar-1", label: "contar (1)" },
      { collection: "topic:map-contar-2", label: "contar (2)" },
      { collection: "topic:map-tomar-1", label: "tomar (1)" },
      { collection: "topic:map-tomar-2", label: "tomar (2)" },
      { collection: "es:caer", label: "caer" },
      { collection: "es:volver", label: "volver" },
      { collection: "es:trabajar", label: "trabajar" },
      { collection: "es:por", label: "por" },
      { collection: "es:salir", label: "salir" },
      { collection: "es:esperar", label: "esperar" },
      { collection: "es:saber", label: "saber" },
      { collection: "es:con", label: "con" },
      { collection: "es:a", label: "a" },
      { collection: "es:conocer", label: "conocer" },
      { collection: "es:creer", label: "creer" },
      { collection: "es:valer", label: "valer" },
      { collection: "es:cargar", label: "cargar" },
      { collection: "es:si", label: "si" },
      { collection: "es:parecer", label: "parecer" },
      { collection: "es:subir", label: "subir" },
      { collection: "es:pensar", label: "pensar" },
      { collection: "es:venir", label: "venir" },
      // Common confusions — translation-choice groups that start from a Spanish
      // form. Grouped into the "Common confusions" family by navigation.ts.
      { collection: "topic:confusable-possessive", label: "su / sus / mi / tu — whose is it?" },
      { collection: "topic:confusable-verb", label: "ser vs. estar, voy a, vivir" },
      { collection: "topic:confusable-false-friend", label: "False friends (realizar, éxito, largo…)" },
      { collection: "topic:confusable-pronoun", label: "él / lo / le / se / tú" },
      { collection: "topic:confusable-determiner", label: "un vs. uno, algún vs. alguno, el" },
    ],
  },
  {
    slug: "en-mappings",
    title: "English-to-Spanish Mappings",
    description:
      "English words whose Spanish translation depends entirely on the sentence around them — \"mean\" is \"querer decir\" when you're asking what someone meant, but \"cruel\" when describing a person, and a statistical \"promedio\" in \"the mean time\"; \"him\" is \"lo,\" \"le,\" or \"con él\" depending on his grammatical role in the sentence. These are the words where one memorized Spanish equivalent will mislead you. Click an English chip to see the full range of what it can become.",
    baseCollection: "topic:en-multi-sense",
    facetButtons: [
      { collection: "topic:enmap-to-1", label: "to (1)" },
      { collection: "topic:enmap-to-2", label: "to (2)" },
      { collection: "topic:enmap-to-3", label: "to (3)" },
      { collection: "topic:enmap-to-4", label: "to (4)" },
      { collection: "topic:enmap-to-5", label: "to (5)" },
      { collection: "topic:enmap-to-6", label: "to (6)" },
      { collection: "topic:enmap-to-7", label: "to (7)" },
      { collection: "topic:enmap-for-1", label: "for (1)" },
      { collection: "topic:enmap-for-2", label: "for (2)" },
      { collection: "topic:enmap-for-3", label: "for (3)" },
      { collection: "topic:enmap-for-4", label: "for (4)" },
      { collection: "topic:enmap-for-5", label: "for (5)" },
      { collection: "topic:enmap-with-1", label: "with (1)" },
      { collection: "topic:enmap-with-2", label: "with (2)" },
      { collection: "topic:enmap-with-3", label: "with (3)" },
      { collection: "topic:enmap-of-1", label: "of (1)" },
      { collection: "topic:enmap-of-2", label: "of (2)" },
      { collection: "topic:enmap-of-3", label: "of (3)" },
      { collection: "topic:enmap-take-1", label: "take (1)" },
      { collection: "topic:enmap-take-2", label: "take (2)" },
      { collection: "topic:enmap-take-3", label: "take (3)" },
      { collection: "topic:enmap-put-1", label: "put (1)" },
      { collection: "topic:enmap-put-2", label: "put (2)" },
      { collection: "topic:enmap-put-3", label: "put (3)" },
      { collection: "topic:enmap-get-1", label: "get (1)" },
      { collection: "topic:enmap-get-2", label: "get (2)" },
      { collection: "topic:enmap-get-3", label: "get (3)" },
      { collection: "topic:enmap-go-1", label: "go (1)" },
      { collection: "topic:enmap-go-2", label: "go (2)" },
      { collection: "topic:enmap-go-3", label: "go (3)" },
      { collection: "topic:enmap-from-1", label: "from (1)" },
      { collection: "topic:enmap-from-2", label: "from (2)" },
      { collection: "topic:enmap-you-1", label: "you (1)" },
      { collection: "topic:enmap-you-2", label: "you (2)" },
      { collection: "topic:enmap-make-1", label: "make (1)" },
      { collection: "topic:enmap-make-2", label: "make (2)" },
      { collection: "topic:enmap-have-1", label: "have (1)" },
      { collection: "topic:enmap-have-2", label: "have (2)" },
      { collection: "topic:enmap-have-3", label: "have (3)" },
      { collection: "topic:enmap-set-1", label: "set (1)" },
      { collection: "topic:enmap-set-2", label: "set (2)" },
      { collection: "topic:enmap-in-1", label: "in (1)" },
      { collection: "topic:enmap-in-2", label: "in (2)" },
      { collection: "topic:enmap-give-1", label: "give (1)" },
      { collection: "topic:enmap-give-2", label: "give (2)" },
      { collection: "topic:enmap-that-1", label: "that (1)" },
      { collection: "topic:enmap-that-2", label: "that (2)" },
      { collection: "topic:enmap-keep-1", label: "keep (1)" },
      { collection: "topic:enmap-keep-2", label: "keep (2)" },
      { collection: "topic:enmap-at-1", label: "at (1)" },
      { collection: "topic:enmap-at-2", label: "at (2)" },
      { collection: "topic:enmap-how-1", label: "how (1)" },
      { collection: "topic:enmap-how-2", label: "how (2)" },
      { collection: "topic:enmap-what-1", label: "what (1)" },
      { collection: "topic:enmap-what-2", label: "what (2)" },
      { collection: "en:feel", label: "feel" },
      { collection: "en:tell", label: "tell" },
      { collection: "topic:enmap-be-1", label: "be (1)" },
      { collection: "topic:enmap-be-2", label: "be (2)" },
      { collection: "topic:enmap-be-3", label: "be (3)" },
      { collection: "topic:enmap-be-4", label: "be (4)" },
      { collection: "topic:enmap-be-5", label: "be (5)" },
      { collection: "topic:enmap-come-1", label: "come (1)" },
      { collection: "topic:enmap-come-2", label: "come (2)" },
      { collection: "en:ask", label: "ask" },
      { collection: "en:there", label: "there" },
      { collection: "en:leave", label: "leave" },
      { collection: "en:it", label: "it" },
      { collection: "en:could", label: "could" },
      { collection: "en:look", label: "look" },
      { collection: "en:fall", label: "fall" },
      { collection: "en:turn", label: "turn" },
      { collection: "en:work", label: "work" },
      { collection: "en:pay", label: "pay" },
      { collection: "en:speak", label: "speak" },
      { collection: "en:say", label: "say" },
      { collection: "en:bring", label: "bring" },
      { collection: "en:as", label: "as" },
      { collection: "en:see", label: "see" },
      { collection: "en:let", label: "let" },
      { collection: "en:like", label: "like" },
      { collection: "en:think", label: "think" },
      { collection: "en:on", label: "on" },
      { collection: "en:open", label: "open" },
      { collection: "en:want", label: "want" },
      { collection: "en:is", label: "is" },
      { collection: "en:talk", label: "talk" },
      { collection: "en:them", label: "them" },
      { collection: "en:catch", label: "catch" },
      { collection: "en:stop", label: "stop" },
      { collection: "en:know", label: "know" },
      { collection: "en:agree", label: "agree" },
      { collection: "en:if", label: "if" },
      { collection: "en:start", label: "start" },
      { collection: "en:use", label: "use" },
      { collection: "en:eat", label: "eat" },
      { collection: "en:drink", label: "drink" },
      { collection: "en:somebody", label: "somebody" },
      { collection: "en:one", label: "one" },
      { collection: "en:old", label: "old" },
      { collection: "en:bad", label: "bad" },
      { collection: "en:run", label: "run" },
      { collection: "en:her", label: "her" },
      { collection: "en:so", label: "so" },
      { collection: "en:must", label: "must" },
      { collection: "en:may", label: "may" },
      { collection: "en:been", label: "been" },
      { collection: "en:send", label: "send" },
      { collection: "en:good", label: "good" },
      { collection: "en:care", label: "care" },
      { collection: "en:are", label: "are" },
      { collection: "en:after", label: "after" },
      { collection: "en:cost", label: "cost" },
      { collection: "en:power", label: "power" },
      { collection: "en:believe", label: "believe" },
      { collection: "en:next", label: "next" },
      { collection: "en:would", label: "would" },
      { collection: "en:count", label: "count" },
      { collection: "en:stand", label: "stand" },
      { collection: "en:even", label: "even" },
      { collection: "en:this", label: "this" },
      { collection: "en:white", label: "white" },
      { collection: "en:lose", label: "lose" },
      { collection: "en:who", label: "who" },
      { collection: "en:then", label: "then" },
      { collection: "en:lend", label: "lend" },
      { collection: "en:finish", label: "finish" },
      { collection: "en:him", label: "him" },
      { collection: "en:request", label: "request" },
      { collection: "en:hard", label: "hard" },
      { collection: "en:free", label: "free" },
      { collection: "en:show", label: "show" },
      { collection: "en:hear", label: "hear" },
      { collection: "en:own", label: "own" },
      { collection: "en:break", label: "break" },
      { collection: "en:able", label: "able" },
      { collection: "en:slow", label: "slow" },
      { collection: "en:become", label: "become" },
      { collection: "en:wear", label: "wear" },
      { collection: "en:mean", label: "mean" },
      { collection: "en:hold", label: "hold" },
      { collection: "en:return", label: "return" },
      { collection: "en:all", label: "all" },
      { collection: "en:many", label: "many" },
      { collection: "en:made", label: "made" },
      { collection: "en:some", label: "some" },
      { collection: "en:the", label: "the" },
      // Common confusions — translation-choice groups that start from an English
      // word that fans out to several Spanish forms.
      { collection: "topic:confusable-pronoun", label: "you (tú/usted/ustedes/te), him (lo/le)" },
      { collection: "topic:confusable-determiner", label: "un vs. uno, algún vs. alguno, el" },
    ],
  },
  {
    slug: "phrasal-verbs-by-root",
    title: "Phrasal Verbs by Root",
    description:
      "One English verb, many particles — click \"look\" to see look at, look for, look into, look up, look after, look forward to, all in one place. Covers both true phrasal verbs (the particle shifts the meaning: give up) and prepositional verbs (a fixed preposition connects to the object: wait for).",
    baseCollection: "topic:phrasal-verb",
    facetButtons: [
      { collection: "topic:phr-be-1", label: "be (1)" },
      { collection: "topic:phr-be-2", label: "be (2)" },
      { collection: "topic:phr-be-3", label: "be (3)" },
      { collection: "topic:phr-be-4", label: "be (4)" },
      { collection: "topic:phr-be-5", label: "be (5)" },
      { collection: "topic:phr-put-1", label: "put (1)" },
      { collection: "topic:phr-put-2", label: "put (2)" },
      { collection: "topic:phr-put-3", label: "put (3)" },
      { collection: "topic:phr-take-1", label: "take (1)" },
      { collection: "topic:phr-take-2", label: "take (2)" },
      { collection: "topic:phr-take-3", label: "take (3)" },
      { collection: "topic:phr-get-1", label: "get (1)" },
      { collection: "topic:phr-get-2", label: "get (2)" },
      { collection: "topic:phr-get-3", label: "get (3)" },
      { collection: "en:set", label: "set" },
      { collection: "en:go", label: "go" },
      { collection: "en:give", label: "give" },
      { collection: "en:come", label: "come" },
      { collection: "en:turn", label: "turn" },
      { collection: "en:keep", label: "keep" },
      { collection: "en:work", label: "work" },
      { collection: "en:talk", label: "talk" },
      { collection: "en:look", label: "look" },
      { collection: "en:ask", label: "ask" },
      { collection: "en:pay", label: "pay" },
      { collection: "en:speak", label: "speak" },
      { collection: "en:fall", label: "fall" },
      { collection: "en:bring", label: "bring" },
      { collection: "en:leave", label: "leave" },
      { collection: "en:think", label: "think" },
      { collection: "en:tell", label: "tell" },
      { collection: "en:agree", label: "agree" },
      { collection: "en:eat", label: "eat" },
      { collection: "en:order", label: "order" },
      { collection: "en:drink", label: "drink" },
      { collection: "en:open", label: "open" },
      { collection: "en:have", label: "have" },
      { collection: "en:count", label: "count" },
      { collection: "en:pick", label: "pick" },
      { collection: "en:send", label: "send" },
      { collection: "en:feel", label: "feel" },
      { collection: "en:run", label: "run" },
      { collection: "en:say", label: "say" },
      { collection: "en:stand", label: "stand" },
      { collection: "en:care", label: "care" },
      { collection: "en:arrive", label: "arrive" },
      { collection: "en:lose", label: "lose" },
      { collection: "en:hear", label: "hear" },
      { collection: "en:throw", label: "throw" },
      { collection: "en:follow", label: "follow" },
      { collection: "en:make", label: "make" },
      { collection: "en:made", label: "made" },
      { collection: "en:apply", label: "apply" },
      { collection: "en:end", label: "end" },
      { collection: "en:listen", label: "listen" },
      { collection: "en:stay", label: "stay" },
      { collection: "en:hand", label: "hand" },
      { collection: "en:lend", label: "lend" },
      { collection: "en:hold", label: "hold" },
      { collection: "en:know", label: "know" },
      { collection: "en:return", label: "return" },
      { collection: "en:see", label: "see" },
      { collection: "en:help", label: "help" },
      { collection: "en:remove", label: "remove" },
      { collection: "en:believe", label: "believe" },
      { collection: "en:let", label: "let" },
      { collection: "en:pour", label: "pour" },
      { collection: "en:remind", label: "remind" },
      { collection: "en:taste", label: "taste" },
      { collection: "en:carry", label: "carry" },
      { collection: "en:mean", label: "mean" },
      { collection: "en:live", label: "live" },
      { collection: "en:sit", label: "sit" },
      { collection: "en:wake", label: "wake" },
      { collection: "en:lead", label: "lead" },
      { collection: "en:request", label: "request" },
      { collection: "en:book", label: "book" },
      { collection: "en:apologize", label: "apologize" },
      { collection: "en:borrow", label: "borrow" },
      { collection: "en:demand", label: "demand" },
      { collection: "en:catch", label: "catch" },
      { collection: "en:wait", label: "wait" },
      { collection: "en:hope", label: "hope" },
      { collection: "en:draw", label: "draw" },
      { collection: "en:call", label: "call" },
      { collection: "en:stop", label: "stop" },
      { collection: "en:pull", label: "pull" },
      { collection: "en:spend", label: "spend" },
      { collection: "en:seem", label: "seem" },
      { collection: "en:pass", label: "pass" },
      { collection: "en:weigh", label: "weigh" },
      { collection: "en:move", label: "move" },
      { collection: "en:volunteer", label: "volunteer" },
      { collection: "en:use", label: "use" },
      { collection: "en:do", label: "do" },
      { collection: "en:include", label: "include" },
      { collection: "en:owe", label: "owe" },
      { collection: "en:rely", label: "rely" },
      { collection: "en:burst", label: "burst" },
      { collection: "en:back", label: "back" },
      { collection: "en:add", label: "add" },
      { collection: "en:kick", label: "kick" },
      { collection: "en:figure", label: "figure" },
      { collection: "en:steal", label: "steal" },
      { collection: "en:blame", label: "blame" },
      { collection: "en:knock", label: "knock" },
      { collection: "en:belong", label: "belong" },
      { collection: "en:touch", label: "touch" },
      { collection: "en:show", label: "show" },
      { collection: "en:depend", label: "depend" },
      { collection: "en:appear", label: "appear" },
      { collection: "en:buy", label: "buy" },
      { collection: "en:own", label: "own" },
      { collection: "en:provide", label: "provide" },
      { collection: "en:reach", label: "reach" },
      { collection: "en:benefit", label: "benefit" },
      { collection: "en:shut", label: "shut" },
      { collection: "en:fade", label: "fade" },
      { collection: "en:find", label: "find" },
      { collection: "en:found", label: "found" },
      { collection: "en:warn", label: "warn" },
      { collection: "en:fit", label: "fit" },
      { collection: "en:exchange", label: "exchange" },
      { collection: "en:block", label: "block" },
      { collection: "en:log", label: "log" },
      { collection: "en:sort", label: "sort" },
      { collection: "en:tidy", label: "tidy" },
      { collection: "en:wear", label: "wear" },
      { collection: "en:start", label: "start" },
      { collection: "en:insert", label: "insert" },
      { collection: "en:involve", label: "involve" },
      { collection: "en:interfere", label: "interfere" },
      { collection: "en:forget", label: "forget" },
      { collection: "en:play", label: "play" },
      { collection: "en:tear", label: "tear" },
      { collection: "en:break", label: "break" },
      { collection: "en:stick", label: "stick" },
      { collection: "en:sell", label: "sell" },
      { collection: "en:reconcile", label: "reconcile" },
      { collection: "en:write", label: "write" },
      { collection: "en:sign", label: "sign" },
      { collection: "en:join", label: "join" },
      { collection: "en:address", label: "address" },
      { collection: "en:aim", label: "aim" },
      { collection: "en:head", label: "head" },
      { collection: "en:lay", label: "lay" },
      { collection: "en:refer", label: "refer" },
      { collection: "en:consist", label: "consist" },
      { collection: "en:desist", label: "desist" },
      { collection: "en:allude", label: "allude" },
      { collection: "en:deprive", label: "deprive" },
      { collection: "en:aspire", label: "aspire" },
      { collection: "en:search", label: "search" },
      { collection: "en:point", label: "point" },
      { collection: "en:allow", label: "allow" },
      { collection: "en:build", label: "build" },
    ],
  },
  {
    slug: "phrasal-verbs-by-particle",
    title: "Phrasal Verbs by Particle",
    description:
      "One particle, many verbs — click \"at\" to see look at, yell at, aim at, laugh at, arrive at. The particle is the hard part to guess as a Spanish speaker, since Spanish doesn't build meaning this way; seeing it hold constant across unrelated verbs is what makes it stick.",
    baseCollection: "topic:phrasal-verb",
    facetButtons: [
      { collection: "topic:part-up-1", label: "up (1)" },
      { collection: "topic:part-up-2", label: "up (2)" },
      { collection: "topic:part-up-3", label: "up (3)" },
      { collection: "topic:part-up-4", label: "up (4)" },
      { collection: "topic:part-out-1", label: "out (1)" },
      { collection: "topic:part-out-2", label: "out (2)" },
      { collection: "topic:part-out-3", label: "out (3)" },
      { collection: "topic:part-out-4", label: "out (4)" },
      { collection: "topic:part-to-1", label: "to (1)" },
      { collection: "topic:part-to-2", label: "to (2)" },
      { collection: "topic:part-to-3", label: "to (3)" },
      { collection: "topic:part-to-4", label: "to (4)" },
      { collection: "topic:part-in-1", label: "in (1)" },
      { collection: "topic:part-in-2", label: "in (2)" },
      { collection: "topic:part-in-3", label: "in (3)" },
      { collection: "topic:part-on-1", label: "on (1)" },
      { collection: "topic:part-on-2", label: "on (2)" },
      { collection: "topic:part-on-3", label: "on (3)" },
      { collection: "topic:part-for-1", label: "for (1)" },
      { collection: "topic:part-for-2", label: "for (2)" },
      { collection: "topic:part-for-3", label: "for (3)" },
      { collection: "topic:part-off-1", label: "off (1)" },
      { collection: "topic:part-off-2", label: "off (2)" },
      { collection: "topic:part-of-1", label: "of (1)" },
      { collection: "topic:part-of-2", label: "of (2)" },
      { collection: "topic:part-with-1", label: "with (1)" },
      { collection: "topic:part-with-2", label: "with (2)" },
      { collection: "topic:part-from-1", label: "from (1)" },
      { collection: "topic:part-from-2", label: "from (2)" },
      { collection: "particle:back", label: "back" },
      { collection: "particle:into", label: "into" },
      { collection: "particle:away", label: "away" },
      { collection: "particle:about", label: "about" },
      { collection: "particle:down", label: "down" },
      { collection: "particle:at", label: "at" },
      { collection: "particle:through", label: "through" },
      { collection: "particle:over", label: "over" },
      { collection: "particle:by", label: "by" },
      { collection: "particle:like", label: "like" },
      { collection: "particle:around", label: "around" },
      { collection: "particle:along", label: "along" },
      { collection: "particle:apart", label: "apart" },
      { collection: "particle:after", label: "after" },
      { collection: "particle:as", label: "as" },
      { collection: "particle:forward", label: "forward" },
      { collection: "particle:together", label: "together" },
      { collection: "particle:onto", label: "onto" },
      { collection: "particle:across", label: "across" },
      { collection: "particle:aside", label: "aside" },
      { collection: "particle:against", label: "against" },
      { collection: "particle:behind", label: "behind" },
      { collection: "particle:among", label: "among" },
      { collection: "particle:under", label: "under" },
      { collection: "particle:past", label: "past" },
      { collection: "particle:ahead", label: "ahead" },
      { collection: "particle:below", label: "below" },
      { collection: "particle:toward", label: "toward" },
      { collection: "particle:before", label: "before" },
    ],
  },
  {
    slug: "transformations",
    title: "Transformations",
    description:
      "One word, rebuilt into another part of speech by a suffix or prefix — power → powerful, power → powerless → powerlessness. Each pill is one transformation pattern; click it to see every word pair the catalog has for that pattern. Spanish/English cognate spelling patterns (-ción → -tion and the like) live on the Cognates page instead — this page is about English word-building alone.",
    baseCollection: "topic:transformation",
    facetButtons: [
      { collection: "morphology:suffix-ful", label: "-ful (power → powerful)" },
      { collection: "morphology:suffix-less", label: "-less (thought → thoughtless)" },
      { collection: "morphology:suffix-ness", label: "-ness (aware → awareness)" },
      { collection: "morphology:suffix-hood", label: "-hood (neighbor → neighborhood)" },
      { collection: "morphology:suffix-ship", label: "-ship (partner → partnership)" },
      { collection: "morphology:suffix-dom", label: "-dom (bored → boredom)" },
      { collection: "morphology:suffix-th", label: "-th (long → length)" },
      { collection: "morphology:suffix-ment", label: "-ment (agree → agreement)" },
      { collection: "morphology:suffix-al", label: "-al (arrive → arrival)" },
      { collection: "morphology:suffix-tion", label: "-tion (educate → education)" },
      { collection: "morphology:suffix-sion", label: "-sion (decide → decision)" },
      { collection: "morphology:suffix-ity", label: "-ity (possible → possibility)" },
      { collection: "morphology:suffix-ing", label: "-ing (weaken → the weakening)" },
      { collection: "morphology:suffix-er", label: "-er (whiten → the whitener)" },
      { collection: "morphology:suffix-er-or", label: "-er/-or (survive → the survivor)" },
      { collection: "morphology:suffix-able", label: "-able (accept → acceptable)" },
      { collection: "morphology:suffix-ible", label: "-ible (convert → convertible)" },
      { collection: "topic:morph-ish-1", label: "-ish (tall → tallish) (1)" },
      { collection: "topic:morph-ish-2", label: "-ish (tall → tallish) (2)" },
      { collection: "morphology:suffix-y", label: "-y (cloud → cloudy)" },
      { collection: "morphology:suffix-en", label: "-en (weak → to weaken)" },
      { collection: "morphology:suffix-ern", label: "-ern (north → northern)" },
      { collection: "topic:morph-ward-1", label: "-ward (in → inward) (1)" },
      { collection: "topic:morph-ward-2", label: "-ward (in → inward) (2)" },
      { collection: "morphology:suffix-ly", label: "-ly (careful → carefully)" },
      { collection: "morphology:suffix-ed", label: "-ed (weaken → weakened)" },
      { collection: "morphology:suffix-most", label: "-most (lower → lowermost)" },
      { collection: "morphology:prefix-un", label: "un- (happy → unhappy)" },
      { collection: "morphology:prefix-dis", label: "dis- (connect → disconnect)" },
      { collection: "morphology:prefix-mis", label: "mis- (understand → misunderstand)" },
      { collection: "morphology:prefix-re", label: "re- (write → rewrite)" },
      { collection: "morphology:prefix-over", label: "over- (cook → overcook)" },
      { collection: "morphology:prefix-under", label: "under- (estimate → underestimate)" },
      { collection: "morphology:prefix-fore", label: "fore- (see → foresee)" },
      { collection: "topic:morph-noun-to-adj-1", label: "noun → adjective (1)" },
      { collection: "topic:morph-noun-to-adj-2", label: "noun → adjective (2)" },
      { collection: "topic:morph-noun-to-adj-3", label: "noun → adjective (3)" },
      { collection: "topic:morph-adj-to-noun-1", label: "adjective → noun (1)" },
      { collection: "topic:morph-adj-to-noun-2", label: "adjective → noun (2)" },
      { collection: "topic:morph-adj-to-noun-3", label: "adjective → noun (3)" },
      { collection: "topic:morph-verb-to-noun-1", label: "verb → noun (1)" },
      { collection: "topic:morph-verb-to-noun-2", label: "verb → noun (2)" },
      { collection: "topic:morph-verb-to-noun-3", label: "verb → noun (3)" },
      { collection: "morphology:noun-to-verb", label: "noun → verb" },
      { collection: "morphology:verb-to-adjective", label: "verb → adjective" },
      { collection: "morphology:adjective-to-verb", label: "adjective → verb" },
      { collection: "morphology:adjective-to-adverb", label: "adjective → adverb" },
      { collection: "morphology:adjective-to-adjective", label: "adjective → adjective" },
      { collection: "morphology:verb-to-verb", label: "verb → verb (prefixed)" },
      { collection: "topic:morph-noun-to-noun-1", label: "noun → noun (1)" },
      { collection: "topic:morph-noun-to-noun-2", label: "noun → noun (2)" },
      { collection: "topic:morph-expr-to-adv-1", label: "expression → adverb (1)" },
      { collection: "topic:morph-expr-to-adv-2", label: "expression → adverb (2)" },
      { collection: "morphology:expression-to-adjective", label: "expression → adjective" },
      { collection: "morphology:number-to-expression", label: "number → expression" },
    ],
  },
  {
    slug: "verb-forms",
    title: "Past-Tense & Past-Participle Formation",
    description:
      "How English builds its past forms, grouped by sound — regular verbs split by their -ed pronunciation (played /d/, watched /t/, wanted /ɪd/), irregular verbs grouped by rhyming pattern (tell → told, sell → sold; sing → sang → sung; drink → drank → drunk). Click a pill to drill one pattern instead of memorizing verbs one at a time.",
    baseCollection: "topic:verb-form",
    facetButtons: [
      { collection: "topic:vf-past-d-1", label: "regular /d/ (played) (1)" },
      { collection: "topic:vf-past-d-2", label: "regular /d/ (played) (2)" },
      { collection: "topic:vf-past-d-3", label: "regular /d/ (played) (3)" },
      { collection: "sound:regular-past-pronounced-t", label: "regular /t/ (watched)" },
      { collection: "sound:regular-past-pronounced-id", label: "regular /ɪd/ (wanted)" },
      { collection: "topic:vf-cut-hit-hurt-1", label: "unchanged (cut) (1)" },
      { collection: "topic:vf-cut-hit-hurt-2", label: "unchanged (cut) (2)" },
      { collection: "topic:vf-cut-hit-hurt-3", label: "unchanged (cut) (3)" },
      { collection: "sound:sent-bent-lent-spent", label: "send → sent" },
      { collection: "sound:kept-slept-swept", label: "keep → kept" },
      { collection: "sound:felt-dealt-knelt", label: "feel → felt" },
      { collection: "sound:fed-bled-led", label: "feed → fed" },
      { collection: "sound:found-bound-ground-wound", label: "find → found" },
      { collection: "sound:bought-thought-taught", label: "buy → bought" },
      { collection: "sound:sold-told", label: "sell → sold" },
      { collection: "sound:built-gilt-spilt", label: "build → built" },
      { collection: "sound:made-paid-laid", label: "make → made" },
      { collection: "sound:held-beheld", label: "hold → held" },
      { collection: "sound:stood-understood", label: "stand → stood" },
      { collection: "sound:struck-stuck-snuck", label: "strike → struck" },
      { collection: "sound:clung-flung-strung-stung-swung", label: "cling → clung" },
      { collection: "sound:spun-won", label: "spin → spun" },
      { collection: "sound:lit-bit", label: "light → lit" },
      { collection: "sound:sat-spat", label: "sit → sat" },
      { collection: "sound:got-forgot-shot", label: "get → got" },
      { collection: "sound:began-rang-sang", label: "begin → began" },
      { collection: "sound:begun-rung-sung", label: "begin → begun" },
      { collection: "sound:drank-sank-shrank", label: "drink → drank" },
      { collection: "sound:drunk-sunk-shrunk", label: "drink → drunk" },
      { collection: "sound:did-hid-slid", label: "do → did" },
      { collection: "sound:blew-grew-knew-threw-drew-flew", label: "blow → blew" },
      { collection: "sound:known-grown-thrown", label: "know → known" },
      { collection: "sound:drove-rode-strode-wove-throve", label: "drive → drove" },
      { collection: "sound:driven-ridden-stridden", label: "drive → driven" },
      { collection: "sound:spoke-broke-woke-awoke", label: "speak → spoke" },
      { collection: "sound:spoken-broken-woken", label: "speak → spoken" },
      { collection: "sound:took-shook", label: "take → took" },
      { collection: "sound:taken-shaken-forsaken", label: "take → taken" },
      { collection: "sound:chose-froze", label: "choose → chose" },
      { collection: "sound:chosen-frozen", label: "choose → chosen" },
      { collection: "sound:gave-forgave", label: "give → gave" },
      { collection: "sound:given-forgiven", label: "give → given" },
      { collection: "sound:gotten-forgotten", label: "get → gotten" },
      { collection: "sound:hidden-written", label: "hide → hidden" },
      { collection: "sound:rose-arose", label: "rise → rose" },
      { collection: "sound:risen-arisen", label: "rise → risen" },
      { collection: "sound:came-became", label: "come → came" },
      { collection: "sound:run-come-become", label: "come (pp = base form)" },
      { collection: "sound:done-gone", label: "do → done" },
      { collection: "sound:tore-wore-swore", label: "tear → tore" },
      { collection: "sound:sworn-torn-worn-drawn-born", label: "swear → sworn" },
      { collection: "sound:eaten-beaten", label: "eat → eaten" },
      { collection: "sound:stolen-swollen", label: "steal → stolen" },
      { collection: "sound:proven-sewn-shaven", label: "prove → proven" },
      { collection: "sound:forbidden-bidden-trodden", label: "forbid → forbidden" },
      { collection: "sound:striven-thriven", label: "strive → striven" },
      { collection: "topic:vf-oneoff-1", label: "one-off (no rhyme partner) (1)" },
      { collection: "topic:vf-oneoff-2", label: "one-off (no rhyme partner) (2)" },
      { collection: "topic:vf-oneoff-3", label: "one-off (no rhyme partner) (3)" },
      { collection: "topic:vf-oneoff-4", label: "one-off (no rhyme partner) (4)" },
      { collection: "topic:vf-oneoff-5", label: "one-off (no rhyme partner) (5)" },
      { collection: "topic:vf-oneoff-6", label: "one-off (no rhyme partner) (6)" },
      { collection: "topic:vf-oneoff-7", label: "one-off (no rhyme partner) (7)" },
      { collection: "topic:vf-oneoff-8", label: "one-off (no rhyme partner) (8)" },
      { collection: "topic:vf-oneoff-9", label: "one-off (no rhyme partner) (9)" },
      { collection: "topic:vf-oneoff-10", label: "one-off (no rhyme partner) (10)" },
    ],
  },
  {
    slug: "verb-patterns",
    title: "Verb Patterns",
    description:
      "What comes after a verb: a bare infinitive (let him go), a full infinitive (want to go), a gerund (enjoy going), or either. English doesn't pick one by rule — each verb just takes what it takes, so this is memorized per verb, not derived from meaning.",
    baseCollection: "topic:verb-pattern",
    facetButtons: [
      { collection: "topic:vp-full-inf-1", label: "verb + to + infinitive (want to go) (1)" },
      { collection: "topic:vp-full-inf-2", label: "verb + to + infinitive (want to go) (2)" },
      { collection: "topic:vp-full-inf-3", label: "verb + to + infinitive (want to go) (3)" },
      { collection: "topic:vp-full-inf-4", label: "verb + to + infinitive (want to go) (4)" },
      { collection: "topic:vp-full-inf-5", label: "verb + to + infinitive (want to go) (5)" },
      { collection: "topic:vp-bare-inf-1", label: "verb + bare infinitive (let him go) (1)" },
      { collection: "topic:vp-bare-inf-2", label: "verb + bare infinitive (let him go) (2)" },
      { collection: "topic:vp-bare-inf-3", label: "verb + bare infinitive (let him go) (3)" },
      { collection: "topic:vp-gerund-1", label: "verb + gerund (enjoy going) (1)" },
      { collection: "topic:vp-gerund-2", label: "verb + gerund (enjoy going) (2)" },
      { collection: "construction:allows-full-infinitive-or-gerund", label: "either, same meaning (start to go / start going)" },
      { collection: "construction:allows-bare-infinitive-or-present-participle", label: "perception verbs (saw him go / saw him going)" },
      { collection: "construction:allows-full-infinitive-or-bare-infinitive", label: "help + either (help him go / help him to go)" },
      { collection: "construction:somebody-bare-infinitive", label: "verb + somebody + bare infinitive (make her go)" },
      { collection: "construction:somebody-doing-something", label: "verb + somebody + gerund (caught him going)" },
      { collection: "construction:have-something-done", label: "have something done (causative)" },
      { collection: "construction:get-something-done", label: "get something done (causative)" },
      { collection: "construction:preposition-plus-gerund", label: "preposition + gerund (before going)" },
      { collection: "construction:go-ing", label: "go + gerund (go shopping)" },
      { collection: "construction:be-present-participle", label: "progressive (to be going)" },
      { collection: "construction:auxiliary-do", label: "auxiliary do (did they go?)" },
      { collection: "construction:double-object", label: "double object (give somebody something)" },
      { collection: "topic:vp-obj-complement-1", label: "object + complement (make/expect somebody to go) (1)" },
      { collection: "topic:vp-obj-complement-2", label: "object + complement (make/expect somebody to go) (2)" },
      { collection: "grammar:passive", label: "passive (something is needed)" },
      { collection: "grammar:going-to", label: "going to (future)" },
    ],
  },
  {
    slug: "questions-negation",
    title: "Questions & Negation",
    description:
      "English splits into two systems depending on the verb. Regular verbs borrow \"do\" (don't, doesn't, didn't) for both negation and questions. Modals and be/have negate and question by direct contraction or inversion instead — can't, isn't, haven't; Can you...?, Are you...?, Have you...? Negative questions and the emphatic \"I DO like it\" both ride on the same do-support system.",
    baseCollection: "topic:question-negation",
    facetButtons: [
      { collection: "qn:do-support-negation", label: "Negation — regular verbs (don't, doesn't, didn't)" },
      { collection: "qn:modal-be-have-negation", label: "Negation — modal/be/have (can't, isn't, haven't)" },
      { collection: "qn:do-support-question", label: "Questions — regular verbs (do, does, did)" },
      { collection: "qn:inversion-question", label: "Questions — modal/be/have (Can you...? Are you...?)" },
      { collection: "qn:negative-question", label: "Negative questions (Don't you...? Isn't it...?)" },
      { collection: "qn:emphatic", label: "Emphatic (I DO like it)" },
    ],
  },
  {
    slug: "imperatives",
    title: "Imperatives & Commands",
    description:
      "Spanish commands change form for formality and number (tú vs. usted vs. ustedes) and even switch conjugation entirely between affirmative and negative — English collapses all of that into one invariant \"Close the door\" / \"Don't close the door.\" Watch the Spanish side change while the English stays put.",
    baseCollection: "topic:imperative",
    facetButtons: [
      { collection: "imp:affirmative-informal", label: "Affirmative — tú (informal)" },
      { collection: "imp:affirmative-formal", label: "Affirmative — usted/ustedes (formal)" },
      { collection: "imp:negative", label: "Negative (don't...)" },
      { collection: "imp:lets", label: "Let's — nosotros" },
    ],
  },
  {
    slug: "collocations",
    title: "Collocations",
    description:
      "Which \"light\" verb goes with which noun is arbitrary in English — you make a decision but take a risk, have a good time but set a goal — and Spanish carves it up completely differently (hacer, tomar, tener, poner all overlap in ways that don't map word-for-word). These have to be memorized as pairs, not built from the parts.",
    baseCollection: "topic:collocation",
    facetButtons: [
      { collection: "coll:make", label: "make (a decision, an effort, a call)" },
      { collection: "coll:take", label: "take (a photo, a risk, a look)" },
      { collection: "coll:have", label: "have (a good time, a hard time)" },
      { collection: "coll:set", label: "set (an alarm, a goal, the table)" },
      { collection: "coll:other", label: "give, tell, pay, hold, break, keep, catch..." },
    ],
  },
];

export function findCurriculumTopic(slug: string): CurriculumTopic | undefined {
  return CURRICULUM_TOPICS.find((topic) => topic.slug === slug);
}
