import { spawn } from "node:child_process";
const port=9401; const c=spawn("chromium",["--headless=new","--no-sandbox","--disable-gpu",`--remote-debugging-port=${port}`,"--window-size=1400,1000","about:blank"]);
const done=x=>{try{c.kill("SIGKILL")}catch{}process.exit(x)}; setTimeout(()=>{console.log("TIMEOUT");done(1)},90000);
await new Promise(r=>setTimeout(r,1600));
const L=await (await fetch(`http://localhost:${port}/json/list`)).json();
const ws=new WebSocket(L.find(t=>t.type==="page").webSocketDebuggerUrl);
let i=0;const p=new Map();const errs=[];
ws.addEventListener("message",e=>{const d=JSON.parse(e.data);if(d.id&&p.has(d.id)){p.get(d.id)(d);p.delete(d.id);return}
 if(d.method==="Runtime.exceptionThrown")errs.push("EXC "+(d.params.exceptionDetails.exception?.description||d.params.exceptionDetails.text));
 if(d.method==="Runtime.consoleAPICalled"&&d.params.type==="error")errs.push("ERR "+d.params.args.map(a=>a.value||a.description||"").join(" "));});
await new Promise(r=>ws.addEventListener("open",r,{once:true}));
const s=(m,pr={})=>new Promise(res=>{const n=++i;p.set(n,res);ws.send(JSON.stringify({id:n,method:m,params:pr}))});
const ev=async x=>{const d=await s("Runtime.evaluate",{expression:`(()=>{${x}})()`,returnByValue:true,awaitPromise:true});return d.result.result?.value};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
await s("Page.enable");await s("Runtime.enable");
await s("Page.navigate",{url:"http://localhost:3000/lesson-builder"});
await wait(4000);
// open first lesson (expand it), edit its name
await ev(`const s=document.querySelector('section[id^=lesson-]'); s.scrollIntoView(); const inp=s.querySelector('input'); const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set; set.call(inp,'Autosave test '+Date.now()); inp.dispatchEvent(new Event('input',{bubbles:true}));`);
await wait(400);
console.log("label right after edit:", await ev(`return [...document.querySelectorAll('p')].map(p=>p.textContent).find(t=>/Saving|saved|Unsaved|retry|Click a lesson/.test(t||''))`));
const nameSet = await ev(`return document.querySelector('section[id^=lesson-] input').value`);
await wait(3000);
console.log("label ~3s later:", await ev(`return [...document.querySelectorAll('p')].map(p=>p.textContent).find(t=>/Saving|saved|Unsaved|retry|Click a lesson/.test(t||''))`));
const persisted = await ev(`return fetch('/api/lesson-builder/lessons').then(r=>r.json()).then(f=>f.lessons.map(l=>l.name))`);
console.log("expected name:", JSON.stringify(nameSet));
console.log("persisted names:", JSON.stringify(persisted));
console.log("match:", persisted.includes(nameSet));
console.log("errors:", errs.length, errs.slice(0,5));
done(0);
